### ISSUE TITLE
Madness bug considering backstab and shred 

### ISSUE THREAD

**Issue by Atssilent** [Atlantiss/BugTracker#10054]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Backstabing and shredding doesn't work no matter where you (or in the case me) position yourself. Tried it on my sub rogue and wasn't able to find the back of the boss. When I gave up and tried to shadowstep behind it I basically fell below the map.

**Current behaviour**: Nothing, Cannot find the bosses back or whenever you teleport to its back you fall from the platform

**Expected behaviour**: There is a specific place that you are supposed to be able to use the 2 abilities I already mentioned and whenever you use shadowstep you must teleport to that specific place

**Steps to reproduce the problem**:

1. Start Madness
2. Use backstab on the specific place
3. Bam it works

**Revision**: ACore rev. 5781 hash. d1ed87de6e31 2018-05-17 18:34:53 +0200 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by Piklo** [comment]
proofs?

**Comment by brajevicm** [comment]
@Piklo 
Only parasites/bloods should have positional requirements.
https://www.youtube.com/watch?v=wkVOU5Eoxck

**Comment by vule456** [comment]
yes backstabs and shereding dont work, they should work no matterr of your position on deathwings arms and or mutated corruption, also currently you can backstab on the far right and left arm as they have a back and you can go around them. 1 post per 1 spell if this is about spells that require a specific positioning than you should have said so instead you wrote 2 spells in the title and now you mentione shadowstep, alos steps to reproduce problem refer to the things you do to make the bug happen, in this instance is should be 1.Start madness 2.try to use a ability with specific position requirement 3. See if it will work.  Pls edit your post so people dont get confused, also before you post something here you need to do your research becouse the devs are trying to fix bugs not make new ones.

**Comment by vule456** [comment]
@Atssilent  you need to do moar research before you start writeing something. At least check the names of the mobs. Using shadow step on Arm tentacles should always drop you in the water, using it on the wing tentacles ports you behind them, you did not state this. You said quote:"When I gave up and tried to shadowstep behind it I basically fell below the map". Your "Expected behaviour" post cointains no evidance and is completely incorrect. Example Quote: "There is a specific place that you are supposed to be able to use the 2 abilities", that good sir is incorrect, there is no specific place rather the opposite of it, on DS Madness encounter you are able to backstab the arm and wing tentacles including deatwings jaw from all angels. I pointed out the problem of your post as the title is not made acording to the guidelines the devs gave you, also the mess of all the false things said. Also how the "Steps to reproduce the problem" were written inncorectly. I pointed those things out for a reason becouse they do not follow the guidelines of this Buggtracker forum or are just incorrect as game mechanics. Saying  you "stated" the problem. Well you didnt, you tip toe from one subject to another. Im sorry if you cant handle a little criticism but your post contains falls and incorrect information. I made the comment so you would acctualy fix your current post or take the time next time you post something here to do it right.

**Comment by Aival94** [comment]
https://github.com/Atlantiss/BugTracker/issues/10044

**Comment by Piklo** [comment]
#10090, i know that this report was first but have list in that newer one
