### ISSUE TITLE
[EN][Ashenvale][Item][Quest-related]Diabolical Plans

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#1162]
Item [Diabolical Plans](http://www.wowhead.com/item=23777) does not drop or has even less droprate as it should have. It need for starting quest [Diabolical Plans](http://www.wowhead.com/quest=26443).

Droprate should be: 
1.5% for [Searing Infernal](http://www.wowhead.com/npc=6073)
1.4% for [Roaming Felguard](http://www.wowhead.com/npc=6115)
1.0% for [Mannoroc Lasher](http://www.wowhead.com/npc=11697)

Edit:It drop after finisnhing any other quest related to these demons and after killing at least 200 total.

**Comment by Bildo** [comment]
1.6% from 6073
1.4% from 6115
1% from 11697

**Comment by dstn3422** [comment]
it was reported on 2nd of jan and still not good? dafuq?

**Comment by Aival94** [comment]
i have done it before 2 weeks without doing any other quest in ashenvale to test it and is working fine but still the drop rate is low and you need to kill 80-100 sometimes if bad luck to get it.

**Comment by Malanie** [comment]
just farmed roaming felguards, searing infernals and mannoroc lasher in ashenvale (felfire hill, demon fall canyon and demonfall ridge) untill i got ~100 broken fangs. since almost every mob droped one of there it was a kinda cound how many of them had to die, and guess what. still no diabolical plans. i really wonder if this is intended
