### ISSUE TITLE
[PL][Quest][Northern Barrens]By Hook Or By Crook

### ISSUE THREAD

**Issue by siwy92** [Atlantiss/BugTracker#1256]
http://www.wowhead.com/quest=13963/by-hook-or-by-crook
 pojawia sie jak widac http://prntscr.com/5odh2v  wyswietlaja sie opcje http://prntscr.com/5odhd6  
wybieram jedna z nich http://prntscr.com/5odhzt no i tyle.. by wybrac kolejna musze wyjsc z tego okna dialogu  tym samym traci target i resetuje sie.. moge tak wybierierac w nieskonczonosc .  nie zaleznie co wybiore nic sie nie dzieje .. potem znika ..

**Comment by NONLIFE** [comment]
Ogolnie brakuje ci jeszcze 2 mozliwosci: laskotania i karmienia.
filmik: https://www.youtube.com/watch?v=rJX8C7gjYWc
Sprobuj pozniej zrobic q.

**Comment by siwy92** [comment]
na poczatku jak bralem q to mialem wszystkie.. ale teraz mam ciagle tylko te 3 .. probowalem juz wyrzucic q  i ponownie wziasc . ale nic nie pomaga .. ciagle to samo

**Comment by NONLIFE** [comment]
mi wrocily wszystkie opcje po pewnym czasie wiec warto poczekac troche ;]

**Comment by siwy92** [comment]
no wiec poczekam :) oby nie za dlugo he :)

**Comment by Angelo-DM-** [comment]
Video as example: https://www.youtube.com/watch?v=rJX8C7gjYWc

I think that the problem is the dialog box when you choise an action... it does not disapper! instead you need to "x" it or to click "goodbye" in order to re-speak with the razormare, otherwise if you click on another choise in the same dialog box, nothing happens...

**Comment by BAndysc** [comment]
Fixed in rev. 4464
