### ISSUE TITLE
[EN][Quest][The lost Isles]The Pride of Kezan

### ISSUE THREAD

**Issue by kazy14** [Atlantiss/BugTracker#1426]
http://www.wowhead.com/quest=25066 the quest is working pretty well exept the plane that you are controling is flying only forward left and right .... no up and down and its pretty hard to aim at the other aircrafts

**Comment by agusgk13** [comment]
i couldn't do this mission, i'm stuck with my goblin since i can't do anything else

**Comment by mathcampbell** [comment]
States when entering the vehicle "you are in the wrong zone", after which it puts you in the plane but you can't fly - it acts as a ground mount only. All other functions appear to workout obviously you cannot complete the quest as it's not possible to shoot down the alliance planes from the ground.  Qui an easy fix but frustrating since this is a core quest line. Should be fixed ASAP as without it, no goblin players can progress.

**Comment by Tj20** [comment]
The quest is buggy, but completable. When you enter the plane it behaves like a ground mount. If you fly the plane against a tree or wall it will start to fly but only on a specific height, you can't go up or down. Still, it's enough to kill 10 enemies and finish the quest. It's not great but it's somehow completable at least.

![pic](http://i.imgur.com/1L399KC.jpg)

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/3593

**Comment by crazyheifer34** [comment]
Can't even get into the plane to do the quest
