### ISSUE TITLE
[EN][NPC][Shadowfang Keep-5n]Commander Springvale

### ISSUE THREAD

**Issue by cosminush** [Atlantiss/BugTracker#1515]
That npc run his skills too fast, and it's like instant kill for players of lvl ~20.
http://www.wowhead.com/npc=4278

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/issues/178

And he was always hitting like a truck

**Comment by Tj20** [comment]
I've just done this with my level 19 pala tank and got my ass absolutely pounded.
To me it seems this is because he is using his adds, which should only appear on heroic difficulty.

**Expected behaviour:** There are a [Tormented Officer](http://www.wowhead.com/npc=50615/tormented-officer) and a [Wailing Guardsman](http://www.wowhead.com/npc=50613/wailing-guardsman) in front of him, but you can pull them separately from the boss, see [video](http://youtu.be/gEqDtuB15zg?t=6m8s). During the boss fight no further adds should appear.

![Screenshot Retail](http://i.imgur.com/b9mXK10.jpg)

According to the Dungeon Journal, Wailing Guardsman and Tormented Officer are heroic difficulty only:

![HC only](http://i.imgur.com/k97L4dM.jpg)

**Observed behaviour:** The boss start with both adds, you cannot pull the adds without also pulling the boss. Also he will periodically call 2 more adds like he should do on HC only.
A look in the combatlog shows: the adds themselves do all the stuff they do on heroic: Unholy Empowerment, Mortal Strike heal reduction, Forsaken Abilities (forsaken abilities (-40% armor/HP/healing/damage/speed)).

![boss needs his bros](http://i.imgur.com/pyNwtkx.jpg)

**Comment by Tj20** [comment]
Speaking of Heroic mobs: After Springvale you encounter 2 packs of 4 [Stone Sleepers](http://www.wowhead.com/npc=3870/stone-sleeper) and [Lesser Gargoyles](http://www.wowhead.com/npc=3869/lesser-gargoyle#drops). Those packs are also brutal: 1 mob melee crit = 360 damage on my tank with 700 HP. And there are 4 of them. I've been a [one-shot](http://i.imgur.com/AsZtQ5w.jpg).

According to the [video](http://youtu.be/gEqDtuB15zg?t=9m3s) mentioned above, there should only be 2 mobs in each group, not 4. (Stone Sleepers, Lesser Gargoyles are Heroic only)

[pic: group 1](http://i.imgur.com/mxSIoE0.jpg)

[pic: group 2](http://i.imgur.com/todnqRC.jpg)

**Comment by captjvmoore** [comment]
I can confirm this, as my lvl 18 full-heirloomed and blues warrior tank got anal probed last night. I was literally 2-shotted before our healer could even cast a healing spell. Eventually, we managed to down him, but only thanks to our insane dps.

**Comment by Tj20** [comment]
(added a screenshot of Commander Springvale when you first visit him)

**Comment by Wolffenstein** [comment]
Fixed everything in rev 4284.
