### ISSUE TITLE
[PL] [Talent] [Shaman] Focused Insight

### ISSUE THREAD

**Issue by Vyrtuz** [Atlantiss/BugTracker#1735]
http://cata.openwow.com/spell=77796

"After casting any Shock spell (...)"

Warunek spełniający "proc" bufka powinien wystąpić podczas rzucenia dowolnego shock spella (niezależnie czy trafi w cel czy nie).

U nas występuje dopiero wtedy kiedy shock pomyślnie trafi wroga.

**Comment by Jenovas** [comment]
Znalazłem z 4 tematy w ciągu 5 minut gdzie jest napisane:
"Focused Insight - note that the shock must actually hit for damage for the talent to proc"

"After casting any Shock spell, your next heal's mana cost is reduced by ... I could indeed use it without the hit boost, but should I?"

"Focused Insight: Empowers heals after using any shock spell, depends on your ... For those who wonder "why should i roll hit, iam healer?!""

"You might be skeptical on the viability of this talent because,
1. three points of this can be used else where
2. 17% miss chance"

Tak więc wynika że jak nie trafisz to ma nie być buffa.
Zamykam.

**Comment by nowusss** [comment]
przecież wyraźnie jest napisane After casting.... a te tematy który przytoczyłeś to wypowiedzi użytkowników, więc to jest żaden dowód

**Comment by Jenovas** [comment]
Nie wszystko działa tak jak jest w opisie.

**Comment by nowusss** [comment]
> Nie wszystko działa tak jak jest w opisie.
a niby dlaczego? 

[http://www.tauri-veins.tk/restoration-shaman-wow-pve-healing-rotation-cooldowns-abilities](url)
punkt 4.2.5

**Comment by nowusss** [comment]
[http://www.mmo-champion.com/threads/840216-Telluric-Currents-Focused-Insight/page3](url)

"First:
You don't need Elemental Precision for both talents.
Focused Insight works without hitting the target, and I rather have an instant Ghostwolf instead of wasting points in the elemental tree for EP."

**Comment by nowusss** [comment]
do otwarcia? :)

**Comment by Vyrtuz** [comment]
Pozwolę zacytować:
"...Focused Insight causes your shock spells to grant you the Focused Insight buff (even if they miss their target), increasing your next heal's effectiveness by 30%..."
(http://www.tauri-veins.tk/restoration-shaman-wow-pve-healing-spec-builds-talents-glyphs)
