### ISSUE TITLE
[EN][Spell][Death Knight] Blood strike

### ISSUE THREAD

**Issue by jagoan1** [Atlantiss/BugTracker#1773]
http://www.wowwiki.com/Blood_Strike
The amount of bonus damage Blood Strike was receiving per disease was inconsistent with its tooltip.
the bonus per disease should be 12.5% but when i hit it the bonus was like 100% per disease.

my weapon damage is around 1000k, i hit 1200 (blood strike) without disease, around 2000 with one disease and around 3000 with 2 disease

thanks

**Comment by Varchord** [comment]
Weapon damage has range from  X to Y. Skills that calculate damage based on weapon damage percentage pick a value from this range. The bigger the range, the more unpredictable output damage. That's why it can vary so much. If you want to test such things you have to pick a weapon with lowest range of damage possible (for example 2-3) to eliminate this randomness

**Comment by jagoan1** [comment]
thanks yeah i noticed that but i think the problem is the bonus damage per disease it should be 12.51% per disease but i feel like its 100% per disease. if my mean damage of my weapon is 1000 approximately it will hit 1706.25 with 2 disease. oh and my dk still level 78 so BS = 80% weapon damage + 565, 12.5% bonus per disease. i just dont feel rite my BS hit much more than that. or its just my bad calculation. 
i tried with 21-32 wep damage but it feels the same .640 no disease, 1490 with 1 disease, 1859 with 2 disease.

**Comment by Jenovas** [comment]
Fixed in rev 4285
