### ISSUE TITLE
[EN][Talent][Rogue] Find Weakness

### ISSUE THREAD

**Issue by MorbidMike** [Atlantiss/BugTracker#1788]
Find Weakness does not seem to work properly. I have found two issues with it:

1) When I Ambush a mob and I use Hemorrhage on that same mob afterwards, the Find Weakness debuff gets replaced by the Hemorrhage debuff. The Find Weakness debuff should stick for the full 10 seconds and not be replaced.

2) When I Ambush it randomly will or will not apply. Especially when I have used Premeditation or Shadowstep, Find Weakness will usually not apply for some reason.

**Comment by lastkiss** [comment]
It works fine with Find Weakness talent. I tested on mobs and dummy and hemo doesn't replace the Find Weakness debuff. Also works fine after shadowstep and premeditation. 

I think the problem is with some of your addon. It may be some kind of visual bug caused by the addon. Try tu disable them and then check if Find Weakness debuff still disappears.

**Comment by MorbidMike** [comment]
You are entirely correct. It was the result of my UI bugging.
