### ISSUE TITLE
[EN][Spell][Rogue] Shadowstep

### ISSUE THREAD

**Issue by GtGraphics6** [Atlantiss/BugTracker#1868]
The problem is i just keep dying after using shadowstep, i just fall through the map, cant release spirit => macro. Most of the times it happens while in raids/dungs, for example a week ago i was doing ICC 25N .. used shadowstep on 2nd boss and bam, no ICC for me. Just used it on baron ashbury in heroic Shadowfang keep and i was suddently teleported under him in some weird shit area where u cant use mounts?! :D. The worst part is that it can happen everywhere - bg, dung,raid, random place in azeroth. I am friggin scared to use shadowstep its like a shadostepophobia. Pls for rogue`s sake make it stop

**Comment by lastkiss** [comment]
Its the first time I see such complain. Never had any bug with shadowstep. Falling into textures occured in raid instances with Killing Spree but never with Shadowstep
On bgs and arenas it works fine for me.

**Comment by GtGraphics6** [comment]
it actually happens to me quite a lot.. u shadowstep a random guy and u fall through the map,now that happens mostly in dungeons and raids, and i dont remember falling through the map in a bg tbh, but in dungs and raids all the time,

**Comment by GtGraphics6** [comment]
Guys, you really need to fix it. Last evening i tried to do cho gall with my guild and i kept falling through the ground down to sinestra or at shadowfang keep on 1st boss, or in nagrand arena. Please ;s

**Comment by Aviannaqt** [comment]
#4091
#4382

**Comment by gumby123** [comment]
This bug is very annoying. It seems like currently there is no vertical (z) movement implemented for shadowstep. For instance, you can't shadowstep to a target that's in the air.

**Comment by knasen88** [comment]
Shadowstep currently ignores "z" coordinate in the xyz coordinate wow uses(3d) and z is the height coordinate. You can't shadowstep a flying object and end up in the air on atlantiss, it puts you on the ground, behind the target.

Maybe it's the problem since the spells tries to target the lowest ground possible and in some enviroments it makes you fall through, e.g. nefarian, cho'gall, conclave.

I'm not sure but maybe adding a little height after each shadowstep jump would help things as a quick fix, Making you teleport to you target and a few centimeters up in the air so you end up falling for 0.1s before touching ground, eliminating the falling through ground part.

**Comment by Wolffenstein** [comment]
Check again in rev 4701.

**Comment by knasen88** [comment]
You fixed the "z" coordinate, I tested it in a duel but the falling through ground is still there. Atleast in conclave but in that place you can't even stealth properly. I have yet to try it in nefarian or cho'gall room

http://gfycat.com/EnviousPlumpGourami

This is from today

**Comment by Genomnomnomnom** [comment]
Shadowstep took me under textures on the flat ground :<
