### ISSUE TITLE
[EN][Quest] Echoes of Tortured Souls

### ISSUE THREAD

**Issue by GtGraphics6** [Atlantiss/BugTracker#1999]
http://www.wowhead.com/quest=24499/echoes-of-tortured-souls

When u kill the bosses it doesnt count it and it stays on 0/1 => u cant advance to the other dungeons

**Comment by Quban** [comment]
Quest works now.

**Comment by Tj20** [comment]
I have a "special" problem with this quest:

I forgot to take this quest on the PTR. Then I cleared the Forge of Souls once. When I wanted to enter the next dungeon "Pit of Saron" it said that I have to do this quest first.

The problem is: Jaina doesn't offer me this quest any more.

I reset the instance, made sure that I don't have an ID (it was normal mode anyways), I cleared my cache folder, made sure with another char on the PTR that Jaina does in fact offer the quest...
The problem persists: Jaina doesn't offer the quest any more for my paladin although I don't have the quest completed yet.

**Comment by Syruzak** [comment]
quest doesn't appear on any of my characters not even on first run, Jaina doesn't offer it and therefore making it impossible to move onto next dungeon

![wowscrnshot_083015_235128](https://cloud.githubusercontent.com/assets/13981280/9569671/22e76f92-4f72-11e5-869e-32962e269c57.jpg)

**Comment by Syruzak** [comment]
works if you first complete quest http://www.wowhead.com/quest=24510/inside-the-frozen-citadel
received from http://www.wowhead.com/npc=37776/apprentice-nelphi
in Dalaran
