### ISSUE TITLE
[EN][Core][High priority] Absorbs.

### ISSUE THREAD

**Issue by Tyroth** [Atlantiss/BugTracker#2099]
There is a problem with absorbs and direct damage. The thing is absorbs can only absorb up to 10%-50% of their real value. There is no problem with dots damage - it works just fine, but absorbs are just useless vs direct damage. http://i.imgur.com/dgntloL.jpg

**Comment by Arcadia713** [comment]
Video soon, just need time to upload :P

**Comment by Wolffenstein** [comment]
When did it start to happen? After which revision?

**Comment by Tyroth** [comment]
This might have occured since the very beggining of 4.3 if nobody checked it.

**Comment by MasterK15** [comment]
its only pvp bug  or pve too ?

**Comment by Tyroth** [comment]
I don't know. I don't play pve, but if you could check it, that'd be nice.

**Comment by Tj20** [comment]
I've had a look in an old Steamvault run log with a disci priest from 1 week ago. The absorb numbers do not seem to add up either, although not so drastically.

[Example 1 - spell damage](http://pastebin.com/M238GaHp): Fresh PW:S has a value of 5879. 723 spell damage gets absorbed. When Shield expires it says: 4566 left (like it has absorbed 1313 damage, not only 723 according to the combat log).

[Example 2 - spell+melee](http://pastebin.com/tU3vKA2k) Fresh PW:S on the tank has a value of 5879.When the shield is reduced to 0 and thus removed, it has absorbed only 4839 damage I think.

[Example 3](http://pastebin.com/gUy3hr35) PW:S starts and ends with a value of 5879 because the recipient did not receive any damage. This is fine obviously.

Just throwing this out there, it has maybe nothing to do with your case because my numbers seem closer to where they should be and maybe I'm just forgetting something, like damage reduction through armor in example 2 cannot be found in the combat log or something.

**Comment by Arcadia713** [comment]
We observed that if something hits harder in shield - amount of absorb is less effective.
If i hit with frostbolt non-crit for 9k - it absorbs this fully, but second direct damage goes through absorb (doesn't matter if its 1k or 10k).
When i had crit - example ~18k - PW:S absorbed about 8-9k dmg and whole damage hit priest... 

It's a little confusing and i don't see any linear relations between damage taken and absorbed - it's just soooo random. 
But one thing is sure - when something hits absorbed target - just a part of that damage is absorbed, rest goes through and even your absorb is still on you, 100% sure next direct damage will damage you and remove absorb (like bubble doesn't exist anymore).

Please mark it as high priority on "to do" list because this is gamebreaking bug for many classes - especially in PvP. There is no point to use PW:S, Ice Barrier, Mana Shield etc. actually.

**Comment by debtheone** [comment]
it does exist since prepatch

**Comment by Malylolek** [comment]
:( dont make my cry Priest sill can do something

**Comment by Wolffenstein** [comment]
Fixed in rev 4313.

**Comment by Tj20** [comment]
Damn, fixed in a couple of hours... that's impressive.
