### ISSUE TITLE
[EN][Macros][Druid] Druid powershifting macro

### ISSUE THREAD

**Issue by Iambugged** [Atlantiss/BugTracker#2136]
Druid powershifting macro doesn't work
/cast !Cat form
is supposed to be spammable and shift you out of cat for only very short part of a second and immediately shift you back in. (this is used to remove slows)
Sometimes though, when I click this macro multiple times it just straight up cancels form, making me have to worry about manually shifting back in.
This exact same thing happens with bear form too.

http://www.wowhead.com/spell=768/cat-form
http://www.wowhead.com/spell=5487/bear-form

**Comment by Kuszki** [comment]
have you noticed this problem just few days ago or its common for you? i use this macro since i created my druid and i have never experienced this problem.

important is that i never spam my button very hard... i will try to reproduce it soon and tell you what i know about it.

**Comment by Iambugged** [comment]
I noticed this as soon as I started using this macro on this server. At first I thought it was about latency too but my latency isn't even that bad here (around 70-80ms). And it hasn't happened on other 4.3.4 servers, even though I had higher latency there.

**Comment by BeVeR86** [comment]
I don't have this problem as I just spam the Cat form key. Anyway, tested your macro and indeed it doesn't work as expected when GCD is up (it does work nicely when there is no GCD). I personally think this is not a bug. If I remember correctly this was blizzards way of stopping people from using macro's that could be used for botting (not sure though but that's what I thought).
I don't think macro's are supposed to take GCD into account.

So to fix your macro so it works just like yours but makes you able to spam it in case GCD is up:
/cancelform [stance:3]
/cast [nostance] Cat Form

Have fun :)

**Comment by BeVeR86** [comment]
Just some info on the subject from wowwiki.com:

<i>Multiple actions with one click
In general, you cannot cast more than one spell with a single click of a macro. Most spells and some items trigger the global cooldown (GCD) which keeps you from taking too many actions at once. Even if a spell fails to cast, if it would trigger the GCD, it prevents subsequent /casts in the macro from running. This was not the case prior to patch 2.0 which is why you may still come across macros like the following:

<i>/cast Overpower
/cast Execute
/cast Mortal Strike
/cast Sunder Armor
Macros like this do not work anymore. As soon as Overpower fails to cast, the game will block all the other spells from casting as well, even though the GCD is not actually triggered.</i>

Source: http://www.wowwiki.com/Making_a_macro

So the game works as expected, GCD should stop a macro from casting subsequent abilities.

**Comment by Kuszki** [comment]
> /cancelform [stance:3]
> /cast [nostance] Cat Form

is nice, but lags may crash it - i have many "double check" macros like
`/cast [conditions] spell_1; !spell_2`

like:
`/cast [stance:3] Skull Bash; !Cat Form`
or:
`/cast [nostealth] !Prowl`

its realy efective

also you need to remember to dont break your spell button.

**Comment by Iambugged** [comment]
[quote]/cancelform [stance:3]
/cast [nostance] Cat Form[/quote]
This seems to do the exact same thing as my !Cat Form macro.

I did some more testing and it seems that when you spam the macro, for the first half of the cgd it wont cancel your form because the game itself has a mechanic that prevents cancelling forms instantly when spammed. Seems that lock time is just way too short here as it didn't happen on other servers no matter how long I spammed it..

**Comment by Iambugged** [comment]
Just in case any other ferals with same problem find themselves here, I discovered another macro that solved the problem. Instead of "/cast !Cat Form" I use "/cast Cat Form" twice and it does the exact same thing but does not cancel form when spammed. Seems "!" for macros is just broken here.

**Comment by Milton3450** [comment]
Confirmed. Spamming the shifting macro gets you out of form sometimes when there is between 0.5 - 0 sec left of the GCD.

**Comment by Milton3450** [comment]
This bug is really gamebreaking for druids.

**Comment by Isuel** [comment]
well, I noticed it not only happens to power shifting, but also when u spam the cat form button too fast (takes u out, in and out of cat form instantly)
