### ISSUE TITLE
[EN] [WORLD] unable to perform actions due to combat persistance

### ISSUE THREAD

**Issue by okevino25** [Atlantiss/BugTracker#2180]
it seems that whenever i finish a fight, i cant equip items or eat/drink nor logout, in my character portrait thought, it does not appear in red designating that i am in combat but when i want to do any of those actions metioned before, the game refuses, telling me that i am in combat..... my charecter is a night elf (might help out) i do not know if anyother races/zones react this way

**Comment by okevino25** [comment]
may i get an explenation if this gets closed like the one before?

**Comment by xolon** [comment]
its due the combat bug, sometimes you don't lose agro on some mobs that you didn't kill. 
Those mobs freeze in 1 position and they wont attack you, you will keep cb forever if you dont kill that mob or alt+f4

**Comment by Iambugged** [comment]
It is indeed a combat bug which happens fairly often on private servers, regardless of your race or class. Usually the only way to fix it is alt+f4, which sadly makes you die and have to run to your corpse as ghost.. But since you are night elf you can use your racial spell Shadowmeld to take you out of combat.

**Comment by Bildo** [comment]
Bug tracker is not a place for guessing or worse for reporting bugs without any information (like your report).
