### ISSUE TITLE
[ENG][Quest][Zul'Drak] Wanted: Ragemane's Flipper

### ISSUE THREAD

**Issue by Technowizard15** [Atlantiss/BugTracker#2230]
http://www.wowhead.com/quest=12857/wanted-ragemanes-flipper

When looting Ragemane one gets a grey item called "Severed Flipper" (http://www.wowhead.com/item=39222/severed-flipper) but you should get "Ragemane's Flipper" (http://www.wowhead.com/item=41115/ragemanes-flipper). The severed flipper shouldn't even be in Ragemane's loot table (http://www.wowhead.com/npc=29664/ragemane).

**Comment by Canderous** [comment]
The [Severed Flipper](http://www.wowhead.com/item=39222/severed-flipper) is fine, you can see on its "Dropped by" tab that it's dropped by Ragemane (or selecting all loot at Ragemane, not just Noteworthy). [Ragemane's Flipper](http://www.wowhead.com/item=41115/ragemanes-flipper) should be a 100% drop rate though, wowhead takes into account kills when people don't have the quest, that's why it's 87% there. When I did the quest, he dropped it, so if you kill him a few times, it will probably drop, but it should be 100%.

**Comment by Bildo** [comment]
Fixed by Navedonar:
