### ISSUE TITLE
[En][Core][Battlegrounds] Strand of the Ancients

### ISSUE THREAD

**Issue by sshad00w** [Atlantiss/BugTracker#2664]
Zone:
http://www.wowhead.com/zone=4384/strand-of-the-ancients

BUGS:
http://www.wowhead.com/npc=27894/antipersonnel-cannon - we can sometimes move this cannon (i dont know how, but i see ppls as do that) - its a very nice bug.

START BATTLE - sometimes when we join to bg, we are not on deck, we are on the deep waters.

**Comment by Swepy** [comment]
I dont know if its just me, but sometimes i dont see the bombs that i or the enemy place at the gates, so they cannot be disarmed. Maybe its just because when you place a bomb it puts it front of you, not in the place where you stand so when you do it in front of a gate, it puts it into the gates so you cant reach it to disarm.

**Comment by ShockRW** [comment]
GATES
