### ISSUE TITLE
[EN][Quest][Gilneas] Quest:Grandma's Cat

### ISSUE THREAD

**Issue by grimrzr** [Atlantiss/BugTracker#2678]
I do the worgen questline, and I stucked with Quest:Grandma's Cat because client bring me an error. I tried everything: reinstall client, create another character, disable all addons, all time, same result. I can't even log onto my char, when loading screen it's finished, the error pops up. On other race, like human or nightelf the client works normally.

![error](https://cloud.githubusercontent.com/assets/11515305/6682129/053b136e-cc7c-11e4-9480-ac7cebe02301.JPG)

**Comment by krecik88** [comment]
For now u can use unstuck option.

**Comment by Aival94** [comment]
I think that bug is related to phase of quests(or sth like this) rathen than the quests itself as for some players happen during this quest and other during the quest mention in #2493. For me for example it happened during the one in #2493 but no more wow errors during this quest mention in this post(after i use unstuck option)

**Comment by grimrzr** [comment]
I used unstuck, same thing. Nevermind, I rolled a Night Elf :(

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/3329
