### ISSUE TITLE
[EN] [Blackrock Dephs] [Mechanic] Door opening mechanic not working

### ISSUE THREAD

**Issue by captjvmoore** [Atlantiss/BugTracker#271]
In Blackrock Dephs, the Shadowforge Key is used on a wheel object to activate a mechanic that opens a passage door. Instead, the wheel object is usable without the key, but the door still doesn't open. To obtain this key, there should be an NPC somewhere inside the passages below the BRD summoning stone. This NPC is only interact-able with while your character is dead. This NPC IS missing.

Furthermore, while dead, you are automatically given a flying mount. Unfortunately, this mount does not fit through the passage ways below the BRD summoning stone, making interacting with the NPC that gives the quest for the Shadowforge key impossible.

http://www.wowwiki.com/Shadowforge_Key
http://www.wowwiki.com/Quest:Dark_Iron_Legacy
http://www.wowwiki.com/Franclorn_Forgewright

**Comment by Tj20** [comment]
I've tried the new mole machines now and they work nicely, you can reach most of the bosses now. 

Now only the areas West Garnison and Grim Guzzler are still unreachable, because of the door opening mechanic described here.

By the way: I've defeated the 7 dwarfs, and the [Chest of the Seven](http://www.wowhead.com/object=169243) spawned, but it contained no loot. Since it is another gameobject, I figured I might put that here.

**Comment by Wolffenstein** [comment]
"As of 4.0.3a, this is no longer needed, or for that matter, available to get. You can no longer pick up the quests, and the previously locked gates are now openable by anybody, so don't waste your time."

The Shadowforge Key is obsolete as well as the quest chain.

**Comment by Tj20** [comment]
True, the doors (despite marked as "locked" in green via mouseover) can be opened by anybody, and the big wheel mechanism can be used also.

Just to clarify: The other 2 bugs mentioned (the wheel does not open the door to the middle part of the instance / while dead you get a flying mount so you won't fit through the door) however remain.

**Comment by Wolffenstein** [comment]
Fixed everything in rev 4287.
