### ISSUE TITLE
[EN][Quest][Western Plaguelands] Zen'Kiki and the Cultists

### ISSUE THREAD

**Issue by hiralovesgiita** [Atlantiss/BugTracker#2763]
http://www.wowhead.com/quest=26955/zenkiki-and-the-cultists

Bears are out of cage
For 30-40 minute wait none of them spawned back

I only managed to find 3 working cages out of 4.

**Comment by lourrific** [comment]
http://www.wowhead.com/quest=26955/zenkiki-and-the-cultists

As of May 15, 2015 this quest is still bugged. When I free the bear Zen'Kiki does not healing them.

**Comment by davidrivasdos** [comment]
17 of september...still bugged

**Comment by Nightend1** [comment]
+1

**Comment by LaveniaGithub** [comment]
Already reported: https://github.com/Atlantiss/BugTracker/issues/6755

**Comment by xStiven** [comment]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Quest is not works,

**Current behaviour**: Bears isn't resetting in their cages, they just stayed near cages, after some one freed them. Probably if restart server, they will reset in their cages, too. But still a bug.

**Expected behaviour**: Open cages->npc heal them> repeat 4 times > quest done. 
https://www.youtube.com/watch?v=jNZoVs6SX5c

**Steps to reproduce the problem**:

1. This form is rudiment for quests.
2. Pick the quest. 
3.  When come to cages - bears standing near cages, because probably some else has done this quest before.
4. Open cage - nothing happening.

**Revision**: ACore rev. 5269 hash. e09b68089d49 2016-12-14 23:02:45 +0100 (4.3.4 branch) (Unix, RelWithDebInfo)

BUMP!

**Comment by GamingAnonymous** [comment]
Still bugged, 2 years on.

**Comment by KasiaSmolarska** [comment]
+1
