### ISSUE TITLE
[EN][Spell][Hunter] Black Arrow

### ISSUE THREAD

**Issue by Kejmil** [Atlantiss/BugTracker#2766]
http://www.wowhead.com/spell=3674/black-arrow#changelog
http://wow.gamepedia.com/Black_Arrow

As stated in http://atlantiss.eu/community/viewtopic.php?f=91&t=1235&p=7764#p7764, the problem is that on our server we have old, powerfull ticks from 4.3.2- in fast ticking dot from 4.3.2+, resulting in overall 100% dmg increase for hunters from this skill

**Comment by Jenovas** [comment]
Fixed in rev 4373

**Comment by serianx** [comment]
I don't understand this change, correct me if i'm wrong but the patch note said it now ticks every 2 second instead of 3 but leaving the total damage unchanged

(duration/3)*c1*AP=(duration/2)*c2*AP <------- total damage

means c2= (2/3)*c1

so the new coefficient should be 66.6% of the previous one, not 50% like the patch note says

**Comment by Kejmil** [comment]
15sec duration and 3sec for tick - 5 ticks
20sec duration and 2sec for tick - 10 ticks
same damage overall means that in faster ticking dot we have 0,5 of the old dmg per tick
