### ISSUE TITLE
[ENG][Professions][Fishing] Can't fish in Dalaran.

### ISSUE THREAD

**Issue by gala320** [Atlantiss/BugTracker#2808]
... "You can't use that here" message appears instead. Checked spots in sewers, fountain, and prison. None of them work. I am not sure but I think this bug exists since last fix.

**Comment by gacek1989** [comment]
I try to do "The lurker above" achiv in SSC and also got message "You can't use that here" . Please for fix :>

**Comment by Althin** [comment]
Still can't fishing in Dalaran. In SSC u must stand in special place to fish up boss.

**Comment by Dexobox** [comment]
+1 Confirm the fishing skill in Dalaran underbelly is bugged.

**Comment by Avalain** [comment]
Also confirming, Fishing was working till some fix and now no matter where you stand there is no possible way (that I could find) to fish in Dalaran forbidding us to finish some of the achievements.

**Comment by Tessa99999** [comment]
Confirmed. Still bugged. Can't fish in Dalaran.

**Comment by sunshineinabox** [comment]
I think the issue is related to maps and the water not being detected as water. Might have to do with dalaran floating in the air. I've also been looking for a fix that was used for TC b/c they experienced a similar issue. 

The only commit I could find that might be related is the following.

https://gitlab.com/trinitycore/trinitycore/commit/11f6eb91c0f1343ccfea11c6dc7e8d346bb04ce1

**Comment by Magohoy** [comment]
It used to work, I'm only missing a few coins for the achievement, no idea what made it bug out.

**Comment by Philippe777** [comment]
Not only Dalaran, but Ironforge and Undercity are also affected by this bug. Undercity being affected means we can't get the Sickly-looking fish to complete The Limnologist achievement, and Ironforge holds Old Ironjaw. =/

**Comment by Bildo** [comment]
fixed by Wolfenstein
