### ISSUE TITLE
[ENG][Transmog] Agi>Int sword transmogrification issue

### ISSUE THREAD

**Issue by Stupify** [Atlantiss/BugTracker#2819]
http://www.wowhead.com/item=63533/fang-of-twilight 
seems to be not moggable by any other sword with intellect stats
ex.: 
http://www.wowhead.com/item=37060/jeweled-coronation-sword
http://www.wowhead.com/item=30910/tempest-of-chaos
http://www.wowhead.com/item=40336/life-and-death
I always get the error message: 
"You can only transmogrify an item to take appearance of an item of the same type and slot"
As you can see both of the intellect swords are one handed: no main-hand or off-hand specification. So it should be moggable as of patch 4.3.
On the other hand when I've tried to transmogrify Jeweled Coronation Sword into Fang of Twilight I could do it without any error messages.
Fang of Twilight can be transmogrified into any other sword without the specific slot requirement
ex.
http://www.wowhead.com/item=35101/brutal-gladiators-slicer (no intellect/spirit/spell power stats)

**Comment by Murmaider** [comment]
Also items that have proc chance instead of passive stats like: http://www.wowhead.com/item=10847/dragons-call cannot be used in transmogrification.

**Comment by lanrutcon** [comment]
Most Int weapons are Main-Hand only weapons. WoWHead does not show that because that restriction got removed in MoP.
Prior to MoP, you couldn't transmog a "normal" one-handed weapon (for both slots - main and off) with a weapon that had Main/Off-Hand as a requirement.

So, this is not a bug.

Here is some the "real" Jeweled Coronation Sword: http://cata.openwow.com/item=37060

**Comment by Stupify** [comment]
I must have missed that
though we still have an issue:

"On the other hand when I've tried to transmogrify Jeweled Coronation Sword into Fang of Twilight I could do it without any error messages."

**Comment by lanrutcon** [comment]
That's is fine, because Fang of Twilight can go for any slot (Main or Off), so there is no restriction here. Since Jeweled Coronation Sword will only be used on the Main Slot and FoTwilight can be used in that slot too, there is no problem.

But what Murmaider said is a bug. At the moment, weapons with Chance on Hit bonus (only! - no +20STR, etc) can't be transmog, and this goes for both sides, you can't get the look and you can't change the look of the weapon.

**Comment by cosminush** [comment]
It's normal to can't transmog items without stats? Like http://www.wowhead.com/item=13361/skullforge-reaver what i can't use for transmog. :(

**Comment by Nc94** [comment]
no it's bugged at the momment, we should be ale to transmog items without stats (blizzard even made "cosmetic" items without any stats/proc only for transmog)

**Comment by cosminush** [comment]
"cosmetic" like http://www.wowhead.com/item=52486/jewelers-sapphire-monocle or http://www.wowhead.com/item=52489/rhinestone-sunglasses#created-by-spell ?

**Comment by Nc94** [comment]
Cosmetic item has "Cosmetic" in it's tooltip like http://www.wowhead.com/item=95475/crown-of-eternal-winter but few items like Monocle that you linked are prohibited from transmog by blizzard like legendary items and they're giving massage when you try to use them. Bugged items don't show that massage and you can click "apply" button but when you click it nothing happens old item has it appearance and transmog don't show up.
http://eu.battle.net/wow/en/forum/topic/3147737067 here's more info about restriction in bluepost
