### ISSUE TITLE
Cho'gal, last boss of BoT (Raid)

### ISSUE THREAD

**Issue by jangsna** [Atlantiss/BugTracker#2869]
The adds in phase 2 suppose to spawn only 4 but instead it spawns more than 4 which is 6-7 and they are keep coming really fast.

**Comment by Jenovas** [comment]
From the code I see 4 spawns every 30 seconds. Are you sure you saw 7?

**Comment by jangsna** [comment]
It's not every 30 seconds, at least 15-20 seconds spawn time and I'm sure it's more than 4

**Comment by xolon** [comment]
i think also that our guild sometimes get 5 adds in last phase

**Comment by Frainzil** [comment]
There is a bug; the amount of adds is something between 3-5. Sometimes 1 of the adds doesn't spawn    in its ''wave''. Now what will happen is that so for example on the first wave you get 3 adds (1bugged and didn't spawn). Now the next wave of adds, the 4 will spawn of that current ''wave'' + the one which bugged before, so that gets up to 5 adds which spawns together. 7 adds though seems a bit to much though? When did you last encounter this boss?
