### ISSUE TITLE
Cloak drop from Al'akir is not tradeable with rest of the raid

### ISSUE THREAD

**Issue by Vaxivop** [Atlantiss/BugTracker#3097]
So, we killed Al'akir and a cloak dropped. I was not able to give the loot to another player, even though he was in the raid and not released when Al'akir died. Seems to be a bug that happens when you die vs. Al'akir in phase 3 or something.

The cloak in question is  [Cloudburst Cloak of the Earthshaker]. My character's name is Myretis and the person whom I wish to give it to is Wux.

**Comment by mitim1** [comment]
https://github.com/Atlantiss/BugTracker

**Comment by Jenovas** [comment]
From the rules:
GMs/Admins do not change the race/class/sex of a character, they do not change a nickname nor make character transfers, do not move/exchange/give items/gold, do not complete quests for any players (it can be done only in cases with no other way) and do not give back items/honor/ap/rating/gold etc lost because of dc/player's fault/technical problems/actions by a third party.

So your friend wont get the item. We'll look into this bug. Thx for the report

**Comment by Vaxivop** [comment]
Alright, then.
