### ISSUE TITLE
[EN][Achievement][Childrens week] School of Hard Knocks

### ISSUE THREAD

**Issue by Cassedy** [Atlantiss/BugTracker#3127]
For the achievement a flag in the eye of storm must be captured while the kid is following. Did that yesterday but it did not count. Other ppl in bg confirmed this bug. The issue seems to be the same as with all other flagrelated achieves in eots.
http://www.wowhead.com/achievement=1786/school-of-hard-knocks
This achievement and thus the childrens week metaachievement dont work.

**Comment by Tessa99999** [comment]
Also confirmed. My boyfriend did it twice in EotS with me; I saw it, and he got no achievement.

**Comment by Wojowniczka** [comment]
i must thank You ppls for reporting this :) so i will not try to do this achievement till it is fixed :) hope SOON™ :)

**Comment by imeasytokill** [comment]
only Eots dont work?

**Comment by Cassedy** [comment]
@ imeasytokill
All other achieves work - it's only eots

**Comment by Navedonar** [comment]
bt rules

**Comment by Cassedy** [comment]
Uhm .. closed? Is the bug fixed?

**Comment by Navedonar** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Cassedy** [comment]
k - one contributor less then.

**Comment by Stephenjawn33** [comment]
So the bug is not going to get fixed? A simple bug that will cause some of us at least another 6 more months of waiting? Even if no proof has been given, people are confirming this we've got 5 confirms and I can get at least 4 more people ingame to confirm this! This achievement is vital for the Violet Proto-Drake! Every event is! And that is not a mount that we, achievement hunters, can easily look past! I politely ask you to try to look into the achievement, extend the event if you have to, but please, please find a way to solve this!

**Comment by LaveniaGithub** [comment]
Fixed with http://atlantiss.eu/changelog#rev4847 ?
