### ISSUE TITLE
[EN] [Spell] Dark Intent

### ISSUE THREAD

**Issue by Propolys** [Atlantiss/BugTracker#3148]
http://cata.openwow.com/spell=80398

Dark Intent does not proc as it should when applied to the pet (and possibly other similar casting NPCs too). Tested it as Affliction/Destruction warlock and nor the Imp neither the Felhunter popped the proc (i was doing DoT crits myself).

**Comment by Varchord** [comment]
Um. Because DI procs from periodic damage? Which warlock pet has periodic damage? 
Felhunter deals direct damage
AFAIK imp only casts fireballs which also are direct damage

**Comment by Avalain** [comment]
Checked this one myself. Burning Embers in Destruction (http://www.wowhead.com/spell=108647/burning-embers) are considered as player damage.

Only gain you should receive pitting Dark Intent on minion is flat haste buff 3% for both of you.

You might want read a little about skill here:
1) http://wowmb.net/forums/f9/40783-does_dark_intent_your_minion_actually_work/p2/
2) http://wowmb.net/forums/f9/41008-dark_intent_guide/

**Comment by Propolys** [comment]
Dark Intent should also proc from your critical Dot hits too. And it doesn't. You sadly focused on the pet side while the player side is actually bugged.

**Comment by Varchord** [comment]
It does, buff some player with it, put him on focus and do some damage. You'll see that this player is getting stacks from your crits

**Comment by Propolys** [comment]
Yeah, that's how it works when put on a player. But it doesn't proc from your own dot crits when put on a pet.

**Comment by Varchord** [comment]
Even if it doesn't it's not really important. Pet's don\t have DoTs so they don't benefit from this buff. Plain and simple

**Comment by Avalain** [comment]
Only Cataclysm skill description I could find: http://cata.openwow.com/spell=80398

"You link yourself with the targeted friendly target, increasing both of your haste by 3%.
When you or the linked target gains a critical periodic damage or healing effect, the other gains increased periodic damage and healing lasting for 7 sec. You gain 3%, while the target gains 3%. Stacks up to 3 times. Dark Intent lasts for 30 min."

Please notice "periodic damage" part.
Like Varchord typed: It would not benefit your minion in any way since only damage they deal is direct.

**Comment by Propolys** [comment]
You're perfectly right: "When YOU or the linked target gains a critical periodic damage". It should also pop from your dots but it doesn't.

**Comment by Avalain** [comment]
Please explain where do you see a problem then.

1) You put DI on a player:
You both receive flat 3% haste buff.
- you have critical periodic damage - other player receive increased periodic damage.
- other player gains critical periodic damage - you receive increased periodic damage.

2) You put DI on minion:
You and your minion receive flat 3% haste buff.
- you have critical periodic damage - minion receive increased periodic damage, which change nothing due to reason no minion posses abilities that put periodic damage - change in pet's dps is null.
- minion deals direct damage only so no critical periodic damage therefore no increased periodic damage for you. Change in your dps is null.

**Comment by Varchord** [comment]
I think I've figured out what his problem is.
He thinks that when HE crits with DoTs, these crits should grant HIM stacking buff. Which is incorrect. You only get stacking buffs from crits of other players with DI

**Comment by Avalain** [comment]
In that case you should remember that Blizzard's tooltip is often vague.

I played warlock on retail long time and it never gave me stacking buff from my own critical periodic damage.

The point of this DI buff is same as Focus Magic from mage - you're dependent of other player performance.

**Comment by Varchord** [comment]
> the other gains increased periodic damage and healing lasting

I think it's perfectly clear
