### ISSUE TITLE
[EN][Druid] Feral Charge positioning

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#3161]
When you feral charge, it positions you with the back at your target.

How it should be:
everytime you leap it should position yourself with the face towards your target
https://www.youtube.com/watch?v=MBVndy3dSFo
at 2:40
at 3:20
you can see

**Comment by Isuel** [comment]
confirmed.

**Comment by ahtebe** [comment]
It doesn't even leap behind anymore whether the mob is against a wall or not. Tested on training dummy with no wall behind and on Cutpurse (http://www.wowhead.com/npc=94/cutpurse) in Elwynn Forest.

**Comment by Isuel** [comment]
maybe the magmaw fix screwed it :D

**Comment by Jenovas** [comment]
Before my "Magmaw Fix" Feral Charge in Cat form didnt calculate nor check if path is available it just made you move behind the target without checking anything. After my fix Feral Charge in Cat form now uses pathfinding to check if you can jump behind the target, so falling into textures or into a hole or something doesnt happen as often now.

**Comment by sunshineinabox** [comment]
Sometimes when feral charging you get oriented correctly, but the leap puts you too far so that you need to move back to actually attack the back. You basically end up in the middle of the mobs. Other times, as I have noticed with warrior charge, you get put WAY outside the hit box. This is more noticeable the larger the mob is. Sometimes when you charge you end up going backwards in situations like raids or other larger bosses. As for the warrior charge it tends to put you out of melee range so you need to move usually forward or back to be able to do anything. This is true for both cat and bear form.
