### ISSUE TITLE
[EN][Warrior] Sweeping Strikes

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#3208]
1. You shouldn't be able to cleave attack while you are disarmed/not have a weapon equiped.
2. If your main target is under 20% HP and the target near it is at 100% HP, when you activate Sweeping Strikes you shouldn't damage the target that's at 100% HP if you attack your main target with Execute . The Cleave with Execute should work only on targets under 20% HP .
3. When you activate Sweeping Strikes , the opportunity strike(warriors arms mastery) should have an ICD of proccing.

proof:

http://www.wowwiki.com/Sweeping_Strikes
 Requires Melee Weapon Equipped."

http://www.wowwiki.com/Sweeping_Strikes 
"Sweeping Strikes will not cause [Execute] to strike a nearby opponent unless the nearby opponent has less than 20% health (does not consume a charge of Sweeping Strikes either)".

http://wow.joystiq.com/2010/11/12/the-care-and-feeding-of-warriors-how-will-mastery-affect-warrio/2 "Even with an internal cooldown in Strikes so it can't proc off of the extra swing it creates" .

**Comment by Jenovas** [comment]
From topics I found about Opportunity Strike say that it can proc with Sweeping Strikes, also on MMO Champions there is a player that showed it happen BUT it turns out OS should have a 0.1 ICD to not have chain reactions that never stop.

**Comment by Bobertgaming** [comment]
idk where they changed "Sweeping Strikes will not cause [Execute] to strike a nearby opponent unless the nearby opponent has less than 20% health (does not consume a charge of Sweeping Strikes either)", but at least in 6.2 retail sweeping strikes transfers execute despite any requirement for the other targets health. im going to say wowwiki is wrong, because it even has tooltips for the updated spells like slam on that website, and that means they are saying this explanation for sweeping strikes, what you linked, would be right. and its simply not. cause i just got done playing a warrior on retail. ill post a log of dps for a fight in the next comment.

**Comment by Bobertgaming** [comment]
https://youtu.be/d6QXKM7ZSQo?t=2m21s

starting the video at 2:21 slow the video down to .25 and you can clearly see that execute is cleaving off the main target onto the second target that has well above 70% hp.
