### ISSUE TITLE
[en][core mechanics] Global Cooldown

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#3213]
Sometimes the global cooldown gets doubled, i dont know how to replicate the bug but i often found that when i have high haste with gcd close to 1sec ( as caster ) and spamming spells i could do 1-2 ice lance when opposed to possible 3 and even four.
i think it might have something to do with the haste mechanics, on non hasted casts i never had that problem
http://www.wowhead.com/spell=61304/global-cooldown

**Comment by Tj20** [comment]
Are you sure that it's really a GCD issue and not just lag spikes?

Keep in mind that our server has no spell queue (#1087) - in fact I think no PServer has figured out how to emulate that feature yet which was implemented by Blizzard in patch 4.0. 

This means that your 1 sec casts will have a cast time of 1.5 seconds with 500 ping. (Well, nobody plays with constant 500 ping on our server, but when for whatever reason some packet are delayed you will instantly feel that in your spell casts).

Take for example me spamming Hunter's Mark, a spammable 1 sec CD:

![pic](http://i.imgur.com/BgyET2N.jpg)

Sometimes the next spell cast success really is 1.0 seconds later, but sometimes it takes up to 1.4 or 1.5 seconds due to lag probably.

I think a /combatlog would also be helpful in your case.

**Comment by mitim1** [comment]
dubel #866
