### ISSUE TITLE
[en][engineering] Electrostatic Condenser

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#3230]
Electrostatic Condenser every time you mine,colecting herbs,skin should increase the chance of dropping volatile air.
is not wokring.

**Comment by smmuntz** [comment]
Here is the wowhead link:

http://www.wowhead.com/item=67494/electrostatic-condenser

But with that, I don't believe what you are saying is true, so likely this should be closed. 

It just seems there is a flat chance of it happening (seems to be anywhere between 2.5% and 6%, though some claim up to 25% but that seems unlikely, and I am not exactly sure what the actual chance is) and there is nothing that I can find that suggests that every time you collect from a node that chance should increase.

The wording of the Electrostatic Condenser just says "Allows a skilled engineer to occasionally collect Volatile Air while mining, skinning, or collecting herbs." which also does not suggest that what you are saying to be true.

**Comment by Thefakemccoy** [comment]
It is not working properly.

141 elemental ore
149 Pyrite ore
2 Airs
11 earth 
10 fire 


seams way to low

**Comment by xmesaj2** [comment]
bump

**Comment by fluessig** [comment]
comments on wowhead say that skinner engineers never find volatile air off skinning but instead always find it as extra loot in the strange bloated stomachs (so no vol air from regular skinning, but 100% vol air erxtra drop in the stomach)
i think its pretty save to assume a 5% proc chance on the condenser since thats about the drop chance of the stomachs
wowwiki says rich mining nodes and pyrite have a higher proc chance for volatile air, so maybe 10% for rich nodes and pyrite?

**Comment by Piklo** [comment]
#9013 reported with issue_template
