### ISSUE TITLE
[EN][Core Mechanic]Vote Kicking not working in RDF groups

### ISSUE THREAD

**Issue by sunshineinabox** [Atlantiss/BugTracker#3256]
Vote kicking is not working in RDF groups. There is a strange bug where even if everyone votes yes it says vote kick has failed. Tried almost everything like passing lead and trying to kick someone. It happened after the recent update.

**Comment by Kejmil** [comment]
s**t happens when people don't test things on PTR when devs are asking for it

**Comment by Thefakemccoy** [comment]
i cant even get on the ptr its down for me but im also new only been here a week. So i wanted to work on a main on the live server first.

**Comment by Axahus** [comment]
I can sometimes test some things but I can't see any info on website about that need... (I don't read forum because my eng is bad and there's no info about PTR in polish language in "localized forum").

**Comment by MosOpinca** [comment]
"s**t happens when people don't test things on PTR when devs are asking for it" is an offensive response tbh. People posting here are , in good faith, trying to point to some problems, and in doing so giving the developers some aid in finding the problems . Receving such an answer ( even  thou the massage it conveys it's true) is wrong .. It's far from polite to get a "shit happens" or "u're fault because u didn't test it" form someone who is involved in the bug repairing team.  I think a "Thank you, we will look for it." would have been the correct answer , or , if Kejmil didn't had anything relevant comment regarding this matter should have absteind from such a comment.  

Getting over the lesson in manners , the bug still persists and after the combat bug i think it's one of the most annoying ever. Because if the server fail while you are in a party , and some of the members don't come back u're screwed for atleast 30 mins ( most of the time u'll get deserted debuff for leaving the party), not to mention the time wasted clearing parts of the dungeon prior to server crash . Also, not been able to kick players with key roles (tank, healer) that decide to leave the instance (most cases at start because ...i dont know ...they are @#$%heads that queued for RDF but like only a couple of fast instances) cripples the party and forces anyone in that party to get a deserted debuff since the only option is to split the group (u cant requeue since the party is full).

**Comment by Jenovas** [comment]
MosOpinca  - Kejmil is not in the team and has nothing to do with the "repairing team" so please stop. Thank you for reporting the bug. And no thank you for writing these lies.

**Comment by Aival94** [comment]
this one is also reported here #696

**Comment by sunshineinabox** [comment]
This problem should probably be fixed soon. When you want to rdf at level 80 or higher its almost impossible to do rdf b/c you either get BRC or ToT. Now that would be ok, but the bug with saved instance IDs forces you to leave groups and get deserter. Those two problems in combination make it almost impossible to do rdfs. You are better off just doing specifics and choosing BRC.

**Comment by Aival94** [comment]
Close this one...now vote to kick is working i think.
