### ISSUE TITLE
Deathstrike

### ISSUE THREAD

**Issue by vampatdawn** [Atlantiss/BugTracker#3284]
Deathstrike only ever gives 7% of max health - not more when you take tons of damage.

It is supposed to give 20% of preseding damage in the last 5 seconds - it doesnt. I have checked with bloodshield tracker.

**Comment by aneq** [comment]
I'm pretty sure it works correctly. Go to blackwing descent, fight chimaeron. Death strike right after a massacre - you'll be healing yourself much more than 7% of your max hp. The addon you checked this with might be broken, not the spell in question.
Also next time you submit a bug make sure to follow the bugtracker rules. (you should link the supposedly bugged spell in the submission)

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md
Read rules before posting. Title is wrong, description is wrong, no links


Besides. It is working properly.

Average tank has around 160k hp. 
160k * 0,07 = 11200
11200 * (100/20) = 56000

What it means that you have to take more then 56k damage in 5 seconds for your heal to be calculated from damage taken rather than your health pool. And it's happening. You can see this on heroic content. Heroic Cho'gall, Magmaw, Chimareon.

You've wrote that you've checked this. How? No screens, no videos, no description.

**Comment by Kejmil** [comment]
i actually think that the periodic or channeled dmg is not taken into formula of death strike healing (mostly noticable on magmaw hc omnomnom) but have to double check it before making proper issue

**Comment by Varchord** [comment]
Actually, Mangle DOES increase your healing. but it's irrelevant since it's bugged and most often then not you can't hit magmaw during mangle
