### ISSUE TITLE
[EN][Auction House] Item loss

### ISSUE THREAD

**Issue by Thefakemccoy** [Atlantiss/BugTracker#3339]
So last night before bed i put some Volatile Fire and waters up. When i log back in the next after noon i check my mail. I did not receive and gold for any of them nor did i get them back for not selling.

They are no longer listed on the ah.

The have vanished into thin air.

**Comment by Ypsilenna** [comment]
Lastly I put many things in Auction houses and some of them didn't come back after they have expired. I lost many items such as: several black pearls, enchanting rods, tiny emerald whelpling pet, archeology items, mats, glyphs and so.
I realised that I keep losing things after server restarts. The problem is keep getting bigger and bigger every week. It's getting really annoying.
