### ISSUE TITLE
[EN] [Support Spells] [Paladin] Can't cast party required spells in arena.

### ISSUE THREAD

**Issue by zixsen** [Atlantiss/BugTracker#3366]
Support spells that require party does not work in arena at all. It's like we're not even in party when playing. Can't cast Hand of Protection, Beacon of Light or Hand of Sacrifice it was not like this yesterday.

**Comment by Ponyrider2** [comment]
It have connetion with new buffs on arena "alliance" and "horde", if you are from different faction that you have buff (it happens when both teams are from same faction - one get alliance buff and 2nd team get horde buff) so basicly, if u are alliance player and get "horde" buff/flag u cant use team spells on your partner like intervene, beacon and so on also u cant use insygnia (medalion).

**Comment by Kejmil** [comment]
rev. 4453 should be fixed
