### ISSUE TITLE
[EN][Core] You do not recieve rewards for dungeons you complete in RHC after server crash

### ISSUE THREAD

**Issue by sunshineinabox** [Atlantiss/BugTracker#3380]
As stated you do not receive VP (or satchle) if you complete the dungeon after a crash. This makes it so that you do not receive proper reward. People just leave after crashes leaving you saved for the dungeons, but unable to get valor.

**Comment by Dean1989** [comment]
is the same with low level df, if you finish it after a crash you don't get the exp and the bag reward

**Comment by Aival94** [comment]
and if you finish it valor counter in rhc decrease by one like you get valor points.

**Comment by Frainzil** [comment]
Its pretty hard to fix such a thing if you know the server crashed. since the server crashed they can't see if you did the dungeon queuing the RHC or if you entered manually. i Don't think they can detect any difference after a restart of servers. if you are doing it for the valor, its not such big of a deal, you lost some time yes, but queuing for a new one will just solve the problem. Annoying yes, that's for sure.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/696
