### ISSUE TITLE
[PL][Warlock][Spell] Summon Doomguard

### ISSUE THREAD

**Issue by Wulgarny** [Atlantiss/BugTracker#3389]
http://www.wowhead.com/spell=18540/summon-doomguard

Doomguard niestety nadal ma problemy z targetowaniem. Powinien atakować target z Bane of Doom/Bane of Agony od warlocka. Niestety przy większej ilości POTENCJALNYCH targetów zaczyna wariować. Mianowicie 3 przeciwników, jeden ma na sobie Bane of Agony a Doomguard kompletnie go olewa atakując jeden z pozostałych targetów (których warlock nie uderzył żadnym spellem). 

Poza tym, Doomguard podchodzi pod melee range (nie atakuje już melee swingami) aczkolwiek gania za swoim targetem co oczywiście przenosi się na jego totalny dmg.

**Comment by Wolffenstein** [comment]
Dziwne, mi przy 3 targetach zawsze atakował tego z Bane of Doom/Agony. Testowałeś sam czy jeszcze z jakimś innym warlockiem rzucającym Bane'y?

>Poza tym, Doomguard podchodzi pod melee range (nie atakuje już melee swingami) aczkolwiek gania za swoim targetem co oczywiście przenosi się na jego totalny dmg. 

Taa, to przeoczyłem :D

**Comment by Wulgarny** [comment]
Testowałem sam, najpierw na kukłach - po czym pomyślałem, że na kukiełkach nic nie sprawdze. To zgarnąłem Resto Shamana, na początku duela wyrzucił Earth i Fire elementale - po czym zarzuciłem Bane of Agony na Shamana i wypuściłem Doomguarda. Cóż, Doomguard skakał po targetach ale shamana nie tknął :P

**Comment by Wulgarny** [comment]
Dobra, 
Doomguard ładnie zmienia targety. 
Aaaczkolwiek, na pełnych odpałkach (volcanic potion, trink z valiony, DMC Volcano proc) robi średnio 200-250k damage przez cały czas jego walki :/

**Comment by Badrng** [comment]
Doomguard zdaje się critować za 150%, nie powinien za 200%? Przynajmniej w simcrafcie tak to wygląda. No i faktycznie coś słabo bije nawet jak się go odpali na procach, może jest coś nie tak z coeffami na doom bolta?

**Comment by Kejmil** [comment]
patrzac na shadow apparitiony spreja moze byc tak ze ma critowac za 150%, znajdz jakis filmik na ktorym dokladnie widac co i jak zeby poprzec swoj argument
no i overall dmg nie wyglada na prawidlowy

**Comment by Glare** [comment]
Mam wrażenie, że nie korzysta z mastery Demo. Doomguard Destro vs Doomguard Demo to różnica około 50k dmg, która wynika jedynie z tego, że ten od Demo dłużej żyje(talent).

**Comment by Kejmil** [comment]
https://youtu.be/f__LGzHItyU?list=PLD47BDAA8A49C5F1E&t=133 powinien critowac za 200% jbc

**Comment by fafal** [comment]
![wowscrnshot_041011_001436](https://cloud.githubusercontent.com/assets/7698889/8684025/6c2e1f1e-2a76-11e5-88dd-70755502ebd7.jpg)
Jest to przyklad z 4.0.6 // 4.1 na to ze ma na 200% na cricie. (Swojam droga dmg locka bez potionow i nie bisowym gearze)
MAstery z Demonology dla DG skaluje sie zle albo wcale.
DMG ogolem jest smiesznie maly, porownujac do sima/fotek/yt. Przyklady dam niebawem.

**Comment by Glare** [comment]
Fafal lepiej daj screeny dmgu Infernala z wczorajszego BH ;]

**Comment by fafal** [comment]
Zrobio DG to zglosze Infernala, bo robi tyle co DG powinien czyli robi za duzo ;x

**Comment by fafal** [comment]
bum, nadal doomguard nic nie robi ;c

**Comment by fafal** [comment]
Actually:
Doombolts crits only for 150% normal damage instead of 200%
Doombolts bolts do not scale with owner haste (only from stats and gear, no buffs!) (demo 20-21 bolts rip) but dont take benefit from Bloodlust, not sure about buff on sinestra).
Doomguards dont scale with owner Critz and debuffs on target (not sure for 100%)
Doomguards scale dynamic from owners SP and Mastery instead of take SP/M from master when summoned. DG scale dynamic on MOP like also take benefit from BL, not on Cata.

Also some tests from today on ATS:
Demonology, 11.38% Haste 13784 SP. All procs, CoE on target, 76% Mastery
Hits 12192 to 18764     Crit 18808 to 26505     Bolts 19
Demonology, 7% Haste, 4304 SP, No Proc/No Debuffs, 44% Mastery,
Hits 6516 to 6602    Crit 9873    Bolts: 19
Demonology, 0% Haste 176 SP, No Proc/No Debuffs, 18% Mastery,
Hits 1192 to 1294 (i dont see crits ;c) Bolts: 19
Afliction, 5.87% Haste, 3689 SP, No Proc/No Debuffs, Worgen
Hits 5518 to 5602    Crit 8634    Bolts:13

And retail logs: (From EJ Warlock Forum Thread Tests, i can link this)
Demo 168 SP 0 Mastery
Min 2092 Avg 2172 Max 2261
Min 4323 Avg 4371 Max 4419

Afflic 168 SP 0 Mastery
Min 1401 Avg 1472 Max 1508
Min 2947 Avg 2968 Max 2989

Demo 505 SP 0 Mastery
Min 2252 Avg 2322 Max 2413

Afflic 505 SP 0 Mastery
Min 1666 Avg 1702 Max 1754
Min 3528 Avg 3528 Max 3528

Demo 168 SP  321 mastery
Min 2256 Avg 2359 Max 2435
Min 4585 Avg 4700 Max 4820

Demo 15123 SP 1680 Mastery
Min 29064 Avg 29176 Max 29307
Min 58107 Avg 58225 Max 58342

Afflic 10985 SP
Min 9153 Avg 9213 Max 9252
Min 18318 Avg 18363 Max 18422

I hope this helping with something.

**Comment by Bildo** [comment]
Spell coeff - fixed
Crit - fixed

**Comment by fafal** [comment]
After morning tests on new rev:
Spell coef looks good, crit also.
So DG need fix for:
1. Doomguards scale dynamic from owners SP and Mastery instead of take SP/M from owner once for bolts when summoned to end of his duration.
2. Doomguards dont scale with Mastery (only demonology) !!!!!!!!
3. Doomguards dont scale with owner Critz and debuffs on target
Nr -without this DG doing ~250-350k dmg... without nr 2 DG for demonology still is useless. Nr 3 is just loose of dps but not that big like nr1 and nr2. Also to check:
1. Doombolts bolts do not scale with owner haste (only from stats and gear, no buffs!) (demo 20-21 bolts rip) but dont take benefit from Bloodlust, not sure about buff on sinestra).

**Comment by Glare** [comment]
Co każdy cast bolta przybliża się kilka kroków do bossa aż będzie w meele range co wygląda komicznie i zmniejsza ilość wycastowanych boltów.

Btw przeszliśmy z PL na EN?

**Comment by anxanas** [comment]
Both sinestra buff and BL/TW works on doomguard, tested today

**Comment by fafal** [comment]
"Only" :(

**Comment by anxanas** [comment]
Also another bug i have noticed with doomguard(and any other pet/guardian that casts): it casts a spell and then moves a little closer to its target which lowers the amount of casts its can do happens with fiery imps too. Also if you move away from where the fiery imps spawn they follow you a bit and keep casting again.

**Comment by Wolffenstein** [comment]
Mastery snapshot should be fixed in rev 4820.

**Comment by anxanas** [comment]
Ty for fix nice 65% damage increase to doomguard with moonwell chalice =)))

**Comment by fafal** [comment]
Mastery snapshot looks nice.
Still need snapshoot for Spell Power :)

**Comment by anxanas** [comment]
Spell power is the most important, but it also needs to benefit from haste rating crit % and hand of guldan increased crit chance. =)) But the fix is very nice indeed my doomguard can do 600k now

**Comment by fafal** [comment]
Need Avo, dying from random spells

**Comment by anxanas** [comment]
It has avoidence(90%) like any other pet, the problem is just that if it gets stuck in an engulfing flame on ragnaros it cant move out and even with 90% damage reduction it will probably die unless someone heals it, this is very blizzlike i believe. Only fiery imp and ebon imps were completely immune to aoe spells

**Comment by Kejmil** [comment]
from what i recall one dev said that in most cases if pet dies to aoe spell, it is problem of spell not being "flagged" for aoe, not avoidance itself

**Comment by Wolffenstein** [comment]
Doomguard has avoidance aura.

**Comment by fafal** [comment]
Engulfing flames on ragnaros, flames on the quest forlon spire itc kills him almost instantly so idk

**Comment by anxanas** [comment]
as i said before engulfing flame does pretty high damge and last for a long period so if a doomguard with 80k hp stands in it(Even with 90% damage reduction) he will die unless healed, this is very blizzlike, same thing happens with hunters pet if engulfing flames are in the middle, i have to waste gcd all the time to heal my poor little wolf, in p2 and p3. #Healerslearntohealpetsandguardiansitincreasesyourhps

**Comment by fafal** [comment]
ok, checked, you're right, my bad

we can back to other stats Scalling topic again ^^

**Comment by anxanas** [comment]
Bump, shouldnt it be easy for you to make it snapshot int, since you already made it snapshot mastery?

**Comment by Kejmil** [comment]
having unholy gargoyle and frost/blood ghoul in mind i guess not

**Comment by kadi2** [comment]
http://www.worldoflogs.com/reports/eqal3tkanmy347k3/details/258/
90k crit doombolt :D

**Comment by Jenovas** [comment]
SP snapshot added in  rev 5226
