### ISSUE TITLE
Ignite

### ISSUE THREAD

**Issue by mekase** [Atlantiss/BugTracker#3390]
Ignite munching isnt working as it should be, sometimes it randomly ignores some of crits instead of following 0.2. And Ignite munching isnt the healthy way to nerf Fire mages if you ask me, nerfing base damages would be an healthier choice instead. Not that I believe they were overpowered. There are specs that pull as much as Fire.

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Caturix** [comment]
I must agree, Ignite became so random after recent changes. It is really annoying to play mage atm.

**Comment by Jenovas** [comment]
It doesnt ignore crits, ignite now can have 3 ticks instead of 2 and with 3 ticks the DMG gets divided by 3 so that probably where you think DMG gets ignored.

Also ingnite munching got added and will be here if you like it or not. We are blizzlike we do not do our own bufffing / nerfing, we always try to do it the blizzlike way.

**Comment by Caturix** [comment]
"we are blizzlike" yeah, good thing blizzlike had delay on ignite like we do.
