### ISSUE TITLE
Templar`s Verdict and Shield of the Righteous bug 

### ISSUE THREAD

**Issue by Newasenior** [Atlantiss/BugTracker#3546]
Templar`s Verdict and Shield of the Righteous shouldn`t consume 1 charge of Holy Power if the abilities end up in a miss/dodge/parry !!! ( can`t find anything related to this to say otherwise on official patch notes)
EX: Got 3 HP and i use Templar`s Verdict and it misses /dodged /parry  i lose 1 charge of HP for every miss/dodge and parry).
Only the abilities that generate Holy Power should not give any HP if they end up in a miss/dodge/parry !!!
EX: from http://wowwiki.wikia.com/Patch_4.0.6

Paladin Bug Fixes 
 The Silence debuff from Avenger's Shield was using the Dazed visual effect, and its Daze debuff did not have a visible effect. This has been remedied. 
 The damage bonus from Communion is no longer applied even when the paladin has no paladin auras active. 
 Crusader Strike, Holy Shock, and Hammer of the Righteous no longer incorrectly grant Holy Power from a missed attack. 
 Divine Storm no longer incorrectly highlights when Hand of Light procs. 
 Exorcism no longer re-targets whomever it does damage to when it finishes casting. 
 The healing amount in the buff tooltip for Holy Radiance is now accurate. 
 Pursuit of Justice is now providing Holy Power when the paladin gets stunned by the Fire mage talent Impact. Conversely, Pursuit of Justice is no longer granting Holy Power when the Paladin is hit by Holy Wrath. 
 Repentance tooltip now states that it does not break Censure damage. 
 Rank 1 of Shield of the Templar was reducing the cooldown of Guardian of Ancient Kings by 45 seconds, which is inconsistent with the scaling of ranks 2 and 3. This has been adjusted. 
 The tooltip for Tower of Radiance indicated that Holy Light would generate a charge of Holy Power. This has been fixed. 
 Word of Glory no longer resets the swing timer.

**Comment by Dean1989** [comment]
update the title
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Frainzil** [comment]
I never noticed this. Probably cause those attacks usually never miss/dodged. Will take a look at it if it would get parried, but normally templars verdict/crusader strike should never get parried in the first place. According to what i know so far, both are spells and not really melee swings. If the spells would get parried in the first place its actually saying he parried a spell, which is kinda weird. If you think the spell is a melee swing all melee dps will get a pretty nice nerf with spells getting parried all the way, especially paladins since both crusader strike, divine storm and templars verdict are 'melee swings'. (isn't really an answer to what Newasenior said but its still something i want to make clear)

**Comment by Jenovas** [comment]
Crusader Strike can normally be parried / dodged / missed and should be.
The same goes with every other melee based special attack. 
Thats why when your a melee class fighting against a tank you barely DMG him.

**Comment by Jenovas** [comment]
Fixed in rev 4474
