### ISSUE TITLE
[EN][Talent][Priest] Discipline Mastery

### ISSUE THREAD

**Issue by Terrificlol** [Atlantiss/BugTracker#3650]
Priest Discipline Master (Shield Discipline) seems not to work:

1. Im a mastery stacking priest and no matter how much more mastery i have, the percentage is still deafult (20% increased potency)
2. Despite having more mastery, the potency of absorbs doesnt seem to change, which is a terrible issue for Discipline Priests (if so its slight - not significant)

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Jenovas** [comment]
Mastery works as it should. It is only a graphic bug that the 20% doesnt increase.
Just checked both PW:S and Divine Aegis and both get increased by mastery and Divine Aegis Absorb Cap also gets increased.
Closing.

**Comment by Suricat-chicken** [comment]
Well If I can make a comment here so I dont wanna open another bug to mess. Mastery is working, but not the math way it should > instead of having 46% shields /exactly 18,4 mastery * 2.5%) Iam gettin only 43,8% from the Divine Aegis... it is a 1k sometimes up to almost 1.5k shield loss. Could it be fixed? :)
