### ISSUE TITLE
[EN] Justice points

### ISSUE THREAD

**Issue by Dean1989** [Atlantiss/BugTracker#3663]
i was with around 2350 jp, after i buyed the http://www.wowhead.com/item=58133/mask-of-vines
for 2200 jp, my jp went to 0. this happened now after the 50% bonus introduction. can you check if something is bugged? ty

**Comment by BAndysc** [comment]
Hello, thank you for fast report! Yes, the bug was caused by bonus exp, honor and justice, I haven't noticed 50% bonus was not only added when you gain justice points but also when you... spend them! It has been already fixed. I hope you wouldn't be sad if I said you didn't recover those 150 jp...? Finding out what was your exact currency before is quite tedious task compared to the amount. Is that ok?

**Comment by Dean1989** [comment]
ofc no problem Bandy, ty and the rest of the staff for the amazing work you do evreyday!
