### ISSUE TITLE
Close this

### ISSUE THREAD

**Issue by Helbringer** [Atlantiss/BugTracker#3673]

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by Helbringer** [comment]
It took me ages to write that report and none of that was reported before. If you have a problem with how i did it, then just tell me what it is.

**Comment by Varchord** [comment]
This took you ages to write? 

wowhead links to bosses, quests, NPCs which are relevant and mentioned in report

If you've read readme you would know what is wrong -.-

**Comment by Helbringer** [comment]
It took ages to write becasue i had to look up all the boss names which no longer exist in WOD and that also means wowhead is incorrect, cant believe you would rather bugs werent reported, no wonder not many people report. I was going to add the paticular npcs which have no pathfinding, theres like 10 of them and i wouldnt know without going there myself and i havent had time. Have no bugs reported if thats what you prefer.

**Comment by Varchord** [comment]
http://cata.openwow.com/

Still. I don't see how it took you 'ages'

**Comment by sunshineinabox** [comment]
I agree the way you act is very off putting. Let the staff take care of what they need to. You spamming the link over and over does nothing. Not only that its irrelevant. If you are so concerned ask for moderation privileges and edit the titles yourself. You add absolutely nothing to the reports when you just attach the readme link. If you want to improve the way bug reports are done I would suggest perhaps make a page on the website that the bugtracker link takes you to that includes the readme or a link to it and then the link to the bugtracker itself. It doesn't matter if it took him ages or not, he took time out to report the bug, which is a good thing. The bugtracker is very hostile and maybe that makes people not want to post and in the end the loss is to everyone who plays on the server.

**Comment by Varchord** [comment]
Seeing report number 1256 on the same damn thing can make you hostile. Because why use search?
Seeing report number 1120 with no wowhead links can make you hostile.
Seeing report number 657 with no arguments, proofs, links can make you hostile
Seeing reports with wrong title, or people using BT as ticket system can make you hostile.

It creates a mess. There are rules. Rules which are written in README file. If it took you so damn long to write this then there shouldn't be any problem to take 5 more minutes and read it. You need to stop justifying yours and others laziness to read instruction which is even shorter than this report.


I TOLD HIM what is missing, I've provided him with wowhead alternative which has everything that is on cata and below and he still hasn't updated his report. You gonna tell me what? That he is just sitting in the corner crying and offended because I've told him he didn't read README?

**Comment by sunshineinabox** [comment]
I understand what you are saying and I even agree with it, but there are better ways to go about it. You shouldn't be rude to people that are just trying to help. He may not have followed the guidelines, but ultimately he was trying to help the server. I just wanted to clarify I don't care what you say, but it isn't your job and its very rude. I'm also not lazy and bug reports that I submit I make sure adhere to the guidelines. Honestly you can do what you want this isn't the place to argue and if someone sees fit they can delete the messages and if they would like me to I will delete them on my own.

**Comment by Varchord** [comment]
So what do you want me to do? Explain every single poster what they did wrong? Linking README is faster and they can figure it out on their own, without holding hands.

And posting link to README is not rude. It's.. neutral, informative. It's better than report closed without any comment from the dev closing it. You will say I was rude in my second comment. You know why? Because he didn't even bother to open the link and read. He wanted everything on a silver plate cause his report was so long and complicated -.-. 
In the early days there were a lot of reports which were done wrong. Non-poland community wasn't even here yet. I was. And even though I don't have any authorization to close/label etc I've been trying to keep BT clean.

>but ultimately he was trying to help the server. 

[The road to hell is paved with good intentions](https://en.wikipedia.org/wiki/The_road_to_hell_is_paved_with_good_intentions)

**Comment by Helbringer** [comment]
Erm wow.

**Comment by Helbringer** [comment]
I will just stop reporting bugs now. Thankyou sunshineinabox for your understanding.

**Comment by Kejmil** [comment]
and now you can only blame your childlish behaviour for not working properly scholomance

**Comment by Helbringer** [comment]
Dont be rude.

**Comment by Varchord** [comment]
Hah. Kejmil You're the men

**Comment by Jenovas** [comment]
Oh my god... Like rly? 
You made a bad report if it were me I would just close it not saying anything.
Is that me being rude? Nope. It's you not reading and not following the rules.
And after someone corrected you, you decided to erase the issue (how dare he correct me, how dare he say I did something wrong! I spent so much time making the report! Now I'm gonna remove it to show everyone who's boss!).

"however you decided to be rude and ungrateful." - are you 10 years old? I've spent the last 3-4 years working for this servers sometime 10 hours daily (before I had my job). Do you know how much times people were rude and ungrateful? If everyone acted like you just did this server would have died a week after it started...

**Comment by Varchord** [comment]
Jenova is there something like change history where you could see his report before he deleted it? I could repost it after verifying

**Comment by Helbringer** [comment]
chill man, wtf, again with the child refferences? Im sorry for removing it, but u guys said it was useless anyway, it just doesnt take much to be alittle polite, you dont have to gang up on me.

**Comment by Helbringer** [comment]
Jenova i respect you for all your hardwork and i thankyou for that dedication, its just not nice to gang up on me and call me names for what i have done which is try to help the server and over react about vanchards rudeness, i love this server and i dont want to be treated this way. Please dont continue arguing with me for nothing.
