### ISSUE TITLE
[EN] [Warrior] Execute uses only 10 additional rage instead of 20

### ISSUE THREAD

**Issue by Nukeey** [Atlantiss/BugTracker#3782]
**What should happen**
According to the tool tip Execute should use up to 20 additional rage and do damage accordingly.
This would result in a total of 30 rage.

**What is happening**
Using Execute at full rage only costs 20 rage, and also only does damage with those 10 additional rage.

**Comment by deflexure** [comment]
Formula for execute should be as follows: http://puu.sh/iUqNx/f49b2fc2d3.png atm when you have 10-20 rage it only uses 20 rage and gives base damage. At 20-100 it costs 20 rage and gives base damage + extra damage as if it costs 20 rage, so it works almost correctly. 

What it should do is take however much rage you have between 10-29 and put it in that formula to find amount of damage it needs to deal as well as take appropriate amount of rage (at 23 rage it should cost 23 rage etc, atm it would cost 20) and for 30+ it should do max damage and cost full 30 rage if cast about 30 rage.

**Comment by Jenovas** [comment]
Works as should. Spell uses up to 30 rage and DMG also grows with the more rage used.
As for the only 20 rage used - talent called Sudden Death makes execute return 10 rage, so it takes 30 rage and gives 10 back right away making you think execute works badly.
Closing.

**Comment by Nukeey** [comment]
1. That's not how sudden death is supposed to work
2. It only does bonus damage as if it uses 10 rage, and not the full 20 rage. This is easy to test if you don't believe me.

What sudden death does is not use bonus rage that would put you below 10 rage, so if you use it between 20 and 39 rage you will always end up with 10 rage left, and the bonus rage consumed varies between 0(for 20) and 19 (for 39). All above that should use 30 rage.

**Comment by Jenovas** [comment]
I did tests with no talents - execute took 30 rage and hit for 800
I did tests with sudden death - execute took 20 rage and hit for 800

The DMG stays the same only sudden death makes your execute take 20 rage but it still hits as if 30 rage was used. Both tests were done when I had 100 rage so sudden death ALWAYS makes your execute cost 10 less but the DMG doesnt change.

**Comment by Jenovas** [comment]
Math:
Execute Deals - 10 + AP * 0.437 DMG
Additional MAX DMG From Rage - AP * 0.874

I found a target with around 10% armor. My execute hits him for 880 DMG (with Sudden Death Talent).

Execute Deals - 10 + 630 * 0.437 DMG = 285
Additional MAX DMG From Rage - 630 * 0.874 = 550
Execute Total DMG - 285 + 550 = 835

With Battle Stance on and Two Weapon Spec from arms tree I have +18% to DMG.
Execute Total DMG + DMG Bonuses = 835 * 1.18 = 986 

Execute after 10% armor reduction - 986 * 0.9 = 887

So execute uses 20 rage but hits as if it used 30 rage and the DMG is GOOD. If it turns out that sudden death shouldnt reduce execute cost by 10 warriors will get nerfed.

**Comment by Jenovas** [comment]
[4506] Warrior:
- Sudden Death will no longer reduce the cost of execute by 10, instead it will save up to 5/10 rage if the caster's rage would fall beneath that 5/10 rage
