### ISSUE TITLE
[Eng][Spell][Death Knight] Dark Command

### ISSUE THREAD

**Issue by aranguard** [Atlantiss/BugTracker#3888]
This skill is taunt for Blood Death Knights with 8 secs cooldown.
http://www.wowhead.com/spell=56222/dark-command
 First i want to explain what taunt must do.
 1. sets your threat equal to the highest threat on the boss.
 2. Forces the boss to attack you for the duration of the taunt.(for dark command its 3 sec and its working)

Problem is specific encounters (Halfus Wyrmbreaker in BOT, Argaloth in BH ......) When blood dk use that taunt aggro meter shows around %60 percent (not equal of other tank's threat pobably he must be %100+ at least and much more, for example  when i start on boss my threat stays over %200 all time.) and you have 3 sec to beat other tank's threat otherwise boss turning back to first tank and you need to wait 8 sec cooldown to threat back.

Its really big problem when needs to change boss instant and specific debuff rotations in raids.

**Comment by Kejmil** [comment]
it's death grip that work this way, check it and edit your issue or i will close it

**Comment by aranguard** [comment]
Death grip not worked at halfus hc when i tried last time.And about dark command its actually same as paladins reckoning.For example i started on boss as dk and my threat %200+ when pala use reckoning my threat reducing below %100 instant and he takes aggro and keeps it with his 8k dps.But when i use dark command dont know about his threat generate reduce or not but i cant keep aggro my 13k+ dps as blood dk Boss turning back to him than waiting dark command cd (death grip not worked at that time) when i use dark commad second time finally i got aggro but pala got 2 more stacks and died.It happened several times.Im just saying there must be something wrong about that.Maybe its about boss or maybe its about pala threat generate but its not good for dk tank.

**Comment by Ulissexo** [comment]
it doesn't matter how much dps you have as a blood DK, Paladins and Warriors have an insane increase amount of aggro with their skills (defensive stance for war and seal for pala), basically the problem here is that you cannot overcome your tank partner aggro

**Comment by aranguard** [comment]
i know and blood dk have blood presence for aggro same as others.But its ok I will check again next week more carefully and compare with other bosses and open new one if its still persist you can close this one.Btw thks for your attention.

**Comment by Ulissexo** [comment]
Also, as a Tank myself, you need to encourage your tank partner and ask him to overuse his abilities when you are trying to get aggro. I am a Warrior Tank and everytime there's a raid that involves switching bosses, I always stop using skills in order to let my tank partner to take some aggro (because normally i would steal his aggro very quickly), check this as well, maybe he's just spamming all his skills and getting aggro back

**Comment by ahtebe** [comment]
Dark Command is an 8 second taunt. All other tanks have an 8 second taunt. This taunt should not only force the mob to attack the tank, but also give the tank enough threat to be at the top of the mob's threat table.
Death Grip is a secondary taunt like ability.

**Comment by aranguard** [comment]
Yea that was my point.

**Comment by Ulissexo** [comment]
When you taunt a target, your threat goes to the top of the List along with the Top 1 of the list....in that case is 100% only (yellow) and you must go UP to 120%-130% in order to take the boss aggro, like i said before, it might be possible that your tank partner is doing a lot of aggro after you taunt him that it causes the boss to attack him again after the "3 second" time expires.

**Comment by Jenovas** [comment]
Works properly.
