### ISSUE TITLE
Frost dk mastery cant be real....

### ISSUE THREAD

**Issue by baronfyfy** [Atlantiss/BugTracker#3922]
ive run the numbers on the mastery for frost dks, and it cant be right. ive bee playing frost dk since Cata. and the numbers just dont add up. even tryed bypassing hit/expertise cap with no dif. ive reported this issue on dif servers with no response, hoping to hear from you.
frost dk 4ever!

**Comment by Varchord** [comment]
https://github.com/Atlantiss/BugTracker/blob/master/README.md


aaand it's getting closed

**Comment by sunshineinabox** [comment]
If you have ran numbers please include them and also make it so your title matches the guidelines for bug submission. You should include proof of what you are saying.

**Comment by Kejmil** [comment]
There is a reason why masterfrost spec happened.
Also there is possibility that your character avoid talent resets to clear double mastery or other kind of thing.
Do math and edit your issue to match rules or i will close it.

**Comment by Helbringer** [comment]
I dont know the math but id like to see this get investigated if possible. I played a frost dk on retail and it doesn't seem to have the same viability on atlantiss.

**Comment by sunshineinabox** [comment]
The mastery seems to be fine from small calculations that I've done. I'm only level 81 might have issues when it scales at higher levels I will check it later

Here is an example of a calculation. 

>1322*(.44 * AP) = base dmg of Howling Blast

From you can calculate the increase in frost damage you are seeing:

> Base dmg * x + Base dmg = Observed dmg

When using that I was able to get a percentage that was pretty close to the increased frost dmg you should see using mastery.

**Comment by Jenovas** [comment]
Closing. We wont investigate a whole class cause you "dont know the math".

**Comment by Helbringer** [comment]
WTF was that for, i dont mind if you close it, Sunshine did the math for us. What is your problem ffs.

**Comment by Jenovas** [comment]
No one is rude, I just stated that it is not the job of Devs to test a whole class, because someone thinks his DMG is too low. You want a bug to be fixed? Find it and prove that it's a bug.

The rules of the bugtracker are "Make sure, that what you report is actually a bug." and baronfyfy doesnt know what is bugged and you by saying that you dont know if it works or not already breaks this rule meaning that the issue will be closed. So no one is being rude, we are only following the rules. 

Also Sunshine wrote "mastery seems to be fine" so this is a second reason why this issue should be closed. So just as you stated "What is your problem ffs"?

PS - you are the one being rude and I dont know why.

**Comment by sunshineinabox** [comment]
I agree  devs can't go around testing classes on a whim, but I have some free time I'll take a look at some other abilities if there are any issues I can post them to this issue right?

**Comment by Kejmil** [comment]
better make new ones that updating closed ones i guess

**Comment by Jenovas** [comment]
Sunshine please create a proper issue, with proof, with the proper title etc and please remember one bug = one issue. Thank you and have a nice day.
