### ISSUE TITLE
[EN][Raid-Cata] Al'akir Master Looter Problem.

### ISSUE THREAD

**Issue by kevlarz** [Atlantiss/BugTracker#3953]
Hello, We killed Al'akir and i had master looter on when i looted the items it wouldn't let me assign the loot to the players who won the roll for the loot so i took the item my self so i could then trade them the items. However it was saying that they were not eligible for the loot. 

Any chance you could give The neck to Devan and the helm token to Meloera please.

![wowscrnshot_072615_195919](https://cloud.githubusercontent.com/assets/13303461/8895424/db38d7a0-33d1-11e5-9a6e-75e0aec7a21b.jpg)
![wowscrnshot_072615_200645](https://cloud.githubusercontent.com/assets/13303461/8895433/148a9700-33d2-11e5-8e10-12f46c07d4ff.jpg)

**Comment by Aival94** [comment]
once had the same problem.The issue was that they were not enough close to loot location when you press to loot so they cannot take these items.I made a ticket and GM told me he cannot do anything at all for this so i just sell items.You can either sell them or trade them to someone else who might need them.

**Comment by Sayris987** [comment]
Ye players being out of range of the boss corpse or in al'akir case that box or w/e is it you cant give the loot to them i dont know if its a bug or thats how it suppose to be but to avoid this just make sure everyone are near the corpse of the boss before actually looting him

**Comment by Bildo** [comment]
fixed rev  4670
