### ISSUE TITLE
[EN][Npc] Garr rare boss in Mount hyjal

### ISSUE THREAD

**Issue by theodoros96** [Atlantiss/BugTracker#4004]
Today me along with 11 people killed Garr at mount Hyjal and he dropped "Garr's Girdle of Memories" and "Design: Guardian's Nightstone" both of which do not belong to his loot list according to wowhead,  
http://www.wowhead.com/npc=50056/garr.

**Comment by Pallitax** [comment]
• Title doesn't follow the guidelines

https://github.com/Atlantiss/BugTracker/blob/master/README.md

**Comment by lanrutcon** [comment]
Garr's loot got updated on 4.1 patch.
Since we are on 4.3.4 patch, instead of ["Garr's Girdle of Memories"](http://www.wowhead.com/item=67235/garrs-girdle-of-memories) players should now get ["Garr's Reinforced Girdle of Memories"](http://www.wowhead.com/item=69842/garrs-reinforced-girdle-of-memories)
About ["Design: Guardian's Nightstone"](http://www.wowhead.com/item=52367/design-guardians-nightstone), Garr can drop it.

**Comment by Varchord** [comment]
Content wise we are on patch 4.1 and he should have loot table from patch 4.1

**Comment by Aival94** [comment]
the loot table updated on 4.1 so it is supposed ot be updated here as well.

btw i think is the same report: https://github.com/Atlantiss/BugTracker/issues/1092

**Comment by Samineh** [comment]
Today we killed garr and no loot T.T

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/1092
