### ISSUE TITLE
[EN][Quest][Blasted Lands] Blood Ritual

### ISSUE THREAD

**Issue by Enay** [Atlantiss/BugTracker#408]
**Blood Ritual** (http://www.wowhead.com/quest=26160) gets an auto-complete. All this quest is talking, but the talking part is missing. NPC should walk around, talk about the ritual, and then do it, and then the quest is complete, but here, quest just auto-completes right away, as you take it.

Here's how it should work - https://www.youtube.com/watch?v=s6vlxMnB6pc

**Comment by RastaTinu** [comment]
Quest still "autocomplete"

**Comment by tomatosz** [comment]
bump

**Comment by tomatosz** [comment]
Fix for alliance side on forums:

https://community.atlantiss.eu/index.php?/topic/14902-quest-blood-ritual/

Additional details for horde (anything not mentioned is the same as alliance side):
npc is 7506 (instead of 42298)
quest is 25686 (instead of 26160)
gossip is 'I would like to start the Blood Ritual, Lynnore.'
after first talk she walks forward ca. 3 yards to ca. (-11466.5,-2629, 3.231252) in ca. 1-1.5sec (couldn't measure exactly, vid: https://www.youtube.com/watch?v=v0X46yrxYvI
For Lynnore, gossip_menu_option id=1, creature_text group_id IN (0,1) and smart_scripts id IN (0,1,2,3,4) are already used (if [my previous fix](https://community.atlantiss.eu/index.php?/topic/14892-quest-loramus-thalipedes-awaits/) gets accepted), so don't use DELETE on those tables and start after these numbers.

**Comment by tomatosz** [comment]
Also added horde side on the forums:
https://community.atlantiss.eu/index.php?/topic/15484-quest-blood-ritual-horde-only/

**Comment by Piklo** [comment]
should be fixed in [rev. 5608](https://atlantiss.eu/changelog#rev5608)
