### ISSUE TITLE
[EN][QUEST] Daily fishing and cooking quests in Dalaran

### ISSUE THREAD

**Issue by Anhaeyn** [Atlantiss/BugTracker#4087]
I know, that this was already reported here https://github.com/Atlantiss/BugTracker/issues/1777, but it's closed when this problem still exists. 
When I accept daily quest from Marcia Chase (fishing trainer), I don't have available quest from Awilo Lon'gomba (cooking trainer). If I accept daily quest from Awilo, I don't see any quest from Marcia. For me it's huge problem, because I'm leveling cooking&fishing now.

**Comment by Probullet25** [comment]
This problem is closed because different zone are still bugged. Some exemples are Orgrimmar and Dalaran. Soo if you start fishing for Coins or Lurker Above Achivement you can't do this because message ''you can't fish in this zone\place '' appear everytime. It would be great if GMs can fix this game core.

**Comment by badpollo** [comment]
Dalaran fishing worked after a patch earlier today... but then they restarted the server and it was broken again :(

**Comment by Probullet25** [comment]
Fishing in Dalaran, Serpentshrine Cavern and some zone of Orgrimmar have a bug i think because i try fishing in this zone everyday but nothing changes, Soo i wait soo much for this fix because im a player how love to Fishing and make Cooking.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/1777
