### ISSUE TITLE
[EN][Rogue] Shadowstep in Pve Environment

### ISSUE THREAD

**Issue by Evelinrose** [Atlantiss/BugTracker#4091]
Ello let me just start by saying that there are already 2 issues for this reported however none of them explains in detail where exactlly shadowstep fails to work properly.I will try to make one big report here and will update with more boses as i disscover them.For the sake of keeping things simple you can close issue 1868 and 2283 or just coppy info from this one into either one of them.

Starting with cata raid Blackwing Decent
1.Magmaw-it doesnt work like it should,this is the quote from elitist jerks thread(can be found here http://forums.elitistjerks.com/topic/118015-cataclysm-subtlety-compendium/)
"Shadow Step can be used safely while Magmaw's head is grounded. Using ShS at any other time will drop you into the lava behind him"
2.Atramedes-part where you would teleport behind him while in the air phase doesnt work,although shadowstep does work when he is in the air it doesnt put you right next to a boss so you can fall down, but rather under him,another quote from elitist jerks 
"On Atramedes air phase, you can combine Shadow Step with Flexweave Underlay, Levitate, or Slowfall to DPS him in the air. If kiting fire on Atramedes, this can also be used to avoid the flames (it will remain at the position below you until you land)."
3.Nefarian-starting with adds-Chromatic Prototype-quote
"On Nefarian, you can Shadow Step to the adds on the pillars to completely avoid any time in the lava."
If you do that on atlantiss you will fall down into.....am not really sure what it is some kind of weird world where you can see encounter from distance as if it's right above you.
Essentially both Nefarian and Onyxia have issue if you shadowstep on them,you would appear in same place as mentioned above.

Bastion of Twilight
4.Cho'gall-while shadowstep works completly fine on boss it self, if at any point he is very close to a middle of the room or you simply would like to shadowstep mind controlled players who are in the middle and instantly interupt them  you would find yourself in sinestra's room right under it

Throne of the Four Winds
5.Conclave of winds-only one part is not working correctly here and that is nezir when you shadowstep him during ultimate you go under the boss even tho slipstream get's you back on platform over time.
This should be it more or less,i was able to test every single cata dungeon and pretty much every single boss,luckily it works nearly perfect,only one you arent able to shadowstep would be Ozumat in throne of the tides,however i think this one is intended.

Some observations i made-usually it doent work on higher ground terrain such as platforms or stairs but not necessarily every time,i would use conlave of winds and al'akir as comparison while on al akir it works perfectly.however not on nezir doesnt even tho both of the boses are on platforms.What i also saw some guys coplaining about is if boss is very close to wall and you shadowstep him somtimes u literally find yourself inside the wall and that's where you can fall down trought the world aswell.

P.s only reason why i quoted some of elitis jerks posts is to show that it was possible on retail as proof and not just make something up.

**Comment by xolon** [comment]
These  are all mmap/pathing/transport problems. For magmaw exposed head phase you already have a bug where you have to face the position where his body was in normal phase thats where you shadowstep, imho shadowstep works alright its just some of these problems above

**Comment by Evelinrose** [comment]
Xolon thank you for posting things which i already mentoned above if you actaully bothered to read entire post :)
Also you are wrong about magmaw,it doesnt metter where you stand and what phase it is,it will always drop you down in lava and one last thing these really are somewhat of a boss speciffic things and therefore whole point of this report is to highlight them so they could be checked individually.

**Comment by xolon** [comment]
Ok, lets start again.
I never stated that you wouldn't fall down in lava on magmaw. I waned to say the reason why you fall is that his exposed head is visualy on the spike but to actualy hit him you must face the position where he is in a normal phase, so when you shadowstep it drops you behind that and you fall in lava. 

For Nezir, when he does the ultimate he slightly teleports under the textures the reason you fall thru the map (same for anshal)  thats why bosses tend to get stuck in one place.

For Cho'gall middle of the room platform ( door,drop,gate or w/e) its really the MMap problem . For example if you relog/alt+f4 on that you have a chance to drop down to sinestra. MMaps present the "invisible walls" inside such objects (doors etc) which should prevent you from falling,going thru (etc. on retail you should never be able to exploit that door in black temple because there is a wall blocking you) these object should open after certain criteria is done and that "invisible wall" should disapear. For Nefarian is the same problem. I really don't know what causes that teleport deep inside the lava.

The only problem with shadowstep here is at atramedes. You should certainly be able to shadowstep into the air. Maybe its not just the problem with Atra go check it out on some flying mobs. (Btw its Sniprep here)

**Comment by knasen88** [comment]
I've noticed shadowstep doesn't try to alter your "z" location like x y z system that wow uses ( also makes shadowstepping airborne targets useless since you end up under them)

Merely fixing so that shadowstep moves you up a little after use would fix many issues of falling through the floor since it would be like a long range jump- ish.

**Comment by gumby123** [comment]
This bug is very annoying. It seems like currently there is no vertical (z) movement implemented for shadowstep. For instance, you can't shadowstep to a target that's in the air.
