### ISSUE TITLE
[EN][Quest][Mount Hyjal] Lycanthoth the Corruptor

### ISSUE THREAD

**Issue by mariohenriquebr** [Atlantiss/BugTracker#4199]
When you kill Lycanthoth, should appear the Spirit of Lo'gosh, but I tried twice and it didn't happen, just in the third time. 

http://www.wowhead.com/quest=25272/lycanthoth-the-corruptor#comments

**Comment by pelekon** [comment]
Spirit of Lo'Gosh is summoned by item from other quest( http://www.wowhead.com/item=52854/totem-of-logosh ) It's little hard to get it because you have to go on the road and do all q in Lightning Ledge ( http://i.imgur.com/WtGLh78.jpg http://i.imgur.com/vhUoNBe.jpg ) If you fly down right to Takrik Ragehowl You'll have wrong phase and quest Lycanthoth the Corruptor will be not possible to complete.

**Comment by mariohenriquebr** [comment]
Well, i did the quests before the "bugged" quest i've reported. The problem is that the Lo'gosh doesn't appear, when it have to appears, without any item or anything else. I've had to abandon the quest and get it again three times.

**Comment by Bildo** [comment]
https://github.com/Atlantiss/BugTracker/issues/1195

**Comment by Simgiov** [comment]
The first post is correct, it appears after you kill Lycanthoth 3 times. You should reopen the ticket.
