### ISSUE TITLE
[EN][Quest][Cooking] Cooking dailies 

### ISSUE THREAD

**Issue by Achiver** [Atlantiss/BugTracker#4227]
Horde has 2 available cooking dailies in Orgrimmar 
(One is always <a href="http://www.wowhead.com/quest=26233/stealing-from-our-own"> Stealing From Our Own <a> and the other is random) and taking them does not prevent player from taking  another daily in Thunder Bluff . Undercity cooking and fishing dailies dont work.

Alliance has only 1 quest available either in Stormwind, Ironforge or Darnassus  and taking one prevent the others from being taken.

It is not fair as horde can earn 3 tokens per day (1 recipe every day) when alliance only 1 (1 recipe every 3 days)

Screen with 3 cooking dailies : 
![wowscrnshot_081415_132330](https://cloud.githubusercontent.com/assets/13379840/9272971/d2f3dae4-4287-11e5-94ec-ae2f85093072.jpg)

**Comment by Anhaeyn** [comment]
I would like to add, that quest "Stealing from our own" doesn't counts to cooking achievment, and you can get two quest with this title - one to get trolls barrels, and second one for goblin barrels, which should be available only for troll players. Because of this bug, can't complete cooking achievments and get title.
