### ISSUE TITLE
[EN][PvP][Arena] 3v3 doesn't work

### ISSUE THREAD

**Issue by Genomnomnomnom** [Atlantiss/BugTracker#4299]
We were waiting for next 5 minutes after making screenshots.

http://i.imgur.com/WTbtApm.jpg?1
http://i.imgur.com/yuYra1o.jpg

**Comment by blinkmaster** [comment]
Probably smth is bugged with the ques again, it didnt connect for rated bg and often for 2v2 we wiat for a long time, week ago 2h in que 20-22 and no arenas sooo...

**Comment by Jenovas** [comment]
We checked the arena queueing system a few times and it seems that everything is ok after my latest fixes. We will probably add some logs showing Team Name, Team Min Rate, Team Max Rate, Team Arena Rate, Team MMR, Team Waiting Time etc. It might turn out that because of the wrong queueing system that was before and the problems we had with calculating arena rating and MMR something got badly bugged for some teams (say 10000000 MMR or something like this).

**Comment by blinkmaster** [comment]
oke but will it help or we still wont be able to play arenas as normal ? :S

**Comment by Jenovas** [comment]
rev. 4610 
PvP:
fixes to Arena Queue System - needs testing, also please check if Rated BG works after this fix and send me a report
changes to gained rate from arena's - MMR, Personal and Team Rating will grow faster until they are even

Please check it after this rev.
