### ISSUE TITLE
[EN][Spell][class] Druid Resto haste ticks are bugged

### ISSUE THREAD

**Issue by phanttom** [Atlantiss/BugTracker#4346]
SIr are u noob or what why did u delete my ticket without reading it well !!!!! i posted paragraph: i have 13.12% haste and my wild growth ticks 8 times
13.12% haste with full nature grace =30.09% haste than gives my wild growth ticks 9 times
13.12% haste + nature grace + beserking(troll)=56.10% haste BUT it gives me only 8 ticks of my wild growth !! why? because its bugged .... and druid healer always rely on ticks

AND u replied : Did a test on the main realm.
Druid resto with 13.37% of haste from gear.
13.37% + Nature Grace = 30.37%
Wild Growth ISNT bugged because it ticked 9 times.
Closing the issue. .................................................................................................................................................................... OMFG reallly !!!!! 13.37% + Nature Grace = 30.37% give 9 tickssss corrrrrrrrrect BUT try now!!! 13.12% haste + nature grace + beserking(troll)=56.10% haste and u GET 8 ticks even less than 13.37% + Nature Grace ...........................did u get my point or want me to show u manually !!!!!

**Comment by Aydien** [comment]
Ticks and haste for resto druid:

entries in this list assume a 5% haste buff from a Moonkin, Shadow Priest, or Shaman totem(!).

916: 5th tick of Rejuvenation. 
1573: 9th tick of Wild Growth and Effloresence with Dark Intent. If you have DI, you only have to make it to here instead of 2005 to get this nice bonus.
1602: 5th tick of Rejuvenation without 5% haste. If you're missing the haste buff, you really want to be at this point or higher.
1779: 6th tick of Rejuvenation with Nature's Grace.
2005: 9th tick of Wild Growth and Efflorescence. This point is very valuable, as these two spells make up a large portion of our healing.
2032: 6th tick of Rejuvenation with Shard of Woe proc active. If you have a Shard, this is only a small leap from 2005 and makes your trinket use much more effective.
2490: 7th tick of Rejuvenation with Nature's Grace and Shard of Woe active.
3106: 11th tick of Wild Growth/Efflorescence with Nature's Grace.
3478: 6th tick of Rejuvenation with Dark Intent.
3754: 10th tick of Wild Growth/Efflorescence.
3967: 6th tick of Rejuvenation.


Coppied form "http://forums.elitistjerks.com/topic/109405-resto-cataclysm-43-dragon-soul/"

**Comment by phanttom** [comment]
yea i know these im nt noob BUT the BIG idea is when u have 56.10% haste u will have less ticks than 30.37% in WILD GROWTH spell !!! plz explain maybe im noob and i dont get it if that is true means same as u saying 1=-3 in realife

**Comment by phanttom** [comment]
To be more clear WHY i have 8 ticks of wild growth with 56.10% haste and i have 9 ticks wild growth with 30.37 haste.......implies 30.37%> 56.10% i should quit math teacher in real life

**Comment by phanttom** [comment]
Extra details: 13.12% haste+ timewarp + nature grace + Beserking(troll)= 102.94% haste rating and my wild growth ticks only 7 Times !

**Comment by LaveGit** [comment]
https://github.com/Atlantiss/BugTracker/issues/4339 Has been reopened.

"I will reopen the issue and change it cause ONLY wild growth is bugged by haste and no other druid HoT."

**Comment by ezzira** [comment]
Well the problem is you didn't read the tooltips and you didn't do the math right. Time Warp and Berserking only increase your melee, ranged and casting speed. they don't increase your haste rating in 4.3.4., so if you do the math:
1681=13.12% haste rating (base stats+gear), lets add the 5%haste increase from moon kin/shadow/totem:
1681/100*5=84 haste=1765 haste rating. now add nature's grace (3 points), this will increase your haste by 15%:
1765/100*15=265 haste=1765+265=2030 haste rating.
the breakpoint for the 9th wild growth tick is 2005, so when you have the 5%haste increase from the auras/totem and nature's grace proc's you can get the 9th tick for wild growth. if you don't the the 5% haste increase you'll only get 8 ticks for wild growth.

so what do we know now? haste works like it should. Time Warp and Berserking only reduce's casting time of your spells and don't increase your haste rating.
http://www.wowhead.com/spell=80353/time-warp#changelog
http://www.wowhead.com/spell=26297/berserking#changelog
(if you hover over the 4.2 version you will see the tooltip, with 5.0.4 these spells were changed to increase the haste rating).
