### ISSUE TITLE
[EN][NPC][ITEM] Quatermaster selling bags

### ISSUE THREAD

**Issue by Helbringer** [Atlantiss/BugTracker#4358]
![wowscrnshot_082615_130215](https://cloud.githubusercontent.com/assets/10423624/9492790/ba366020-4bf2-11e5-9c7f-fc698dda3564.jpg)
As you can see in this screenshot, this 16 slot bag requires nothing but 1,90g
All horde and maybe allience Quatermasters all sell these 16 slots, however they should not be sold without the player having at least revered repuation with the corresponding faction.
As a guild master, i know pretty much every member of my guild will buy these, this is not blizzlike and it also completely breaks the economy as 16 slots have to be sold for less than a gold.
http://www.wowhead.com/npc=50477/champion-uruzin
http://www.wowhead.com/npc=50488/stone-guard-nargol
http://www.wowhead.com/npc=50484/magistrix-nizara
http://www.wowhead.com/npc=50323/frizzo-villamar
http://www.wowhead.com/npc=50304/captain-donald-adams
http://www.wowhead.com/npc=50483/brave-tuho

**Comment by Avalain** [comment]
Confirm, those bags are being sold without reputation requirement on Alliance side as well.

It's also worth mentioning that there is problem getting said reputation while wearing tabard provided by those NPCs due to bug in which we're not receiving reputation gain in old instances while leveling (while wearing said tabard).

NPCs affected with reported bug from Alliance side:
http://www.wowhead.com/npc=49877/captain-lancy-revshon
http://www.wowhead.com/npc=50309/captain-stonehelm
http://www.wowhead.com/npc=50308/master-tinker-trini
http://www.wowhead.com/npc=50305/moon-priestess-lasara
http://www.wowhead.com/npc=50307/lord-candren
http://www.wowhead.com/npc=50306/kadu

**Comment by sigmundfreud2016** [comment]
Not a big deal. And it somehow compensates all the bugs with rep.gain. On retail I normally got Revered with all 6 factions on ~40 lvl simply by using LFG. Here I barely get Revered with my natural faction (i.e. human <-> SW, worgen <-> Gilneas, etc) on ~50 lvl because rep is gained only in Stratholme and Scholomance.
>completely breaks the economy
Are u serious? Since WOTLK nobody buys 16 slots as there are cheap 20 slots. So its pretty much blizzlike.

**Comment by Helbringer** [comment]
If you want everything to be bugged, go back to molten.

**Comment by Piklo** [comment]
posted fix on forum:
http://community.atlantiss.eu/index.php?/topic/12540-4358-reputation-bags/

**Comment by TranceAccount** [comment]
Fix got rejected.

**Comment by sunshitwowsucks** [comment]
i think it was rejected because item data is located in item-sparse and custom items/the other ~ 200 items not in the sparse are in item_template

**Comment by wtRCH** [comment]
It's still a bug, confirming it from yesterday gameplay with fresh character

**Comment by Artamedes** [comment]
atlantiss need to do this: 

create hotfix system if not have one already

update the item data, either in a new item-sparse table or item_template then send hotfix in client (send SMSG_HOTFIX_NOTIFY_BLOB on the load screen with the itemids in that then when client send CMSG_REQUEST_HOTFIX send SMSG_DB_REPLY to client)

core should handle RequiredReputationRank  and RequiredReputationFaction 

here's what i did for this system

https://gyazo.com/3ef759354e38365455e9434b2ccfbfb7
https://gyazo.com/854a33fd0791fbd3d962702400d80f5f
https://gyazo.com/b866c0af17154274b5f5b8c4f3974d4a
https://gyazo.com/7c21a9c33753893084f7ae37663fdc24

gogo @TranceAccount :D

**Comment by wtRCH** [comment]
fix pending
