### ISSUE TITLE
[EN][Item] Lethality Analyzer.

### ISSUE THREAD

**Issue by Dearkus** [Atlantiss/BugTracker#4384]
http://www.wowhead.com/item=63426/lethality-analyzer
You are able to cast this item on yourself which allows you to fly after swimming with the debuff.

**Comment by EnderBlazer** [comment]
I can confirm this. My frost mage character (Icelcebaby level 26) was on the quest Studies in Lethality (http://www.wowhead.com/quest=28324/studies-in-lethality). When I tried using the item i forgot to select the slimes, instead the item worked on myself, turning me extremly small. It also works on other npcs AND PLAYERS, so it can be exploited in pvp, because not also it makes you small, it removes some of you health when turning you small. As mentioned above, when you swim with the debuff the item gives you, you can air swim. My internet connection is bad now so I'll upload a video demonstrating the bug in an hour or so.

**Comment by EnderBlazer** [comment]
Sorry for the delay, my connection is really horrible. The video quality is crap on the browser, download  it if you want better resolution.
https://www.dropbox.com/s/u1r3x3eksz378om/Icelcebaby.mp4?dl=0

**Comment by Pallitax** [comment]
This issue has been fixed, although it'll take some time for the fix to go live.
