### ISSUE TITLE
[EN][Talent][Warlock] Mana Feed (Demonology Tree)

### ISSUE THREAD

**Issue by idguakeren** [Atlantiss/BugTracker#4405]
The Warlock talent Mana Feed. (http://cata.openwow.com/spell=85175) was working perfect untill someday this week it's not working the way it's meant to. only some warlock pet gives you the mana, and most of them didnt. 
![felmana](https://cloud.githubusercontent.com/assets/13581125/9569038/7ff34656-4f87-11e5-9636-0f315cd93872.png)
We can see felhunter gives the warlock 4% of the mana pool from the talent when it does critical strikes.
![felnomana](https://cloud.githubusercontent.com/assets/13581125/9569056/1c3452b2-4f88-11e5-824b-9009c91a5941.jpg)
in this one felhunter does a critical strike at the target, but the warlock did not receive 4% of his mana pool back
![felnomana](https://cloud.githubusercontent.com/assets/13581125/9569062/3eaf2d6c-4f88-11e5-8e98-bd6b382ab529.jpg)
I tried with Felguard. it never gave me mana when it does critical strike. (the most used warlock pet for demo lock)
![impmana](https://cloud.githubusercontent.com/assets/13581125/9569039/90facf28-4f87-11e5-9170-bf937255111f.jpg)
The imp gives mana, but not 4% of the total mana pool
![sucunomana](https://cloud.githubusercontent.com/assets/13581125/9569072/8264f834-4f88-11e5-9a7f-9833a487b146.png)
Tried with succubuss. No mana gain.
![voidnomana](https://cloud.githubusercontent.com/assets/13581125/9569105/a00507ca-4f89-11e5-8cf2-cc49ca5732f4.png)
Voidwalker too

I hope you will fix this soon, best regards.

**Comment by anxanas** [comment]
Try reading the talent, its supposed to give 4% mana everytime your pet crits with a basic attack, as it looks now only imp works that way. felhunter gives around 20% mana back on crit so does felguard, the only reason yours doesnt proc it is cause you are retarded and doesnt have his basic attack turned on. Voidwalker doesnt have a basic attack(i think) and cant proc it.

Aka just close it the bugs he is reporting doesnt exist, the only bug with mana feed is felhunter and felguard basic attack crit gives around 4-5 more mana than it should.

**Comment by kadi2** [comment]
Felhunter and Felguard are supposed to give you 16% of your mana back. It's supposed to give you mana when they critical strike with their basic ABILITIES, not melee autoattacks. Assuming everything works fine and can be closed.

**Comment by swiftstrike763** [comment]
Hello, I didn't want to start a new thread as I saw this one was still open. I've been struggling with whether or not I should post it because I accept the possibility that I'm missing something or not including everything in the math, but to me, it doesn't seem like Mana Feed is working properly. On my level 25 Worgen Warlock Krugen I have 1718 mana, and 4% of that is 68.72 according to google, so I'm thinking it should be around ~67-70 right? The thing is, when Mana Feed triggers, I get around ~274. Maybe this is intentional? Here's a screenie.

![wowscrnshot_081316_212001](https://cloud.githubusercontent.com/assets/21016015/17646748/e944de62-619c-11e6-8cfe-7e879b0f63bb.jpg)
Please feel free to delete/disregard this if it turns out I'm mistaken. I just felt I should put the info out there. Thanks guys.

Swiftstrike
