### ISSUE TITLE
[EN][Other] Transmogrification issue

### ISSUE THREAD

**Issue by Shisai** [Atlantiss/BugTracker#4412]
Currently you cannot transmogrify to an item that has no stats, however, you should be able to transmog to any item as long as it is uncommon (green) or higher quality.

http://wow.gamepedia.com/Transmogrification or http://us.battle.net/wow/en/forum/topic/3196342583

"Only uncommon (green), rare (blue) or epic (purple) items may be transmogrified. (exceptions: a select few of these items will be prevented from being used to transmogrify if they are inappropriate)"

**Comment by ezzira** [comment]
re-read the article and you'll see "Contrary to the blue post above, the quality (color) of an item does not matter at all, the basic rule is that it has to have attributes to be a valid source.."

**Comment by MorbidMike** [comment]
What matters though is that you can not use items that do not have base stats (such as Stamina or Attack Power) to transmog. A whole range of items that have procs but not stats SHOULD be usable to transmog. 

For example: Skullforge Reaver (http://www.wowhead.com/item=13361/skullforge-reaver#comments) has only a proc, no base stats, and is not usable for transmog on Atlantiss but it was usable for transmog on retail:

"By Aknazer (1,202 – 3·15) on 2011/12/16 (Patch 4.3.0)		
For those that had the lvl58 version of this sword it was downgraded (along with the Cape of the Black Baron and likely any other strat/scholo item still in the game) to the new ilvl/req lvl. 

Also if you use this weapon to transmog a different weapon know that your new weapon will indeed have the purple glow."

Another example: The Night Blade (http://www.wowhead.com/item=31331/the-night-blade#comments). Same issue.

"By Kthxbb (1,487 – 5·17) on 2012/04/06 (Patch 4.3.3)		
I got The Night Blade while I was killing mobs in Netherstorm for a quest back in the day. Anyways, I was kind of sick with the Landslide enchant on my 1st phase daggers so I decided to transmog them. It costed only 2 gold to transmog for both daggers and now instead of having the sun on my toon's hips, I have 2 dark orbs. Definitely suits the rogue style better than bright landslide. It looks way more sinister."

This proves that weapons with ONLY a proc, and no other attributes such as Crit or Strength, must be valid for transmog.

**Comment by Wolffenstein** [comment]
Fixed in rev 4701.
