### ISSUE TITLE
[EN][Proffession][Fishing] Fishing in Dalaran, Ironforge and Serpentshrine caverns

### ISSUE THREAD

**Issue by eclipex** [Atlantiss/BugTracker#4416]
We can't Fish in Dalaran fontain same for Dalaran underbelly, Ironforge lake and in the raid of Serpentshrine caverns so, many achievements are not possible to get.

When we try to fish in that areas it's says : " You can't use that here." 

I guess that the water is indetectable or someting

**Comment by Probullet25** [comment]
Yes all we know that but if you search on BugTracker you will find alots of more topics about Fishing and Cooking. I see alots of old player have "Lurker Above" or Fishing Dalaran daily quests, Now you can make Dalaran and Thunder Bluff Cooking Quests. In Orgrimmar "Stealing From Our Own" dont work soo you cant make achievment. About Fishing in Dalaran fountain and in SSC raid you cant fishing because this zones are bugged. I think GMs try hard to fix that, but only we need now is just waiting for this, If fishing and cooking will be fixed. this Cataclysm server become best scripted private server. :) Cheers

**Comment by maciekf3** [comment]
I beg you GMs, repair fishing in these places

**Comment by aranguard** [comment]
Same here.Its important part of game also cooking dailies in cities these kind of bugs must have priority.

**Comment by Bildo** [comment]
fixed by Wolfenstein
