### ISSUE TITLE
[En][Shaman][Pet]Feral Spirit - Auto cast on summon

### ISSUE THREAD

**Issue by comnet256** [Atlantiss/BugTracker#4435]
Upon summoning feral spirits two spells are automatically on auto-cast : Bash and Feral Wolf Leap.
It is possible do disable them but they will auto enable the next time wolves are summoned.
This is a huge issue in pvp as enhancement shamans rely on manually casting Bash for an additional interrupt on demand. 
Additionally it causes the pets to go through 2 global cooldowns before being able to use Spirit Walk, which is a key ability when battling any class or match-up that has root and slow effects.

**Comment by Jenovas** [comment]
Just checked the internet and auto cast on summon aint a bug, there are even ppl on blizzard forums / arena junkies / wowhead asking for macros to turn off auto-cast Bash after summon.

Closing.

**Comment by comnet256** [comment]
Feral spirits are considered temporary pets. Temporary pets did not save action bars before cataclysm thus the topics you've found.

**Comment by Jenovas** [comment]
http://us.battle.net/wow/en/forum/topic/1648725799 - post from the 23 of December 2010
Cata was released on the 12 of October 2010

http://us.battle.net/wow/en/forum/topic/981899064 - still talking about Feral Spirits having spells on autocast and please create a macro to shut it off + QQ posts that Feral Spirits cant be controlled and when in combat the first thing after being summoned is them bashing the target. - the topic is from november 2010 so still after the release of Cata.

Please find a post / a video that shows us that it should not be on autocast after summon and we'll reopen. 

Thx and have a good day.


PS - 
Post 1 - "We don't. And we can't control that Stun. It's still bugged to where the moment you cast Feral Spirit, the first thing they do to the first thing they attack is Bash. 

I also can't believe you're perfectly fine with us relying so heavily on our Spirit Wolves in order to perform well in PvP."

Post 2 - "Um... just turn Bash auto-cast off and macro it to something? <.<"

Post 3 - "It's bugged. It's always auto-casted. "

From Cata.

**Comment by comnet256** [comment]
The second thread you linked dates - 11/8/2010
The first thread you linked dates - 12/23/2010 ,so it's after the first one,and in it the only response points towards being able to normally disable the bash and no-one disputed it at that time.

The time discrepancy between 4.0.1 and 4.3.4 is 2 years,we are on 4.3.4,even if it was bugged early on cata launch,blizzard certainly fixed it by 4.3.4.

https://www.youtube.com/watch?v=O3L1Vply0-Q  - 
1:15 - Summoned,not on auto cast
2:20 - Summoned,not on auto cast
4:25 - Summoned not on auto cast and bash saved for later use
Note - Twin Howl even if on autocast, it does not cast against players as it does not affect them,it was part of blizzards "making pets smarter".
https://www.youtube.com/watch?v=vVFWb8SwLzI -
1:25 - Summoned,not on auto cast
https://www.youtube.com/watch?v=qr_NE9UoUaE -
1:00 - Summoned,not on auto cast AND custom pet bar setup as in cataclysm temporary pets can save action bars.

Additionally -> Most likely due to https://github.com/Atlantiss/BugTracker/issues/3359 , macros with /petautocastoff Bash do not work.

#showtooltip
/cast Feral Spirit
/click PetActionButtonX RightButton
Is a workaround but not a satisfactory one,shamans bind trinkets and racials to wolves and tapping this macro one too many times leads to re-activating the auto cast as it is a simulated right click.

**Comment by comnet256** [comment]
Bump

**Comment by scynthrax** [comment]
Here are two videos uploaded on youtube the 6th and 9th october 2010  where you can clearly that the pet's spells aren't on autocast when they are summoned.

https://www.youtube.com/watch?v=K5zvjolqzm4 
https://www.youtube.com/watch?v=z782OeoK7BQ
