### ISSUE TITLE
[EN][PASSIVE][PRIEST] Shadow Orbs doesn't work

### ISSUE THREAD

**Issue by franklin1l** [Atlantiss/BugTracker#4453]
I have a problem on my shadow priest. Every time I go to dungeon or just relog I lose the ability to spawn shadow orbs. It fixes after I reset my talents at priest trainer, but I don't want to do this every time.

**Comment by aneq** [comment]
if you buy dual spec and respec it also fixes it.

**Comment by franklin1l** [comment]
Thanks a lot, but it is just a temporary solution, hope somebody will fix it soon.

**Comment by Unresolute** [comment]
Can confirm that this is indeed the case. And its really unfortunate because its really annoying to having to swap specs 2 times at the begining of every dungeon, rebuff, remana, and so on. And considering this bug pretty much reduces like almost 30% of our damage it should be higher on the priority list... I mean 20 days...
