### ISSUE TITLE
[EN][Mage] Combustion haste scaling.

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4593]
## What's wrong:
With  48.83% haste my mage does 16 ticks of combustion(with initial hit; 15+1)

I think the problem is at  40% haste, combustion gets 1 additional tick, it shouldn't.
## How it should be:
It should do 15 ticks(with initial hit; 14+1) at 44.83% haste.

the haste scaling of combustion should be:

* under 5% (10+1)  -> **Correct**
* 5% -> +1 tick (11+1) -> **Correct**
* 15% -> +2 ticks (12+1) -> **Correct**
* 25%-> +3 ticks (13+1) -> **Correct**
* 35%-> +4 ticks(14+1) -> **Correct**
* 40%+ -> there shouldn't be a +5 tick.

## Proof:
https://www.youtube.com/watch?v=EJaEnJ1m2Ro
- at 0:15 you can check the combat log, he does 15 ticks of combustion alltogether with the initial hit(14+1)
     - and he has time warp up
- at 1:30 he shows the haste scaling of spells.
- at 3:00 he shows his gear and haste, he has 14.84% haste
      - At that gear you can calculate he has around 48.83% haste with time warp.Which means he passed the 35% line.

## Compared to our server:
http://tinypic.com/r/w2c5de/8 -> 14.49% haste with gear + trinket popped (haste equal to the guys gear in video)
http://tinypic.com/r/kouox/8 -> 48.83% haste with gear + trinket popped + time warp (the haste the guy in video has when he pops combustion)
http://tinypic.com/r/2hnz6mp/8 -> the amount of ticks: 15+1 (the guy in video has 14+1) , with 1 less than we do here.

**Comment by Caturix** [comment]
I've been doing some tests, and I can confirm most of the bugs you reported. But for this one, i'm not sure if inicial damage "Instantly deals 1454 Fire damage and create a new periodic..." is counted as tick, or what?! Because with 23% haste I get these results: http://imgur.com/Ttu1c23

**Comment by razgal** [comment]
https://www.youtube.com/watch?v=EJaEnJ1m2Ro
- at 0:15 you can check the combat log, he does 14 ticks of combustion alltogether with the initial tick
     - and he has time warp up
- at 1:30 he shows the haste scaling of spells.
- at 4:30 he shows his gear but doesn't show his haste in char sheet
      - At that gear you can estimate he has around 45% haste with time warp.Which means he passed the 35% line.

Which means the initial damage it's calculated alltogether with the other ticks, since at 35% it's the last tick you get.

**Comment by razgal** [comment]
he has 15 ticks of combustion actualy.

**Comment by Badrng** [comment]
At 4,65% haste my combustion ticks 10 times, at 5,25 there are 11 ticks, at 14,97% there are still 11 ticks and at 15,89 there are 12 ticks. Combustion's haste scaling seems perfectly fine to me.
Apart from creating a DoT, Combustion also deals instant fire damage which might have mislead you into thinking the number of ticks is wrong; this damage, however, is not a part of the said DoT. Another explanation of why you came up with wrong results is that you might have been testing it with a 5 % haste buff.

**Comment by razgal** [comment]
@Badrng
> Combustion also deals instant fire damage which might have mislead you into thinking the number of ticks is wrong.

That was what I was thinking until I saw the video above, that guy at 44.84% haste does 15 ticks combustion WITH initial hit. On our server with 41% I did 16 ticks with initial hit.So something is definetly wrong.

**Comment by Badrng** [comment]
First of all: haste is multiplicative, not additive. If you add Time Warp's 30% to his 14,84% from gear you get more than 44,84%  Combustion gets an additional ticks for every 10% haste starting from 5%, at 5% haste its supposed to tick 11 times, at 15% - 12 times, at 25% - 13 times, at 35% - 14 times. and at 45% - 15 times.
Since we established that the mage in the video was well above 45% haste with Time Warp (since haste is multiplicative) and thus he must have had 15 ticks of the dot AND an instant fire damage, 16 hits in total. 
At 44,86% haste my character gets 14 ticks of Combustion  AND an instant fire damage, 15 hits in total. 
I really have no idea how you're getting these results but they're wrong.

**Comment by razgal** [comment]
There is no extra tick at 45%. I'll test again when I reach home from 14.48% + time warp.To see if we have same values as the guy in video.
The guy in video did 14 ticks+1 initial hit, not 15+1 as you assume.Check the combat log.

**Comment by razgal** [comment]
http://tinypic.com/r/w2c5de/8 -> 14.49% haste with gear + trinket popped (haste equal to the guys gear in video)
http://tinypic.com/r/kouox/8 -> 48.83% haste with gear + trinket popped + time warp (the haste the guy in video has when he pops combustion)
http://tinypic.com/r/2hnz6mp/8 -> the amount of  ticks:  15+1 (the guy in video has 14+1) , with 1 less than we do here.

**Comment by razgal** [comment]
I eddited everything, Combustion works properly at 5%,15%,etc. Only around 40% it gets an extra tick, which it shouldn't.

**Comment by Badrng** [comment]
Ok, I get the problem now. 
Combustion gets an extra tick at 5% haste and then additional ones for every 10%. The amount of ticks isn't capped at, say, 4 extra ticks. With 100% haste you will get 10 additional ticks. The reason why all the guides only list haste plateus up to 35% is because they are the only caps reachable with gear available in cataclysm. Haste buffs that take you above 45% will continue to add extra ticks. See https://syntheticaether.wordpress.com/2012/01/30/wow-fire-mage-hastein-4-3/ for reference. The same is true for any other DoT in the game and results from the way the DoTs work in Cataclysm.
Let's get back to your case. You had 48,83% haste so you were above the 45% haste plateu, which is supposed to give you 5 ticks more than the base 10 ticks (11 at 5%, 12 at 15%, 13 at 25%, 14 at 35%, 15 at 45%). It really doesn't matter how many ticks were there in the video, you either counted them wrong or he was below 45% haste when he popped combustion. Maybe he had a different gear during the dummy dps test or when he recorded the part of the video in which he shows his stats he had the 5% haste raid buff, I don't know. The bottom line is that at 45% you are SUPPOSED TO get 5 additional ticks (15 ticks in total) and that's how it works on Atlantiss. Everything is fine.

**Comment by razgal** [comment]
nah I watched 10 times, its 14+1. I doubt a wordpress reference is more accurate than a video+ elitistjerk doesn't mention anywhere

**Comment by Badrng** [comment]
https://docs.google.com/spreadsheets/d/1WLOZ1YevGPw_WZs0JhGzVVy906W5y0i9UqHa3ejyBkE/edit?hl=en_US&hl=en_US&f=true&noheader=false&gid=19#gid=19
I hope you will find this more convincing. 
I guess this report can be closed now.

**Comment by razgal** [comment]
even so @Badrng , if indeed it should get an additional tick it should be at 45%, on our server you get it at 40% so a bug it is in the end
