### ISSUE TITLE
[PL][Achivements][guild] Dark pheonix mount

### ISSUE THREAD

**Issue by phanttom** [Atlantiss/BugTracker#4626]
well achievement guild of full bwd,bot,to4w doesn't work so we cant get the mount ...... old guilds have the mount ?! because achievement was working at that time .... and now u guys don't care to fix it because its been long time ! so its better to remove the mount from all players that have it to be fair with others ...or try to fix it because its annoying .. thx u .

**Comment by Aival94** [comment]
The Title should have [EN] but still this bug is normally about the achievement of teh guild Raids so is reported here: https://github.com/Atlantiss/BugTracker/issues/1716

About the mount,is true that some old Guilds have it when was working and might be unfair for new Guilds now but still do not is possible to disable everyone mount until they fix it.
