### ISSUE TITLE
[EN][TALENT][WARLOCK] Soul Siphon

### ISSUE THREAD

**Issue by Illusionist87** [Atlantiss/BugTracker#4699]
"Increases the amount drained by your Drain Life and Drain Soul spells by an additional X% for each of your Affliction effects on the target, up to a maximum of Y% additional effect."

Having DoTs on the target doesn't have any effect on the Drain Life spell. I get healed by the same amount with or without DoTs on the target.

**Comment by kadi2** [comment]
Drain Life also doesn't recive bonus from Death's Embrance damage bonus, when your target is below 35% HP. Reproduced on 84 level dummy, other skills worked fine with that talent.
http://cata.openwow.com/spell=47200

**Comment by meowmewo** [comment]
Confirmed.

**Comment by meowmewo** [comment]
Ok, so i tested Soul Siphon with 2 afflictoin specs . 1 with 1/2 and 1 with 2/2 becouse u cant go 0/2.
Results  -
1. with 2/2 it gives 6% additional dmg to Drain soul but thats it. Instead of giving 6% per dot on targets, it just gives it 6% dmg bonus regardless of how many dots. Always only 6%.
2. with 1/2- same result but with 3%.

So instead of giving  6 / 3% bonus dmg to Drain soul PER Dot on the target. It gives Drain Soul a static 6 / 3% dmg increase.

**Comment by anxanas** [comment]
bump

**Comment by kadi2** [comment]
You can close this report.
