### ISSUE TITLE
The Light of Dawn 

### ISSUE THREAD

**Issue by zxcanning** [Atlantiss/BugTracker#4784]
Death knight quest is bugged, army doesn't spawn after taking quest

**Comment by Thefakemccoy** [comment]
On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].

Use the search engine to find out if a similar problem has been already reported. If so, check if it's already been fixed and waits for update.
Make sure, that what you report is actually a bug.
Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com
Write your tickets according to the format:
[EN][Quest][Zone] A Vision of the Past
[EN][NPC] Thoralius the Wise
[EN][Spell][Class] Frostfire Bolt
[PL][Talent][Class] Brain Freeze
[EN][Glyph][Class] Glyph of Frostfire Bolt
[EN][Npc][Drop] Thoralius the Wise
[EN][Web] Armory doesnt work
List of currently supported tags /wiki/List-of-supported-tags-in-issue

**Comment by RandomPickNewb** [comment]
The quest does work only that there a bit of problems with the quest giver being in 2 locations at the same time and the army(spawned after taking the quest) doesnt despawn after finishing the event,so you end up and x armies of undead spawned at the same time.

**Comment by Anhaeyn** [comment]
This quest works. Abandon this quest and take it again - worked for me when I was leveling my dk.
