### ISSUE TITLE
[en][shaman] Lava lash vs. Glyph of Lava Lash.

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4904]
## What's wrong:
Lava Lash does more damage than it SHOULD when its influenced by Glyph of Lava Lash.

## Proof:
Tested on target with 0 resil, 0 gear, no talents buffs etc
the weapon I used and it's damage: http://tinypic.com/r/34t33b9/9
Lava Lash normal damage,without any buffs/talent increase/etc -> http://tinypic.com/r/1zlzxc5/9
**MIN.WEAP DMG**: 91
**MAX.WEAP DMG**: 104

Lava Lash damage with Glyph of Lava Lash -> http://tinypic.com/r/5yeqzs/9
**MIN.WEAP DMG**: 131
**MAX.WEAP DMG**: 149
## How it should be:
**MIN.WEAP DMG**: 91 * 1.2 = 109
**MAX.WEAP DMG**: 104 * 1.2 = 124

**Comment by razgal** [comment]
similar topic:
https://github.com/Atlantiss/BugTracker/issues/4900

**Comment by Bastion** [comment]
idz sie kurwa lecz czlowieku

**Comment by Jenovas** [comment]
Please add links. Thx.

**Comment by razgal** [comment]
lava lash -> http://cata.openwow.com/spell=60103
glyph of lava lash -> http://cata.openwow.com/spell=55444

**Comment by razgal** [comment]
and check my last post from here plz: https://github.com/Atlantiss/BugTracker/issues/4905
might be same issue

**Comment by Jenovas** [comment]
Well it seems the DMG is too low. 
From your SS we see min weapon DMG = 35.

DMG SHOULD BE:
Lava Lash Min DMG = 35 x 2.6 x 1.2 = 130
Lava Lash Max DMG = 41 x 2.6 x 1.2 = 148

WITH GLYPH
MIN.WEAP DMG: 218
MAX.WEAP DMG: 249

So this means Lava Lash doesnt hit too much it hits to little.
It turns out that is you dont have any modifiers it doesnt take 20% of mastery bonus to DMG.

Closing all issues with Lava Lash. Please create an issue that Lava Lash base DMG doesnt benefit from mastery.

Closing.
