### ISSUE TITLE
[en][shaman] Lava Lash vs. Improved Lava Lash

### ISSUE THREAD

**Issue by razgal** [Atlantiss/BugTracker#4905]
## What's wrong:
Lava Lash does more damage than it SHOULD when its influenced by Improved Lava Lash.

## Proof:
Tested on target with 0 resil, 0 gear, no talents buffs etc
the weapon I used and it's damage: http://tinypic.com/r/34t33b9/9
Lava Lash normal damage,without any buffs/talent increase/etc -> http://tinypic.com/r/1zlzxc5/9
**MIN.WEAP DMG**: 91
**MAX.WEAP DMG**: 104

Lava Lash damage with Improved Lava Lash at 5 searing stacks-> http://tinypic.com/r/ztz0p5/9
**MIN.WEAP DMG**: 218
**MAX.WEAP DMG**: 249
## How it should be:
for 5 stacks **MIN.WEAP DMG**: 91 * 2 = 182
for 5 stacks **MAX.WEAP DMG**: 104 * 2 = 208

it's probably bugged for 1-4 searing stacks aswell.

**Comment by debtheone** [comment]
Did you count base mastery which is 20%?? XD

**Comment by razgal** [comment]
mastery its automaticly calculated in lava lash base damage, which is in first picture (91-104 dmg)

**Comment by razgal** [comment]
now that might be the issue , mastery is calculated after the multiplicators, not before.

**Comment by Kejmil** [comment]
nope :D

**Comment by razgal** [comment]
that nope actualy solves a lot.

**Comment by Jenovas** [comment]
Well it seems the DMG is too low. 
From your SS we see min weapon DMG = 35.

DMG SHOULD BE:
Lava Lash Min DMG = 35 x 2.6 x 1.2 = 109
Lava Lash Max DMG = 41 x 2.6 x 1.2 = 124

WITH 5 STACK
MIN.WEAP DMG: 218
MAX.WEAP DMG: 249

So this means Lava Lash doesnt hit too much it hits to little.
It turns out that is you dont have any modifiers it doesnt take 20% of mastery bonus to DMG.

Closing all issues with Lava Lash. Please create an issue that Lava Lash base DMG doesnt benefit from mastery.

Closing.
