### ISSUE TITLE
[EN][Talent][Warrior] Blood Frenzy debuff has two different forms and also disappears.

### ISSUE THREAD

**Issue by Celiez** [Atlantiss/BugTracker#5024]
**How it works now:**
1. First application of Blood Frenzy by Rend (http://cata.openwow.com/spell=772) or Deep Wounds (http://cata.openwow.com/spell=12867) while there is no other bleed debuff present on the target has a proper, no-duration form. But this form can also _disappear from the target for no reason_ after refreshing and casting new bleeds on the target.
2. Any other subsequent bleeds cast on the target (Rend or Deep Wounds) will refresh Blood Frenzy with a _new_, weird Blood Frenzy debuff, and this form of the debuff will have a short duration timer (!) of around 3-4 seconds.
3. After a while, this short form of Blood Frenzy will stop being refreshed, leaving the target with no form of Blood Frenzy debuff even though the bleeds are still present on the target.
4. Back to point 1. and repeat: a new Blood Frenzy debuff with no duration will be applied to the target (usually after a crit with special ability Overpower).

It looks like this on Atlantiss right now:
![ezgif-3884880271](https://cloud.githubusercontent.com/assets/15706917/11405100/11ab5414-93a6-11e5-8ef4-c515aeb6548f.gif)

The first debuff on the left is Blood Frenzy. Second from the left is Deep Wounds, fourth from the left is Rend.
Watch as Blood Frenzy appears and disappears and changes from no-duration form to short-duration form.
Last debuff is Trauma, which works correctly since this fix https://github.com/Atlantiss/BugTracker/issues/1646.

**How it should work:**

**Just like you have fixed Trauma (http://cata.openwow.com/spell=46857) here: https://github.com/Atlantiss/BugTracker/issues/1646 Blood Frenzy should behave like a DEBUFF AURA WITH NO DURATION whenever any of the warrior's bleed effects are present on the target.**

Blood Frenzy debuff (http://cata.openwow.com/spell=29859) should be present on the target whenever there's either Rend (http://cata.openwow.com/spell=772) or Deep Wounds (http://cata.openwow.com/spell=12867) debuff present on the target, **or both at the same time**.
Blood Frenzy **should not have a duration**.

Retail video source: https://www.youtube.com/watch?v=99U7N1On8D4

![image](https://cloud.githubusercontent.com/assets/15706917/11404581/073402cc-93a3-11e5-8bf9-9e39471061d0.png)

This is core talent for an Arms Warrior dps.

**Comment by Exertt** [comment]
Can confirm. Makes my life as Arms Warrior a living hell.

**Comment by Pickles23** [comment]
nice detective work here

**Comment by freddie12** [comment]
There is a similar issue with Frost Dk's brittle bones as well. Brittle bones debuff may disappear even though the target has still frost fever on.

http://wowwiki.wikia.com/wiki/Brittle_Bones

**Comment by Aviannaqt** [comment]
#5024

**Comment by BialyADI** [comment]
Bump

**Comment by szapol** [comment]
ok so i've done some research and it seems blood frenzy atm looks like this:

-it gets applied whenever one of the bleeds (rend/dw) is applied and retains it's duration.

now this is what happens when we apply another bleed:

-reapply the same bleed (be it using rend again when the debuff is active on the target, refreshing rend's duration with mortal strike or dealing a subsequent crit so DW refreshes itself): the duration of BF doesn't get refreshed. 
now with BF not present, when you prolong rend's duration with MS, BF doesn't apply, if you refresh rend on an active rend however, BF gets applied again.

-applying a different bleed seems to be working fine. when you apply DW that goes off before rend, BF disappears along with rend. when you apply DW that outlasts rend, BF disappears along with DW.

so the problem seems to lay in refreshing bleeds. 4% dmg is pretty damn much so pls take a look at this issue

**Comment by gumby123** [comment]
@szapol I think you got it right. It would be nice if this got fixed, it's a pretty important RAID debuff.

**Comment by galiceko** [comment]
Sup,

@Jenovas, this bug is still here. It disappears and it comes back for like 5sec only on critical damage

**Comment by Goregrin** [comment]
Hey,
i hope this bug is being looked at. Its minor but its pretty noticable in the overall dps.
Thanks

**Comment by henkka90** [comment]
Bump still a problem in 2017 July

**Comment by Jenovas** [comment]
Fixed rev  5449
