### ISSUE TITLE
[PL][Quest] The Stagnant Oasis

### ISSUE THREAD

**Issue by vragni** [Atlantiss/BugTracker#5094]
Na mapie pokazoje ze jest complete ale nie da sie tego questa oddać
http://www.wowhead.com/quest=877/the-stagnant-oasis
![wowscrnshot_120215_155846](https://cloud.githubusercontent.com/assets/16046575/11534245/08e71c7e-990e-11e5-85ec-e48ac0a41c27.jpg)

**Comment by gsc89** [comment]
Can't complete this quest I have complete the objectives but Tonga Runetotem wont allow me to continue to complete it.

![image](https://user-images.githubusercontent.com/1032459/36974906-3e120990-2070-11e8-9b1e-a36930237189.png)

**Comment by MercuricUma** [comment]
![wowscrnshot_032518_073755](https://user-images.githubusercontent.com/35276089/37872075-8ee73310-2fff-11e8-9d98-ee278c02f1c5.jpg)
![wowscrnshot_032518_073728](https://user-images.githubusercontent.com/35276089/37872076-91179ce2-2fff-11e8-9a0f-04625d3ec416.jpg)


You can close this post because the quest is perfectly working. All you have to do is going into the Stagnant Oasis (inside that little lake) and right click the pressure (bubbles come out and it's right in the middle underwater). Once you click on it travel to Crossroads to deliver it
