### ISSUE TITLE
[Spell/ability] [Druid] Feral Charge (cat form)

### ISSUE THREAD

**Issue by phifedawg** [Atlantiss/BugTracker#5277]
I haven't seen this in here yet so i'll start the post myself.

As some of you might know the Feral Charge (cat form) doesn't get you behind your enemy, but in front of an enemy. This is somewhat problematic for pvp as well as for pve since you can be detected out of stealth way too early even before you have a chance to pounce.

http://wotlk.openwow.com/spell=49376

**Comment by Jenovas** [comment]
"As some of you might know the Feral Charge (cat form) doesn't get you behind your enemy, but in front of an enemy."

It gets you behind, but due to some bugs in maps the server sometimes says "You cant jump behind this target, there might be a hole there or you might fall under textures" when this happens the server tries to check if you can jump in front of the target if you can it makes you jump in front of the target. It's a bit buggy because of pathfinding but it's better than not being able to jump at all.

**Comment by phifedawg** [comment]
Alright then, If that's the case i'm fine with it at least working. Don't want you guys to break anything while trying to fix something that kind of works ;)

**Comment by Jenovas** [comment]
Someday we'll probably try to fix pathfinding, but that is a huge task and we dont have time now to do it.

**Comment by phifedawg** [comment]
Yeah i totally get it. Still, great job constantly fixing stuff and checking the tracker. Want me to leave the this open or close it for now? (since it's mainly a pathfinding issue and not a spell issue)

**Comment by Jenovas** [comment]
I'll close it.
Cheers.
