### ISSUE TITLE
[EN][Raid][Firelands][Spell][Summon Felguard]

### ISSUE THREAD

**Issue by mhong0429** [Atlantiss/BugTracker#5463]
In the newly opened firelands raid instance, the warlock demonology spec spell [Summon Felguard] does not work properly. I had no issue with the spell or the summoned pet in the beth' tilac encounter, but as soon as I moved to the fiery part of the map (with lava and such), my felguard began to take 25000 fire damage every second. After we finished raiding for the night, I went back to test all the other pets. This was done slightly past the entrance, where the lava particles are seen on the ground. None of the warlock pets took damage here except the felguard, which continued to take 25000 fire damage every second.

**Comment by fafal** [comment]
On Firelands Felguard dying from lava.
On Molten Front each pet but idk why

**Comment by mhong0429** [comment]
Turns out the felguard pet dies everywhere. I can't get it to be properly summoned since having visited FL

**Comment by Glare** [comment]
I thought it was a known issue and they will fix it before release ;d Well shit happens. You need to write a ticket because you can't fix it yourself.

From my experience, pets(not only demons, hunter pets also) get a permanent debuff if they die from lava in Firelands(don't know about MF). I personally "lost" my Imp, Felguard and Felhunter(well, he was lab pig) after Firelands journey ~2 weeks ago.

**Comment by Kaabum** [comment]
I got the same situation with my felhunter.

**Comment by Quban** [comment]
debuf is no longer permament after pet dies
