### ISSUE TITLE
[EN][Hunter] Negative Crit

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#5543]
So, for some reason hunters lose some amount of crit, you can test it by removing all the gear
saw it first on forum post http://i.imgur.com/j4G04EE.jpg ( -0.58% )
Then i tested it myself, i had -0.78 on one point (didn't take pic), but i tested it now again and i had -0.81% in survival spec (http://i.imgur.com/F8BHtDK.jpg) -0.89% in mm (http://i.imgur.com/p2h5TeB.jpg), and -0.89% w/o any spec chosen (http://i.imgur.com/Ytd0lT8.jpg)
I asked some other hunters ( Nedev -0.83% in bm -0.90%; Wankypanky -0.83%; Wulgarny -0.81%)

Hunter base crit rating should be 0% w/o any gear or buffs

**Comment by anxanas** [comment]
BUMP same thing with me

**Comment by anxanas** [comment]
It should be more than0% because of our base agility

**Comment by lqlq32** [comment]
For hunter 1 agility is 1/324.85 = 0.0031% crit or 0.552 crit rating and 179.28 crit rating is 1% crit.
I have 2235 crit rating which is 12.47% (tooltip from holding mouse over it is correct for that one) and 6096 agility which is 18.77% (tooltip says 17.23%). So my tottal crit chance is 30.7% (17.23 + 12.47% + 1% i am troll with bow) instead of 18.77% + 12.47% + 1% (racial) = 32.24%, i think the problem is coming from the agility.

**Comment by BialyADI** [comment]
why you have 10% haste ;o?

**Comment by lqlq32** [comment]
Survival talent

**Comment by lqlq32** [comment]
Ok this isnt a bug probaly i found this thread http://us.battle.net/wow/en/forum/topic/7200060373 its from MoP but i think nothing change about this before WoD, they have the same number - 1.53%.
