### ISSUE TITLE
[en][core] Total Honor / Conquest gained in season

### ISSUE THREAD

**Issue by blinkmaster** [Atlantiss/BugTracker#5578]
Under honor ( or conquest) currency in the vendor, you should see total season gained of that currency, on our server this is not implemented and we can't see how much we gained 

http://us.battle.net/wow/en/forum/topic/3123313891

**Comment by Sayris9876** [comment]
Also past few days i got pretty much most of the vicious (honor) gear and still i cannot buy vicious weapon because it says i didnt get enough honor this season. Total honor gained on this toon so far this season is more than 10 000. I dont know if its the same with ruthless (conquest) gear since so far i got only 1500 conquest.

**Comment by Bildo** [comment]
There is a visual that say you can't buy but you can.

**Comment by BAndysc** [comment]
Visual fixed in the next build
