### ISSUE TITLE
[PL][Quest][Molten Front] Fire in the Skies

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/BugTracker#5700]
http://www.wowhead.com/quest=29290/fire-in-the-skies
Spell Flame Seed powinien bić za 280k a bije znacznie mniej.
Flame Burst chyba nawet nie bije

Przez to ten q się robi z 2h

**Comment by HUMBOL** [comment]
Potwierdzam, Flame burst coś tam bije, ale też malutko

**Comment by Luna-maria** [comment]
I also want to add that if you (for whatever reason) get disconnected while doing this quest, be it a server crash or the players own connection failing, once you log back in, you fall out of the sky into the area with a bazillion mobs and well, death is imminent. There's also no way of getting out other than using your hearthstone (and i'm not even sure what happens if you actually die)

**Comment by Thefakemccoy** [comment]
Any one who hits the mobs should get credit for kill.


The most difficult part of this quest is the Molten Lords. First, unlike other mobs in the Molten Front the Molten Lords are taggable. So if the Molten Lord is grey you will not get credit if you kill it. Second, it usually takes more than one pass to kill a Molten Lord because they have so much HP. Third, all the Molten Lords are shared. So if it's busy you may fly around and around only to discover that all the Molten Lords are already tagged and you are just waiting for someone to kill them so they respawn.

The Molten Lords alone took me 20 minutes on this quest. My advice is to kill them even when they are grey. No, you won't get credit but it will make them spawn much faster. Otherwise, you could be flying for a long time.

edit

This has now been fixed as of July 12 patch notes.
Molten Lords no longer become tapped by the first player who attacks them with any of the Trained Fire Hawk's abilities while on the quest Fire in the Skies, allowing for any player who dealt damage to the Molten Lord to gain quest credit upon its death.
