### ISSUE TITLE
[EN][Item Set Bonus][Rogue T12]Burning wound

### ISSUE THREAD

**Issue by Evelinrose** [Atlantiss/BugTracker#5705]
Following rogue 2 set bonus http://www.wowhead.com/spell=99174/item-rogue-t12-2p-bonus damage from burning wound seems lower then it should be.Here is a ss of total melee dmg and one bellow is dmg of burning wound http://imgur.com/a/n3HcM
Total damage is 2 586 240 divided by 39% as total melee crit{since it will triger only from crits}we get that total dmg of crit is 1 008 633 and if we divide this number with 6 we should get total estimated dmg of 168 105 which is way lower then what ss shows{63 821}Likewise nothing should effect total dmg of burning wound such as attack power,str,agi etc. as it's totaly based off melee crits dmg.
Here is a video i found on youtube which shows nicely how much higher dmg should be{this video is from retail}https://www.youtube.com/watch?v=DaxHrV0lFZw
Pausing a video at 1:14 you can see that highest melee crit he did was 14 000 and after that burning wound hits for 3 452,i could never even come close to that on atlantiss with almost same crit.
It could be that there is something wrong with refreshing this as wowhead says it should work very similarly to fire mage ignite.

**Comment by anxanas** [comment]
I dont think it only procs from auto attack crits, it should proc from combo point generating abilities combo point consuming abilities aka all attacks. Should also benefit from 8% spell damage taken debuff.
http://www.wowhead.com/spell=99174/item-rogue-t12-2p-bonus#comment (proof of what iam saying is true look at first comment by Blutkrieg)

**Comment by tnarf** [comment]
How should works:
http://www.wowhead.com/spell=99174/item-rogue-t12-2p-bonus#comments:id=1473775

example from retail:
http://www.worldoflogs.com/reports/rt-4ch2g2a0chqqsj1c/details/101/?s=3899&e=4207
sum of all crits: 1938303
BW expected dmg: 116298 (1938303 * 0,06)
BW dmg: 112320 (3978 lower than expected, probably, because rounding down + last tick)
Here you can also see that individual crits were in smaller interval than 4s.

effects of little test (on atlantis):
1. BW is trgiered only by Auto-Atack's crits (BUGGED, skils should too)
2. BW dmg base only on LAST crit (BUGGED, every crit should make dmg)
3. Lower crit override bigger (BUG see 2.)

**Comment by vaseno1** [comment]
still not working.
