### ISSUE TITLE
[EN][Item] Jaws Of Defeat

### ISSUE THREAD

**Issue by Korrx** [Atlantiss/BugTracker#5745]
Recently acquired this trinket on my restoration druid and seems that it isn't working as intended. After doing some research i found out that the Buff "Victory" you get from using the trinket is broken. Once you cast spells the buff should give also give the buff "Victorious" from All holy/nature spells not just casted ones. So for example it gives a stack for casting Regrowth But not for instant casts like rejuvenation, but it should give stacks and decreased mana costs for both casted AND instant spells like rejuvenation and renew. But is currently only giving for casted spells rendering it almost useless.

Wowhead link for item: http://us.battle.net/wow/en/forum/topic/3393369999
The comments section also provides some basic insight into how the trinket should work. Thank you.

**Comment by Exertt** [comment]
YAY for 3 months of ignoring!

**Comment by Kaldros** [comment]
This is a pretty big issue. This trinket is supposed to be amazing on resto druids because of our instant cast hots, but it is actually terrible since only our direct heals cause us to gain stacks. Please fix this.

**Comment by Kaldros** [comment]
Bumping this because it's incredibly important for Resto Druids. Also providing some proof that it should give a stack each time you use any HoT as well as cast time spells.

**1.** The top comment on Wowhead JoD page clearly shows the "best possible scenario" for this trinket's usage and as such names a Resto Druid spamming **Rejuvenation** - the spell that this trinket currently does NOT build stacks with on Atlantiss. Now that comment was written during patch 4.0.6, but scroll down and you will find a very similar comment written during patch 4.2.0 when FL came out.
Link:
http://www.wowhead.com/item=68926/jaws-of-defeat#comments


**2.** While not stating the exact mechanics of JoD, this blog post refers to activating Tree of Life together with Jaws of Defeat for maximum efficiency of the trinket, stating: 

> Now, when you hit Tree of Life, you’re spamming all the things.  **Lifebloom** multiple targets, instant regrowth, etc. 

The source clearly states **Lifebloom** as a very good spell to get your JoD stacks going, yet Lifebloom is another spell that does NOT build stacks of JoD on Atlantiss. Note that the blog post was written on  October 17, 2011, during patch 4.2 (4.2 was released on June 28, 2011. as per http://us.battle.net/wow/en/game/patch-notes/4-2-0)
Link:
http://murlocparliament.com/2011/10/17/using-jaws-of-defeat-trinket-and-other-cooldowns-to-burst-heal-all-the-things/


**3.** Lastly, you can lookup this thread on official US WoW forums (also during patch 4.2). The OP asks what is the best way to use JoD as a Resto Druid for which he gets multiple answers along the lines of "Rejuv spam".
Poster "Bluebones":
> Spamming rejuv would build your stacks up the quickest and it makes a relatively cheap spell cheaper.

Poster "Almondmoocha":
> I'll give an example when I use Jaws. On first 7 stacks of H Domo - **spam RJ**

Among others.
Link:
http://us.battle.net/wow/en/forum/topic/3430940490

Please fix this trinket as soon as possible since in its current state it is awful and not even worth using for a Resto Druid.

**Comment by Jenovas** [comment]
Fixed in rev 5075
