### ISSUE TITLE
[PL][Quest][Hillsbrad Foothils][Heroes of the Horde!]

### ISSUE THREAD

**Issue by Perwalebka13** [Atlantiss/BugTracker#5757]
3 postaci tj, kapłanka, krasnolud i postać mająca plany bitwy się nie pojawiają. Quest tak jakby się nie zaczyna, Orkus nic nie mówi.
Link do questa: http://www.wowhead.com/quest=28400/heroes-of-the-horde

**Comment by Angelo-DM-** [comment]
Bugged Quest:
[Heroes of the Horde (ID:28400)](http://www.wowhead.com/quest=28400/heroes-of-the-horde)

Problem:
You can't do this quest becouse no one mob is spawned in order to complete the quest and loot the quest item.

Video: 
This [video](https://www.youtube.com/watch?v=3JqbRm4zmQM) show how the quest should work!

**Comment by Angelo-DM-** [comment]
#5786

**Comment by BAndysc** [comment]
W okolicy widzisz trupy worgenów czy żywe worgeny?

**Comment by Angelo-DM-** [comment]
There are dead worgens nearby... only the 4 mobs near the tower are missing!

**Comment by BAndysc** [comment]
Will be fixed in rev 4838
