### ISSUE TITLE
[EN][NPC][Molten Front]Obsidium Punisher(ID 52107)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#5817]
Obsidium punisher when reach around 80% of its life it start using its ability [Rage](http://www.wowhead.com/spell=98589/rage) all the time until it reach 6 stacks but it should use it every percent it lose from its overall life. 

Wowhead Link: [Obsidium Punisher](http://www.wowhead.com/npc=52107/obsidium-punisher)

**Comment by tnarf** [comment]
Now probably because rev 4828
They gain Rage stack very very slowly.
On "norma" fight they gain max 2 stack (for my mostly only one)
When kiting/bugging mmaps (there is many places where they can't enter) sometimes they gain 6stack (max?) and many times they stop gainig stack on 3 and 5min 5min buff run out.

In addition Rage doesn't reduce movement speed or reduce only little.

**Comment by Luna-maria** [comment]
also should be mine-able http://www.wowhead.com/npc=52107/obsidium-punisher#mining

**Comment by Bildo** [comment]
fixed
