### ISSUE TITLE
[EN][Quest][Darkshore][Beached Sea Turtle] [The Absent-Minded Prospector][Offering to Azshara]

### ISSUE THREAD

**Issue by macmas** [Atlantiss/BugTracker#6117]
This quests no working. ? for quest is absent

**Comment by Bastion** [comment]
wtf

**Comment by macmas** [comment]
http://www.wowhead.com/object=176196/beached-sea-turtle

**Comment by macmas** [comment]
this quest

**Comment by macmas** [comment]
http://www.wowhead.com/npc=34422/malfurion-stormrage this NPC not present on end quest The Offering to Azshara

**Comment by macmas** [comment]
Jr. Archaeologist Ferd no ending The Absent-Minded Prospector

**Comment by Aival94** [comment]
The Breached Sea Turtle has been removed on Cata.

For the [The Offering to Azshara](http://www.wowhead.com/quest=13900/the-offering-to-azshara) never had a problem to complete it. The event did not start at all?

About the [The Absent-Minded Prospector](http://www.wowhead.com/quest=13911/the-absent-minded-prospector) there is already a post here and a temporary way to fix the bug.

You can edit your first post instead of making so many comments and make it hard to read,

**Comment by macmas** [comment]
when I kill Azhara, Malfurion Stormrage not appear

**Comment by macmas** [comment]
thanks, yust working

**Comment by deplecak** [comment]
@macmas how you completed it, im trying right now and malfurion does not spawn,  there is question mark on my minimap so he should be there but he isnt.
![wowscrnshot_032116_074055](https://cloud.githubusercontent.com/assets/10629592/13912015/90a50538-ef38-11e5-87c0-3e36934cf97b.jpg)
