### ISSUE TITLE
[EN][ITEM] Guild Vault Voucher (7th Slot)

### ISSUE THREAD

**Issue by Hamanas** [Atlantiss/BugTracker#6120]
So I bought the item and I used it and we didn't get a 7th slot in our GB. Not only that but ONLY guild leaders are able to use that item. I would appreciate if any of you GM's could help us out by restoring the item for us or that you could add a 7th slot to our Guild Bank (Otherwise we wasted 10k hard earning gold for nothing). 
                                                                                                   - Murloq (Kung Fu Fighting)

**Comment by Aldergar** [comment]
You should read this:
GMs/Admins do not change the race/class/sex of a character, they do not change a nickname nor make character transfers, do not move/exchange/give items/gold, do not complete quests for any players (it can be done only in cases with no other way) and do not give back items/honor/ap/rating/gold etc lost because of dc/player's fault/technical problems/actions by a third party.

Only in some cases we consider giving back things, which have made a permanent track in the database and could not be deleted or given away in any way by the player (e.g. reputations, quest rewards (not daily). We do not consider item/gold/achievements.

**Comment by Hamanas** [comment]
Can I just say this again... "Not only that but ONLY guild leaders are able to use that item."
I'm considering it scripted improperly. Players (or Guild members) can buy that item and use it upon their will and yet, it'll consume it giving nothing but rather -- that player -- losing 10,000 gold basically for nothing. If you're not going to help us with our 7th slot then consider re-scripting the item to its proper command where a player (or Guild member) could not use it other than the Guild leader.

**Comment by Luna-maria** [comment]
even wowhead comments warn to not buy it if you're not the guild master

"Buyers beware! Only the guild leader is able to use this voucher, although anybody can purchase one."  
"Don't buy this if you're not the guild leader. It won't let you use it, regardless of permissions given to the guild rank you have. Further, it is soulbound when you buy it, so you can't transfer it to the guild leader."

on retail anyone can buy it but only the guild master can use it so I think you're out of luck :/
