### ISSUE TITLE
[EN] [Talent] [Rogue] Killing Spree not immune to CC

### ISSUE THREAD

**Issue by RhythmOfficial** [Atlantiss/BugTracker#6397]
Killing spree should be immune to Crowd Control effects.
It currently is not.

**Comment by BialyADI** [comment]
Why?

**Comment by RhythmOfficial** [comment]
Because that is how it worked on retail, they even recently patched it on live because it was being too OP.
Took them till 6.2 to remove this mechanic and you're asking why?
You aren't deluded are you?
@BialyADI

**Comment by Crusaderz** [comment]
Read bug reporting rules:
https://github.com/Atlantiss/BugTracker

**Comment by blinkmaster** [comment]
Proof

**Comment by RhythmOfficial** [comment]
http://eu.battle.net/wow/en/forum/topic/14369066951

**Comment by Bjarzyna** [comment]
Combat rogues also lack additional pvp utility because of this bug.
Because you're immune to CC while in killing spree you should be able to use it as a last resort movement spell when there is nothing around you. This means breaking out of slows and roots and (probably) running on slowing ground with full speed. This would also allow eating freezing traps and crossing ring of frost without harm.

**Comment by Jenovas** [comment]
Fixed in rev 5226
