### ISSUE TITLE
[EN][Quest][Teldrassil] Druid of the claw

### ISSUE THREAD

**Issue by Dean1989** [Atlantiss/BugTracker#643]
the doors don't open so you can't face rageclaw and is impossible to complete the quest.
http://www.wowhead.com/quest=2561

**Comment by Aival94** [comment]
This one can be updated to 4.3.4 milestone as still occur on the pre-patch period.

**Comment by reix2x** [comment]
The objective "Ravenclaw" is behind that door, hitting TAB you can spot him..

**Comment by Duros** [comment]
You can compleet is as a hunter. First hit TAB to target him, then send your pet on him, tag him and call your pet back. Than kill him and use the item.

**Comment by reix2x** [comment]
It's a good idea, but if you don't have a pet you can't complete the
quest.. to move the NPC its a simple solution

2015-01-15 18:38 GMT-04:30 Duros <notifications@github.com>:

**Comment by Dean1989** [comment]
i re-open this because is in the closed issues section and don't popup in the search results if someone is looking for it. 22/04/2015 the quest is still bugged (the door's won't open automatically).

**Comment by MirrorWraith** [comment]
please fix this quest ASAP, idk why this quest hadn't fixed yet since 2014 Dec, and it's still bugged now

**Comment by zwei7** [comment]
Now it is November, almost 1 year anniversary of this bug

**Comment by schwim0341** [comment]
Happy anniversary!

**Comment by zwei7** [comment]
Almost Dec 14. Then it is anniversary.

**Comment by TaleOf4Gamers** [comment]
8 days to go!
Happy Anniversary!

**Comment by karama300** [comment]
I am a little late but anyways: Happy B-day!

**Comment by Samineh** [comment]
:+1:

**Comment by karhima** [comment]
Still bugged. I start wondering what actually gets fixed.

**Comment by GamingAnonymous** [comment]
Trust me, I feel the same sometimes.
I feel there needs to be a "Quest fix week" to fix as many quests as possible because I have pretty much given us as too many (about 10 quests) had to be abandoned as were bugged and impossible to complete. This was fairly early on aswell (Around level 30-35) and with a single character.

**Comment by johnygl** [comment]
If you are dedicated to complete this quest and don't have pet to pull Rageclaw: pull 1-2 mobs nearby, let them kill you close to the door. As ghost run to your body and ressurect behind the door, kill Rageclaw and use the item. To exit the room let that one mob that is also inside kill you and once again as ghost respawn on the other side of the door or use hearstone and run to quest giver.

**Comment by Duros** [comment]
There is actually a way easier way. Which should not be abused. But if you stand in front of the door just log out and relog in. Why loading spam W, while loading you glitch through the door. Now you can easily kill the mob and HS out or just do the same thing again. This trick will not always work on first try because you need to get the timing right.
Good luck!

**Comment by TranceAccount** [comment]
Currently the doors are always open, which is good of course, but not blizzlike.
The doors should open once the players nears the doors.
https://youtu.be/ELIrIORH-Fg?t=25s
