### ISSUE TITLE
[EN][LFG] Dungeon Finder

### ISSUE THREAD

**Issue by SgtTR** [Atlantiss/BugTracker#6470]
When entering a random dungeon group players shouldn't be able to initiate vote kicks for the first 600 seconds unless the target is offline, and when there are 3 or less players offline people should be kickable.

**Comment by Fapguy** [comment]
I dont know if this is blizzlike or not, but it's not a good thing.
Imagine getting ZG/ZA and no one wants to do it, just wastes everyones time and is a bad idea.

**Comment by Aival94** [comment]
First of all if it can be fixed i would be fixed because devs try to keep server blizzlike even if blizzard made some mechanics being annoyed.

Secondly it should not wait 300sec(5 min) but after 15 min and when someone dc should wait 1 min until is available to be kicked.You might  want to make a comment here https://github.com/Atlantiss/BugTracker/issues/696 as well and hope that the poster will update it with recent only bugs.

Proof: [Vote Kick](http://wow.gamepedia.com/Vote_Kick)

**Comment by Aviannaqt** [comment]
Make a comment in #696
