### ISSUE TITLE
[EN][NPC] Vaelastrasz the Corrupt

### ISSUE THREAD

**Issue by Bjarzyna** [Atlantiss/BugTracker#6550]
Second boss of Blackwing Lair "Vaelastrasz the Corrupt" ( http://cata.openwow.com/npc=13020 ) cannot be completed (at least I wasn't able to, 3 times each time different raid week).
When talking to the boss valid responses are available, however after the conversation he won't turn hostile towards you and you can no longer interact with him.
Because of this issue all the bosses in BWL are unavailble atm.
Please note that this boss was working well about a month / month and a half ago. I believe he got bugged after some optimalisation changes.

**Comment by phantomgodx** [comment]
It worked yesterday for me now its bugged out again.

**Comment by Aival94** [comment]
Like someone said in a comment only leader can activate the boss.

**Comment by krelein** [comment]
This boss is bugged out again ;/. Now even leader can't activate the boss.

**Comment by Raffikossmann** [comment]
Vaelastrasz is bugged once more. I tried it 2 IDs in a row now and the fight cannot be started.

**Comment by emundans** [comment]
Trying to do the boss right now, and I am unable to initiate the fight. I am also raid lead.

**Comment by CrypticWizard** [comment]
Tried it as well some time ago. Only person in the raid instance and obviously raid leader. Fight could not be started and after it does not start, the raid ID is wasted.

Personally, I am curious though -- To anyone that has it fail, how did Razorgore go? For me Razorgore bugged out something fierce. Was doing just fine solo, had half the eggs done or so, switching back and forth out of controlling Razorgore and then, boom, suddenly he died. And not in the vanilla sense. Because in vanilla he could indeed be killed by the NPCs. But would then wipe the raid. This did not happen for me.

He died, the door to Vael opened and that was it.

See, I'm thinking that the Vael issue might actually be an entirely different issue. Something along the lines of the MC script bug ( https://github.com/Atlantiss/BugTracker/issues/581 ). That if Razorgore bugs out or is bugged out or simply dies in an unintended way that the raid ID from that point on is bugged.

**Comment by riffraffglobal** [comment]
The Razorgore fight was the exact same for me. He just died all of a sudden.

I already considered this to be the reason aswell. On the other hand, Vaelstrasz used to work just fine for me, even though the Razorgore fight wasn't working properly. Then, without any reason Vaelstrasz bugged out and I couldn't start the encounter anymore. The Razorgore fight didn't change tough.

This leads me to the concluison that the issue must be elsewhre.

**Comment by CrypticWizard** [comment]
I believe that the entirety of BWL is simply borderline close to not working at all. It's in a very fragile state on Atlantiss and could do with a lot of polishing.

"The raid stands upon the edge of a knife, stray but a little and it will fail... to the doom of us all." -- Shameless LOTR plug.

**Comment by Piklo** [comment]
should be fixed in [rev5800](https://atlantiss.eu/changelog#rev5800)
