### ISSUE TITLE
[EN][Quest]If you're not against us...

### ISSUE THREAD

**Issue by micha666** [Atlantiss/BugTracker#6599]
This quest isn't bugged but the npc is spawned multiple times. It can affect server performance in some way i think. It's not of the high priority of course.

NPC link:
http://www.wowhead.com/npc=39933/tyrus-blackhorn

**Comment by Aival94** [comment]
Is already reported here: https://github.com/Atlantiss/BugTracker/issues/3927

Furthermore because you might encounter this bug that the quest [Good News... and Bad News](http://www.wowhead.com/quest=29066/good-news-and-bad-news) is not being given you can make a ticket to ask to give it to you but is not giving you any problem doing rest of the zone.
