### ISSUE TITLE
[Pl][Nightelf][Racial]Shadowmeld

### ISSUE THREAD

**Issue by avalancze23** [Atlantiss/BugTracker#6792]
Shadowmeld nie zdejmuje combata

**Comment by Zhalox123** [comment]
Confirmed shadowmeld should remove combat when used.Used to work like this since vanilla you can easy proof this with videos of feral rouges and many other classes from retail like this.
https://www.youtube.com/watch?v=Av4tiXpZFWY

**Comment by MorbidMike** [comment]
The combat dropping function of Shadowmeld should work exactly like Vanish. You should only leave combat IF the mob is not in combat with any other player or NPC. Otherwise you should stay in combat.

http://us.battle.net/wow/en/forum/topic/2957536006#2

> The combat dropping effect was removed from it a very, very long time ago. It's now similar in function to Vanish, only without the threat reduction. I believe the change was made with patch 3.0.8, dated January 20th 2009 (so 2½ years ago).
> 
> That is to say if you're the last target the mob is "aware" of (or, through a concerted effort, all the remaining targets use their disappearance ability in tandem) than you will exit combat with the mob completely. Ed: ie If you are on your Hunter and pull an extra mob which doesn't see your pet than you can Shadowmeld it off. If you're attempting to lose a mob currently in combat with your pet, however, you must let the pet die first - then use Shadowmeld - otherwise you will remain in combat and be hunted down.
> 

Shadowmeld should allow the use of abilities that require stealth (this is currently bugged).

http://forums.elitistjerks.com/forums/topic/118015-cataclysm-subtlety-compendium/

> Night Elf
> 
> Previously one of the worst races for Sub, they are now very strong. With a slightly higher base agility, and the ability to Ambush out of Shadowmeld for added Find Weakness uptime, Night Elves are a very strong option when Shadowmeld can be reliably used.

**Comment by debtheone** [comment]
ofc it should drop combat https://www.youtube.com/watch?v=2QO22zFAalM&feature=youtu.be&t=210

**Comment by Jenovas** [comment]
Mister Zalox your comment has been removed. We do not care what you think about a Dev. Cheers :)

**Comment by MorbidMike** [comment]
debtheone, my post described how Shadowmeld should act in PvE, and in PvE it should only drop combat under certain circumstances (look to the post I quoted). If it follows the same rules in PvP as it should in PvE then naturally it will always drop combat, because there are no mobs to keep you in combat.

**Comment by debtheone** [comment]
wasn't referring to you :D

**Comment by Aviannaqt** [comment]
rev. 4932
