### ISSUE TITLE
[ENG][druid feral][Rip][Ferocious Bite] dmg reduction of Rip and strange dmg on Ferocious Bite

### ISSUE THREAD

**Issue by Raboou** [Atlantiss/BugTracker#6893]
Feral druid. about 1 week ago worked realy good but..
now:
on 5 combo points "Rip" hits 3k/6k crit.. was doing 6k/12k crit
on 5 combo points "Ferocious Bite" sometimes CRIT for 8k sometimes for 50k. (on full energy)

these statistics were taken from duels: Feral druid 374 ilvl against restoration shaman 361 ilvl -  3100 ressilience.

Please have a look if You can do anything with it because it makes no sense to play by feral druid anymore.

**Comment by kadi2** [comment]
http://atlantiss.eu/changelog#rev4932
About the rip and rake doing too much damage for 3 days last week. But how you managed to do 50k Ferobustion on mail user with a shield - no clue

**Comment by aneq** [comment]
Feral druid. about 1 week ago worked realy good but..
now:
on 5 combo points "Rip" hits 3k/6k crit.. was doing 6k/12k crit
on 5 combo points "Ferocious Bite" sometimes CRIT for 8k sometimes for 50k. (on full energy)

these statistics were taken from duels: Feral druid 374 ilvl against restoration shaman 361 ilvl - 3100 ressilience.

Please have a look if You can do anything with it because it makes no sense to play by feral druid anymore.
xDDDDDDDDDDDDDDDDDDDDD
one week ago feral druid had bugged double mastery
maybe you just suck

**Comment by Jenovas** [comment]
Please calculate the DMG and show the bug.
Closing.
