### ISSUE TITLE
[EN] [Talent][Mage] Living bomb re-applying and dots in general

### ISSUE THREAD

**Issue by flashxx** [Atlantiss/BugTracker#7090]
Hello,

In cataclysm, the way DoT abilities work was changed.
Credit to 0cto for the gamepedia source, used in explosive shot report:
http://wow.gamepedia.com/Previews_of_class_changes_in_Cataclysm
"All warlock damage-over-time (DoT) spells will benefit from crit and haste innately. Haste will no longer act to reduce the DoT's duration, but rather to add additional ticks. When reapplying a DoT, you can no longer "clip" the final tick. Instead, this will just add duration to the spell, similar to how Everlasting Affliction currently works."
"Preventing dot clipping is something we want to do in general. It obviously benefits Shadow priests just as much as warlocks."

I will give an example of how living bomb should work since it is a bit different to other DoT abilities due to its explosion damage at the end. When re-applying it just before its last tick, explosion damage should be triggered.

This example assumes the player has 0 haste: 
00:00  Apply Living bomb
00:10  Re-apply Living bomb, triggering it's explosion. The DoT is refreshed on the target with a new duration of 14 seconds.
00:24 Living bomb effect ends, triggering its explosion.

**Comment by anxanas** [comment]
Living bomb explosion damage shouldnt be triggered if it is reapplied before the duration ends, 
Proof from http://www.tauri-veins.com/fire-mage-wow-pve-dps-rotation-cooldowns-abilities
"Living Bomb gives you a lesser amount of overall damage but also has an instant cast. It should always be refreshed after it has exploded and worn off because the explosion deals more damage than a tick and it also damages nearby enemies."

"Apply/refresh Living Bomb (always let it explode before refreshing)."

And living bomb doesnt work like warlocks dots, dont use information about warlocks. Present proof that living bomb should work like you say, which you probably wont find, since its not supposed to work that way.

**Comment by Kaldros** [comment]
Every source I've looked at on Fire Mages suggested letting Living Bomb time out (thus exploding) before refreshing it.

Also, nowhere in your post do I see any proof that Living Bomb should work the way you are suggesting it should. You are pointing out the changes for Warlock and Priest DoTs but there is absolutely no connection to Living Bomb. Makes no sense.

Give us solid proof that Living Bomb should work the way you are suggesting it should.

**Comment by blinkmaster** [comment]
It should. On mop. Not a bug
