### ISSUE TITLE
[EN][Mining] Smelt Thorium(ID 16153)

### ISSUE THREAD

**Issue by Aival94** [Atlantiss/BugTracker#7122]
Spell on 4.2 changed and started to get learnt in 200 Skill level but seems that here is stay on previous way(230 skill level).

Wowhead Link: [Smelt Thorium](http://www.wowhead.com/spell=16153/smelt-thorium)

Here are all Mining Spells before Mop(i believe site have not updated generally to after Cata but either way i searched the history for the last updated one before Mop): [Mining Recipes](http://wow.gamepedia.com/index.php?title=Mining_recipes&oldid=2881406)

**Comment by Thefakemccoy** [comment]
I think its works like this. Like the wow head link you gave was to smelt thorium bars so to make the bars requires 230 from the trainer. 
(Note: Wowhead is more up to date and nothing with mining has changed since cata except for mining ore out of level and receiving the partial pieces that require 10 to make 1 ore.)

To start mining small thorium veins requires 200 skill. 

So you have to mines up to the skill before you can learn to smelt it.

**Comment by Aival94** [comment]
You can read it in many other comments but just linked the first one: [Wowhead Comments](http://www.wowhead.com/spell=16153/smelt-thorium#comments:id=1499345)

**Comment by Aival94** [comment]
Bump.

**Comment by Piklo** [comment]
posted fix on forum:
http://community.atlantiss.eu/index.php?/topic/13084-7122-smelt-thorium-required-skill-lvl/

**Comment by TranceAccount** [comment]
@Piklo ? Any news?

**Comment by TranceAccount** [comment]
Fix should be live.
