### ISSUE TITLE
[EN][Warlock] Soul Harvest - enchant and trinket procs

### ISSUE THREAD

**Issue by kadi2** [Atlantiss/BugTracker#7210]
Soul Harvest shouldn't proc trinkets and enchants, but it does on the server. Gonna edit this report with a proof very soon. I couldn't find other similar spells acting like this, but prolly this is core mechanic for all other healing spells with similar mechanic.

http://www.wowhead.com/spell=101976/soul-harvest

**Comment by Jenovas** [comment]
First find proof later create an issue.

""dealing damage or healing with spells"
"casting a spell"
soul harvest is spell and is also healing you
working as intended"

"Its supposed to be like that you are healing with those spells so you proc them with certain trinket procs cloak enchant and weapon enchant"

**Comment by kadi2** [comment]
ops

**Comment by texa69** [comment]
SOUL HARVEST SHOULD NOT PROC TRINKETS AND ENCHANTS BECAUSE IT'S A NON-COMBAT SPELL. YOU CAN'T USE IT WHILE IN COMBAT. So mr Jenovas. I think you are the one who needs to find true proofs...

**Comment by kadi2** [comment]
@texa69 I got a movie 3 days ago where it actually did proc Foul Gift and Power Torrent. The issue is invalid indeed.

**Comment by Jenovas** [comment]
@texa69 I got a movie 3 days ago where it actually did proc Foul Gift and Power Torrent in Dragon Soul instance. The issue is invalid indeed.

End of topic texa69. Next time spend atleast 5 minutes checking what you claim, this way you'll save time for everyone. And take a chill pill. Writing something in all caps doesnt make the statement true...
