### ISSUE TITLE
Netherwing

### ISSUE THREAD

**Issue by Yokah** [Atlantiss/BugTracker#7278]
I'm bugged in this quests, I completed the first wave of quest, I got 'neutral' reputation and it detects like enemies, I don't know why 
![screenshot_2275](https://cloud.githubusercontent.com/assets/18682893/14822958/f3896ab8-0bd0-11e6-9993-51ededac01f9.png)

**Comment by JamesSinger94** [comment]
Buddy I'd follow the below or they will close your ticket without fixing:

How to use?

On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].

Use the search engine to find out if a similar problem has been already reported. If so, check if it's already been fixed and waits for update.
Make sure, that what you report is actually a bug.
Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com
Write your tickets according to the format:
[EN][Quest][Zone] A Vision of the Past
[EN][NPC] Thoralius the Wise
[EN][Spell][Class] Frostfire Bolt
[PL][Talent][Class] Brain Freeze
[EN][Glyph][Class] Glyph of Frostfire Bolt
[EN][Npc][Drop] Thoralius the Wise
[EN][Web] Armory doesnt work
List of currently supported tags /wiki/List-of-supported-tags-in-issue

**Comment by Anhaeyn** [comment]
^ this 
And about the report - do you have flying with 280% speed? It's necessary, otherwise you won't be able to get rep with them.

**Comment by Aival94** [comment]
And sometimes it get bugged and you need to relog or fly away from the zone and come back to give you the buff.

**Comment by Yokah** [comment]
I did it, relog, waited 1 day, nothing.

**Comment by Anhaeyn** [comment]
Do you have flying 280% speed?

**Comment by Yokah** [comment]
Nop, slower.

**Comment by Anhaeyn** [comment]
Then you need 280%. Otherwise they will be hostile. Had the same problem with them long time ago.

**Comment by Yokah** [comment]
Bought 280% speed, and I can't tho..

**Comment by Anhaeyn** [comment]
After buying 280% speed relog and make sure again if you don't have "at war" with them.

**Comment by Yokah** [comment]
Wow bro, I love you! 
![screenshot_2289](https://cloud.githubusercontent.com/assets/18682893/14853918/d02a881e-0c8d-11e6-9ded-025976645031.png)

**Comment by Anhaeyn** [comment]
You're welcome :D
