### ISSUE TITLE
[QUEST] Strategic Cuts

### ISSUE THREAD

**Issue by Blightflocke** [Atlantiss/BugTracker#7279]
It's a quest in the Burning Steppes and all the targets can be killed with the quest item, except for Worgmistress Othana, who doesn't seem to react to said item whatsoever. Any help would be greatly appreciated.

Best regards,
Aeldric

**Comment by JamesSinger94** [comment]
Buddy I'd follow the below or they will close your ticket without fixing:

How to use?

On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].

Use the search engine to find out if a similar problem has been already reported. If so, check if it's already been fixed and waits for update.
Make sure, that what you report is actually a bug.
Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com
Write your tickets according to the format:
[EN][Quest][Zone] A Vision of the Past
[EN][NPC] Thoralius the Wise
[EN][Spell][Class] Frostfire Bolt
[PL][Talent][Class] Brain Freeze
[EN][Glyph][Class] Glyph of Frostfire Bolt
[EN][Npc][Drop] Thoralius the Wise
[EN][Web] Armory doesnt work
List of currently supported tags /wiki/List-of-supported-tags-in-issue

**Comment by Bildo** [comment]
bt rules
