### ISSUE TITLE
[PL][Rogue] Vanish

### ISSUE THREAD

**Issue by kevery123** [Atlantiss/BugTracker#7288]
Orb Maga nie działa tak jak powinien,  ponieważ każdy proc dmga wywala Rogue z vanisha, a po vanishu Rogue powinien mieć Buffa z vanisha który uniemożliwia wyjście z stealtha przez 3 sec a Orb instantowo zabiera tego buffa co skutkuje nie wejściem w stealtha.

**Comment by Jenovas** [comment]
I also noticed it's breaking Vanish effect, While doing some researches to prove otherwise, i found out it existed on retail as well. Just curious if they really didn't fix that in late patches, all the posts about this were made before 4.1.0 patch.
http://www.skill-capped.com/forums/showthread.php?9551-Fire-orb-breaking-vanish

**Comment by kevery123** [comment]
Ten bug był też na globie bo grałem na nim z parenascie lat i został naprawiony. Przeczytaj vanisha spella i orb spella . Nic tam nie pisze o takim czymś ze orb powinien wywalac z vanisha wiec juz z samego tego można wywnioskować ze coś jest nie tak.

**Comment by Jenovas** [comment]
Nie nie nie, Dowód albo nie ruszamy tego. Już miałem wielu "grałem na globie to wiem" i mieli racje w 1 przypadku na 10. To że ktoś grał na globie dawno temu nie jest dowodem na to że coś ma działać inaczej lub nie.
