### ISSUE TITLE
[PL][Raid][Firelands] Lord Rhyolith

### ISSUE THREAD

**Issue by Kozakko** [Atlantiss/BugTracker#7342]
Filmik ilustrujący działanie bosa z 07.07.2011
https://www.youtube.com/watch?v=mzSvmlvcS7w
Co jest źle?
1. Zaczynając od samego startu encountera. Lord pula się poprzez podejście do niego (co jest blizzlike) ale tak jakby "aggruje" się na pierwszą osobe która do niego podejdzie czyli rusza w jej stronę. W praktyce wygląda to tak że zamiast ruszać przed siebie poleci w tą stronę z której znajduje się osoba pulająca (podchodzisz od strony prawej nogi to poleci dokładnie w tą stronę, wektor ruchu ma kierunek osoba-startowa pozycja bosa) - Tutaj boss powinien zawsze niezależnie od miejsca pulnięcia iść przed siebie,
2. Zasięg pulania bosa jest stanowczo za mały. Na naszym serwerze encounter zaczyna się dopiero po przekroczeniu "środka platformy" podczas gdy na załączonym filmiku (32-35 s) widać wyraźnie że boss zaczyna swój marsz grubo przed przekroczeniem środka.
3. Sterowanie bosem- Tutaj już ciężko o jakiś konkretny dowód ale wg mnie promień skrętu lorda jest stanowczo za mały. Dodatkowo uważam że lord chodzi ciut za szybki. Sytuacja widoczna między 4.25 a 4.40. skończyła by się na naszym serwerze dośc nieprzyjemnym prysznicem z lawy 
4. Magma Flow - http://www.wowhead.com/spell=97225/magma-flow Tutaj największym problemem jest czas trwania linii. Z założenia powinna trwać przez 10 s (tutaj czas liczony jest od początku wylewania się do jej wybuchu) potem ślad powinien zniknąć w przeciągu 3 s. Na naszym serwerze lawa wylewa się, wybucha po czym zostawia ślad który nie znika dość szybko. Dodatkowo linia która zostaje po wybuchu zadaje dmg co znacznie utrudnia manewrowanie na platformie. Idea działania magma flow jest bardzo dobrze pokazana między 1.30-1.43 s ww filmiku. Dodatkowo częstotliwość pojawiania się magma flow jest stanowczo za duża, Kolejne pojawiają się jeszcze przed zniknięciem poprzednich. (Jak powinno to wyglądać widać między 5.50-6.00) Kolejnym bugiem związanym z tym spelem jest jego dmg. Powinien on zadawać 50 k fire dmg jjesli staniemy na jego drodze oraz 100k jeśli będziemy na nich stali w momencie wybuchu. Niestety u nas jeśli staniemy na drodze magma flow jest to niemalże pewna śmieć, tickuje po kilka razy na sekundę (http://imgur.com/a/4cREd) Dowód że nie tak to powinno działać możemy zaobserwować 5.29-5.32.
5. Spark of Rhyolith http://www.wowhead.com/npc=53211/spark-of-rhyolith
Tutaj zauważyłem mały bug aczkolwiek w wersji hc może okazać się dość uciążliwy. Sprki u nas od razu zaczynają bić aoe i agrują się na najblizszego gracza. Na filmiku instruktażowym widać doskonale spawn sparka między 2.05 a 2.15. 2.07-Sprark się pojawia 2.10-Spark zaczyna bić aoe i leći na osobę która jest 1 w threacie.
Najprawdopodobniej występuje więcej bugów ale z powodu zamiesznia spowodowanego ww.problemami nie byłem w stanie ich zanotować.
Edit: co to dmg- nie uwzględniłem wersji prenerf która dużo bardziej by pasowała do naszego serwera także sama ilość dmg powinna zostać sprawdzona.
6. Aktywacja wulkanów. Lord aktywuje często kilka razy ten sam wulkan co jest wg mnie bez sensu. Wydaje mi się że wtedy ten sam obiekt rozsiewa 2 rodzaje stacków (tak samo jakby istniał 2 wulkan znajdujący się w teksturze pierwszego). Skłonienie Bosa do rozdeptania wulkanu mimo podwójnej aktywacji zdejmuje mu 10 stacków armora (Jeśli jednak podwójna aktywacja powinna być dostępna to idąc konsekwentnie dany wulkan powinien zdejmować 20 stacków). Na żadnym znalezionym filmie nie znalazłem przypadku w którym widoczna by była podwójna aktywacja. 
W pkt 6 jest bardzo dużo wydaje mi się ponieważ na razie nikt z mojej gildi nie prowadzi logów i jedynym narzędziem którym mogłem się posłużyć w ocenie były skady członków raidu.

**Comment by sunshitwowsucks** [comment]
here is translation

Video illustrating the effect of barefoot 07.07.2011
https://www.youtube.com/watch?v=mzSvmlvcS7w
What is wrong?
1. Starting from the start an encounter. Lord pot through the approach to it (which is blizzlike) but as if "aggruje" to the first person who approached him that is moving toward her. In practice it so that instead of moving forward will fly in this site with which the person pulająca (you approach from the side of his right leg to fly precisely in this way, the motion vector is the direction of the person-starting position barefoot) - Here boss should always independently of space pulnięcia go ahead,
2. Range pulania boss is far too small. On our server encounter begins only after crossing the "center of the platform," while the accompanying cutscene (32-35 s) it is clear that the boss begins to march well before crossing center.
3. Control bosem- here already hard for some concrete evidence but by me turning radius Lord is far too small. In addition, I believe that the Lord comes a bit too fast. The situation appears between 4.25 and 4.40. He ended that on our server vaguely unpleasant shower of lava
4. Magma Flow - http://www.wowhead.com/spell=97225/magma-flow Here the biggest problem is the duration of the line. The assumption should last for 10 seconds (here, the time is counted from the start of pouring to its explosion) then the track should disappear within 3 seconds. On our server poured lava, exploding and then leaves a trace that does not go away fairly quickly. In addition, a line that is after the explosion inflicts damage which makes it difficult to maneuver on the platform. The idea of ​​magma flow is very well shown between 1.30-1.43 s above video. In addition, the frequency of the appearance of magma flow is far too large, next they appear before disappearing past. (How it should look like can be seen between 5.50-6.00) Another bug related to this SPEL is its damage. It should ask 50 k fire damage jIf stand in his way and 100k if we are to have stood in the outbreak. Unfortunately, in us if we become in the way magma flow is almost certain trash, tickuje several times per second (http://imgur.com/a/4cREd) Proof that not so it should work, we can see 5.29-5.32.
5. Spark of Rhyolith http://www.wowhead.com/npc=53211/spark-of-rhyolith
Here, however, I noticed a small bug in version hc can be quite disruptive. Sprki with us immediately they begin to beat AoE and agrują the nearest player. You can see in the video instructional perfectly spawn Spark between 2.05 and 2.15. 2.07-Sprark appears 2.10-Spark starts to beat AoE and summer on a person who is 1 in Three.
Most likely there are more bugs but because of zamiesznia caused ww.problemami I was unable to write down.
Edit: what dmg- not allow for one version prenerf that much more to fit into our server, the same amount of damage should be checked.
6. Activation volcanoes. Lord activates often several times the same volcano that is according to me makes no sense. It seems to me that if the same object scatters 2 types of stacks (just as if there were two volcano located in the first texture). Bosa trick to being crushed volcanic despite dual activation removes him 10 stacks Armor (However, if you double activation should be available is consistently going the volcano should remove 20 stacks). At the found any film I have not found a case in which she was seen by a double activation.
In paragraph 6 it is very much think so because if one of my guild does not carry logs and the only tool that could be used in the evaluation were cascade members of the raid.

**Comment by Kozakko** [comment]
Rhyolith rev 4996
1. Bos pula się już z odpowiedniej odległości ale ciągle nie idzie przed siebie na pulu, skręca lekko w swoją lewą stronę.
2. Sterowanie też ciągle kuleje, Wg mojej skromnej opinii promień skrętu jest jeszcze trochę za duży.
3. Magma Flow, huh tutaj dużo się nie zmieniło ciągle linie lavy nie znikają po 2 wybuchu i zadają dmg mimo że nie powinno ich już tam być, Kilkakrotne uderzenia w tej samej sekundzie zostało wyeliminowane. Co do multi molten flow ciężko się wypowiedzieć bo z powodu nie znikania linii lavy ciężko zaobserwować kiedy do końca poprzedni się wylał a kiedy pojawia się nowy.
4. Sparki- atak instant po spawnie, nic się nie zmieniło.
5. Multi wulkany ciągle się zdarzają,

**Comment by Wolffenstein** [comment]
5. http://atlantiss.eu/changelog#rev4997

**Comment by Wolffenstein** [comment]
Please test rev 5001.
