### ISSUE TITLE
[Eng][Priest][Atonement]

### ISSUE THREAD

**Issue by linesar** [Atlantiss/BugTracker#7404]
I decided to test the new fixes to Atonement today in a quick Heroic and it works the same way as before now, before the old changes. 
The actual heal from Atonement can now crit. So the Smite itself does not have to be a crit for Aegis to proc. You can also get double crits from Atonement if Smite crits, then the heal itself can crit on the Smite, which ends up with numbers above 50k. I saw some numbers today between 70k and 90k with Atonement. Fully raid buffed Atonement Priest (depending on trinkets) can get healing crits probably around 100k now.
It is only the damage spell from Atonement that should be able to crit not the heal, but when the damage from either Smite or Holy Fire crits it should proc Aegis.

**Comment by Kozakko** [comment]
Well here we have WoL from retail http://www.worldoflogs.com/reports/gszovbyi4cxemu2p/details/9/?s=11292&e=11584 and there are crits from Atonement

**Comment by linesar** [comment]
yeah, but it probably counts as a crit (since it procs aegis) when smite is a crit.

**Comment by linesar** [comment]
that WoL is also very wierd, since it says that his average crit heals are 3593.2. It seems like every atonement from him counts as a crit, since all his Atonements counts as crits.

**Comment by kadi2** [comment]
does it mean you just have to make it to crit for 100% instead 200%?

**Comment by linesar** [comment]
If you don't count talents like Archangel and Grace, the healing should never be higher than *1.06 than the smite (due to 6% healing increase from talent)

**Comment by Bakkuren** [comment]
Hello there. 

I have fully atonement priest @ 376 ilvl with 4set and really good gear atm on our Atlantiss server. I need to admit that Atonement does not crit itself, only Smite critical strikes gives us additional shield from it, which is correct. What more, my friend, Discipline Priest does use grace effect, archangel and evangelism, if he does place grace effect 3x, archangel and stack 5x evangelism his smite/atonement heals are increased on a target by huge amounts. 

There is another thing to consider. What RHC was it u were making? Who was tanking it? DK? Druid? Both of those classes have skills to increase healing on them a lot, as any tank in game I would say so.

Atonement healing got recently playable, it is not as overpower as you say, it does not crit for 100k heals. As a pure fact for it I did FL10 last night and had no such a heal, except for Baleroc fight where your heals are insanely increased due to buff you stack up. 

I would like to tell this - right now it works around FINE and having high lvl discipline priest made me realize that this is not a joke. Still, in any situations atonement healing is never enough and while raiding you need to do a lot more than that or people will die. 

Cheers.

**Comment by Jenovas** [comment]
Fixed in rev rev. 5008
Atonement can no longer crit, but if Smite was a crit Divine Aegis will still proc

**Comment by linesar** [comment]
I have no clue why, but I couldn't get DMC: Volcano to proc, but that is another 1600 Intellect. You can see my procs on the side, Power torrent and Lightweave from tailoring, I also used Archangel now on some screenshots.

http://imgur.com/a/o1Ese

@Bakkuren I know that Disc use Archangel and Grace, I play Disc myself, the healing would become even higher if i counted those two in. If I would consider few more buffs like 8% spell damage taken and 3% increased damage, on a 61k crit those would become almost 68k. Give a proc from Volcano (Darkmoon Card) with 1600 Intellect on this and you are up to somewhere between 75-80k (maybe even more) and on some random char that has increased healing received, you are very close to 100k.

**Comment by Bakkuren** [comment]
I play Disci priest as well. My highest heals with Atonement are about 30-40k during full burst phase with full buffs, where I see my smite hitting for 30-35k with crit. I always found it quite normal becase this is how it should work, never noticed any atonement crit, only Smite. Well but there was a bug like that, let it be.

**Comment by linesar** [comment]
@bakkuren did u even check my screenshots?  If not, plz do.
