### ISSUE TITLE
[EN][Core]Tol Barad - unbalanced faction numbers

### ISSUE THREAD

**Issue by madcozbad** [Atlantiss/BugTracker#7453]
Like in other battlegrounds the numbers of players of each faction should be about the same. The faction with more players in the battleground should not get any more invites until the faction with fewer players within the battleground catches up. This does not work here, every day the horde outnumbers the alliance players at least 2 to 1. I checked [ /who tol barad ] at alliance and horde side and the difference is huge.

This issue causes the faction with less players loses all of the time. Since its easy honor for horde and getting camped all day for alliance, the difference of players grows bigger every day.

**Comment by Aival94** [comment]
Related bug: https://github.com/Atlantiss/BugTracker/issues/6001

**Comment by karolnpc** [comment]
Turn off this or fix it pls, its unplayable

**Comment by Aival94** [comment]
The one that made the post make it a proper bug report using the rules here: https://github.com/Atlantiss/BugTracker/blob/master/README.md

About how Tol barad queue System should work:
Tol Barad should have 2 population limits. One is 25 and other 80 in each faction.
The first limit is in the beginning and the System just bring anyone from one faction till this faction reach 25 people and after it stop getting more. This means the first limit can make a Told barad with 5 on one Faction and 25 on the faction for example.(which means in the beginning can be imbalanced.)

After both factions reaches 25 ppls each inside Tol Barad system should start leting more to enter Tol barad in 1:1 ratio with the limit in each faction of 80 people.

i believe blizzard instead of checking every time how many ppls where in one faction to let one more enter tol barad to the other faction they let a small imbalance limit of 5 ppls so one faction could have max 5 more ppls than the other but no more(so the system let max 5 ppls to join each time till the other faction get some more to be near the 1:1 ratio).

Right now seems the system let a bigger gap between each faction(can be 30 vs 60) or is just checking only who is queued for Tol barad in total without checking if they have entered or not and only keep the 80 limit per faction(without being sure if it keep this limit).

**Comment by Aival94** [comment]
As far the system work correct during the first cap(25 per faction which can be unbalanced) and the second cap cannot be overcapped(80 per faction) this one can be closed i believe as Wolfenstein fixed it and did some tests in Main realm and it work correct.

The new System might have helped fixing this issues as well: https://github.com/Atlantiss/BugTracker/issues/5977, https://github.com/Atlantiss/BugTracker/issues/5774, https://github.com/Atlantiss/BugTracker/issues/4634, https://github.com/Atlantiss/BugTracker/issues/3620
