### ISSUE TITLE
Frost Orb bugged on Vanish

### ISSUE THREAD

**Issue by jangsna** [Atlantiss/BugTracker#7455]
The Frost Orb hit Rogue during Vanish and it shouldnt.

**Comment by Jenovas** [comment]
I also noticed it's breaking Vanish effect, While doing some researches to prove otherwise, i found out it existed on retail as well. Just curious if they really didn't fix that in late patches, all the posts about this were made before 4.1.0 patch.
http://www.skill-capped.com/forums/showthread.php?9551-Fire-orb-breaking-vanish
