### ISSUE TITLE
[Raid - TBC][NPC] Black Temple - Illidan Stormrage

### ISSUE THREAD

**Issue by dwarfedt** [Atlantiss/BugTracker#7549]
When fighting Illidan, he spawns small tentacle creatures periodically. I don't know what the adds are called, but they look like shadowfiends, the priest spell. **The creatures that he spawn drop framerates to nothing and freeze computers.**

In this video, they don't spawn at all: https://www.youtube.com/watch?v=qrA3OZyy7VU

**Comment by Aival94** [comment]
I believe is reported here: https://github.com/Atlantiss/BugTracker/issues/1881

And generally encounter with event need probably a recheck and some kind of rescryption as the encounter is not like it should be.

How it should be: https://www.youtube.com/watch?v=k8_JbDiALkY (I believe is better to find a group fight than solo as many solo fights because of the huge dps they somehow "skip" abilities.)

Wowhead Link: [Illidan Stormrage](http://www.wowhead.com/npc=22917/illidan-stormrage)
