### ISSUE TITLE
[En][Guild Ranks]Guild ranks keep resetting

### ISSUE THREAD

**Issue by Tigerief** [Atlantiss/BugTracker#7575]
It started last night after the crash. All my guild ranks and permissions have been reset to the original 5 ranks the guild starts with. I changed it back to how it was this morning and now it reset AGAIN this is a really annoying problem for me as the GM to configure

**Comment by Aival94** [comment]
Reported/Related: https://github.com/Atlantiss/BugTracker/issues/2210

**Comment by Tigerief** [comment]
I dont see how to fix it, and it keeps re resetting, my guild has no bank access, cant set events for raids  or anything, its not the roster but the ranks that are the problem. im not sure if its JUST my guild now but i really need a GM to help me with this. it is the guild: Dungeon Siege

**Comment by Lertriency** [comment]
Based on previous experiences with the current guild I'm in who have had the same problem, the issue seems to arise when you have more than 10 ranks created. Ever since we started not going over that 10 rank amount the ranks have never reset on us since.

Albeit this workaround, it would be nice if eventually it would prevent you from creating more ranks and going over this 'cap' (if there even is a cap, after a brief google search I can't find anything on it).

**Comment by Tigerief** [comment]
You cant make more than 10 ranks in a guild, its a blizzard implemented cap. But we only had 9 ranks so i dont see the cause, otherwise your explanation would have explained it

**Comment by Aival94** [comment]
@Lertriency my guild have 10 ranks and it does not happen on last crash. Is just random and can only occur when the Guild Master is online.

@Tigerief If you are ranks keep reseting every time you will need a GM to do sth or even a Dev to check the Database. If they stop reseting just remake the previous Ranks like they were(name and order) and everything should be fine as far as i have seen in my experience.
