### ISSUE TITLE
[EN][Mage][Power]

### ISSUE THREAD

**Issue by AgenorZ** [Atlantiss/BugTracker#7580]
Hello cordial greetings to the development team atlantiss.

Hi I have some time playing on the server and there is something that bothers me about mages is their power that magicians are a class full dps but here wizards are very broken and at a low level object make a very strong damage.

While other classes like Death Knight and Druid (Balance) do a very minimal damage compared to the magician

Please ask them to balance the power of that class

**Comment by linesar** [comment]
What is the bug?

**Comment by MangeNerfedOwl** [comment]
1. Describe the bug. Its not retail forum where you can ask for nerfs because you think something is op. Here you just report bugs. If mages damage works fine - you shouldnt make a topic. If something is wrong with them - prove it.
2. I play balance druid and when mage's cc is gone and its all about dps race i win with huge advantage so idk whats your problem. DK low dmg? Was he naked? DK should obliterate mages without using even all cds.
