### ISSUE TITLE
[EN][class][hunter][pet]

### ISSUE THREAD

**Issue by adorcik** [Atlantiss/BugTracker#7589]
there is no much of a explaning - if you send your pet to kill  the target even if u use skills like http://www.wowhead.com/spell=34026/kill-command u wont achieve any experience points for killing that MOB it wont even shows loot i didnt tried it on quest MOBS when u need to slain them but i will  and will se if it counts them to my quests and will wrote that in comment to

**Comment by Luna-maria** [comment]
you need 51% of the damage done to get credit/loot/stuff. Haven't seen it work any other way on private servers sadly

**Comment by adorcik** [comment]
well i dont compare it to privs if its blizzlike we should compare it to th e global at this patch.
if its intentional than fine

**Comment by dawnhunt** [comment]
This is intentional. Pet damage is considered passive damage, which does not "tag" a mob so to speak. You HAVE to do damage to the mob yourself to get credit, even just 1 damage. As long as you damage mob, and pet kills it counts, but if you don't touch the mob yourself and pet kills, it doesn't count. Same thing for lock pets, mages pets, etc.

**Comment by TranceAccount** [comment]
What @dawnhunt said. If you don't agree with this, please open another issue with proof.
