### ISSUE TITLE
[EN][Hunter] Deterrence vs. Pounce

### ISSUE THREAD

**Issue by xolon** [Atlantiss/BugTracker#7629]
[Pounce](http://cata.openwow.com/spell=9005) can go thru [deterrence](www.wowhead.com/spell=19263/deterrence) which should not happen. Deterrance should deflect every abilitie.

**Comment by TranceAccount** [comment]
Please provide WoWhead links to the spells.

**Comment by kadi2** [comment]
Didn't try to reproduce it, but sounds like not all "Openers" spells have been fixed since wotlk.

Cataclysm Patch 4.0.6 (2011-02-08): Now provides 100% chance for melee attacks to miss instead of 100% parry chance. This means that attacks that cannot be parried, notably some rogue abilities, can now be prevented by Deterrence, and the hunter will gain the benefit of Deterrence even if disarmed.
