### ISSUE TITLE
[EN][Spell][Paladin] Word of Glory 

### ISSUE THREAD

**Issue by nikolaylen** [Atlantiss/BugTracker#7645]
http://cata.openwow.com/spell=85673

Word of Glory as a 84 Holy Paladin (item level 325) says I should heal for around 4,6k per charge of Holy Power. Though I heal around 3,4k which is too low. In addition when I change to strength items (still holy paladin) I heal for 4,1k heal... Obviously scaling with spell power/intelect as a holy paladin doesn't work with this spell only.

Screenshot 1 (with intellect items) http://www.img-share.eu/f/images/228/Screen-Shot-2016-06-16-at-00734S0na9jd_sredna.png
Screenshot 2 (with strength items, as you can see the spell power is significantly lower (47 times)) http://www.img-share.eu/f/images/228/Screen-Shot-2016-06-16-at-00754eHQFbAJ_sredna.png

P.S. My Light of Dawn heals the same amount (even a little more - 3,8k) per charge than Word of Glory...
Screenshot 3 (with intellect items - Light of Dawn - normal healing) http://www.img-share.eu/f/images/228/Screen-Shot-2016-06-16-at-0083748IR0gR_sredna.png

**Comment by Jenovas** [comment]
After doing the calculations the healing with spellpower seems ok.
Please remember that Word Of Glory scales with AP also.
If you think that it scales too much with AP please do the calculations and report it.
Closing.

**Comment by nikolaylen** [comment]
It scales with attack power if you are retri or protection paladin. It should not do that while holy. Holy paladin's spells scale only with intellect. It is not normal do to more healing with strength items. Also this is the case ONLY with this spell, not the others as mention. The spell is definitely bugged. Please fix it. What big prove you need than that that HOLY paladin yes more healing with STRENGTH items with ONLY 1 spell, not all.....

**Comment by Jenovas** [comment]
"it does indead benefit from AP it will scale with either AP or SP depending on which is higher at the moment" - at the moment of the test you had more AP than SP so it should and it will scale with AP.

> What big prove you need
How about trying to calculate it and read about it instead of reporting something you have no idea about? That would be a good start.

**Comment by nikolaylen** [comment]
Good, then this should be the case with other spells, too, right? Why does it apply then only to WoG, not to all Holy Paladin spells/heals (the AP/SP priority)?

**Comment by Jenovas** [comment]
Because I said so...
EoT.

PS - Look at other issues that show DMG / Heal is bad.
PS2 - I'll make it easier for you check the links:
https://github.com/Atlantiss/BugTracker/issues/5659
https://github.com/Atlantiss/BugTracker/issues/1773
https://github.com/Atlantiss/BugTracker/issues/6903
https://github.com/Atlantiss/BugTracker/issues/6297
https://github.com/Atlantiss/BugTracker/issues/6893
https://github.com/Atlantiss/BugTracker/issues/3577
https://github.com/Atlantiss/BugTracker/issues/3190

All these topics either hace calculations either got closed because there were no calculations.
Next time before leaving a comment atleast check if what you are writing is true and stop wasting our time.

Cheers :)

**Comment by nikolaylen** [comment]
Well, I can't find anywhere what is the formula for cataclysm to calculate it, but i am pretty sure, that Word of Glory should heal 3,5 times the amount of Light of Dawn. Right now the second heals even more and heals multiple targets, which makes Word of Glory useless... which is not normal... Also Holy paladin does NOT benefit from AP. Give me a link to cataclysm info of Word of Glory (holy spec)....

So without numbers (Because I can't find any formula on the net for cataclysm), WoG should heal 4,6k in my case, it heals 3,4k... which is 25% less roughly.

**Comment by Jenovas** [comment]
I said EoT. Yes youare wasting my time by creating issues like this one and all your proof is "I think", "I'm pretty sure" "I played on retail so I know". This makes me waste my time by searching for the formulas, testing in-game of the bug really exists and only after all that research I can start fixing. I'm not gonna do the research for you. Either you find the proof or nothing will change, simple as that.
