### ISSUE TITLE
[PL] [Raid] Firelands 10 - Alyslazora

### ISSUE THREAD

**Issue by Respect69** [Atlantiss/BugTracker#7675]
Po ostatnim uptadzie coś się zepsuło z nabijaniem agro w momencie, gdy Alyslazora wstaje. Agro nabite przez maga podczas fazy leżącej, tj. combu+ hero itp. jest później nie do przebicia, a taunty nic nie dają, ponieważ po 2 sec boss znów wraca na maga. Iceblock nic nie daje, mimo tego, że boss powinien obrać inny target po jako odpaleniu.

**Comment by Kozakko** [comment]
polecam invi

**Comment by Respect69** [comment]
Zanim invi zadziała, to już wszyscy nie żyją :D A całe agro po chwili i tak wraca na maga :s

**Comment by Aival94** [comment]
After a mage take 24 stacks get a huge increase to Critical as well and a good mage using TW and Combustion will do around 120k-150k DPS because of this boost. A normal tanking way will not let you keep the boss on you with such dps so you should just use all aggro and dps cooldowns to keep boss on you. Is sth normal i believe except if there is a problem with combustion and the stacks of Alysrazor but i think it worked like that in blizzard.

**Comment by Kozakko** [comment]
HoP/invi on mage and problem solved
