### ISSUE TITLE
cant revive from spirit world

### ISSUE THREAD

**Issue by immakoo** [Atlantiss/BugTracker#7805]
sometimes when i die and cant enter the dungeon or dc then i get teleported to dalaran in siprit form and have to rez using the spirit healer and take rez sickness and then instead of being rezzed in dalaran where i am, i get rezzed back to the dungeon i was at

**Comment by Aival94** [comment]
Use the Bugtracker rules to make a report: [Bugtracker Rules](https://github.com/Atlantiss/BugTracker/blob/master/README.md)

As far as i understand is a core issue which happen when you are in a dungeon/raid and your group has been disband(you are no longer in a group either because the dc disband the group or some of your party members logged faster and left party). 
Usually for me when this happen i go to my Hearthstone location but alive so not sure how you go to ghost form. Are you sure you were normally dead or have combat during the dc. If yes then i suppose that is the reason.

Next time try to use the unstuck button and it might help.

**Comment by sunshitwowsucks** [comment]
blizzlike
