### ISSUE TITLE
 [EN][Quest][Badlands] To Fuselight Proper

### ISSUE THREAD

**Issue by aendry** [Atlantiss/BugTracker#7851]
The teleporter doesn't work. and you can't be teleported up mountain. the rocket that brings me to fuselight bay killed me too. I had to travel all the way to the dead body

**Comment by TranceAccount** [comment]
Please provide WoWhead links to the Quest and Gameobject.

**Comment by arndry** [comment]
@TranceAccount IDK the name or the ID of the rocket but here is the [video of the mission](https://www.youtube.com/watch?v=_CcMw5Sl0e0). In our server the rocket waypoint or travel is not the proper one (rides you trhu the mountains instead of taking you above them) when I arrive it kills me. Then whe I reach my corpse to revive had to take a teleporter ([the broken teleporter that i'm talking about](http://www.wowhead.com/quest=27763/to-fuselight-proper)) in the previous link you can see all the info need it with pictures and videos
