### ISSUE TITLE
[EN][Quest][Gnomeregan] The G-Team

### ISSUE THREAD

**Issue by arndry** [Atlantiss/BugTracker#7951]
the [mission](http://www.wowhead.com/quest=26939/the-g-team) can be done but you can't deliver it. there is a missing [NPC](http://www.wowhead.com/npc=44560/b-e-barechus)

**Comment by Snake90** [comment]
More details :

The NPC [Murd Doc] gives the quest [The G-Team] (http://www.wowhead.com/quest=26939/the-g-team) at the beginning of the dungeon and the quest can be [completed. 
 
But it's impossible to deliver it because the NPC [B.E Barechus](http://www.wowhead.com/npc=44560/b-e-barechus) is not here. 

So all quests that result from this one are blocked : 
-- http://www.wowhead.com/quest=26941/the-g-team
-- http://www.wowhead.com/quest=26942/the-g-team

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/1611
