### ISSUE TITLE
[EN][Talent][Mage] Ignite

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8161]
![wowscrnshot_082516_220233](https://cloud.githubusercontent.com/assets/20555745/18223466/5cc81c48-71b8-11e6-8ac3-d36ee28e9e09.jpg)
i dont get this screenshot

ignite dissipates
fireball crit (29002)
fireball crit (29006)
ignite tick (7778)
fireball hit (13973)
ignite tick (10371)

how is ignite changing its tick value without a crit happening in between the ticks.
even if we assume the 2nd fireball crit to happen the same time as ignite ticks, the ignite tick thereafter makes no sense

(7778*2)/29002=0.5363768 (this is how much mastery i must have in case option 1/2 are correct)

option 1: ignite ticked at the same time as a crit happened and thus the new crit is added to the remaning ignite bank resulting in 3 ticks of ignite
1st ignite remaining + 2nd ignite = new ignite/3
7778 + (0.5363768*29006) = 23336.14546/3 = 7778.7151 per tick ignite

option2: ignite ticked at the same time as a crit happened and thus the new crit is added to the remaning ignite bank but randomly ignite is still only 4 seconds long
1st ignite remaining + 2nd ignite = new ignite/2
7778 + (0.5363768*29006) = 23336.14546/2 = 11668.0727 per tick ignite

option3: 1st ignite is munched and only 2nd crit forms the ignite
2nd ignite alone = newignite/2
if it was the new ignite alone then why is it changing its value without a crit happening

none of these options is correct because the ignite tick value changed from 7778 to 10371

**Comment by kadi2** [comment]
it could always be
Firball crit
ignite tick
ignite refresh
it could be still possible if everything happened in very short period of time.

**Comment by kadi2** [comment]
Everything works fine. there is just delay between crit occuring and applying the ignite.
7778/5800.4-1 = 34.0942004% The % you are getting from mastery or other debuffs on the target. but you don't need these numbers to understand the problem.

Then ignite bank didn't change since the first ignite tick occured between second ignite hit and ignite refresh. so

29002+29006=58008 -- the new ignite bank

(29002+29006)*0.4/3*1.340942004  = 10371.3818357  the tick we gonna get.
https://www.google.pl/search?q=29002*.2&oq=29002*.2&aqs=chrome..69i57.2400j0j9&sourceid=chrome&ie=UTF-8#q=(29002%2B29006)*0.4%2F3*1.340942004


This is just a perfect example of positive ignite munching that occured on your screen. If you are not sure what does it mean. Just look at this picture:
https://github.com/Atlantiss/BugTracker/issues/5539#issuecomment-173502900

**Comment by lamaATS** [comment]
I asked @fluessig for the mastery and he told me that he had 34,1%.

First `Fireball` crit generated `Ignite` with ticks for 7778 because `29002 * 0.4 * 1.341 / 2 = 7778.3364`
When second `Fireball` critted generated `Ignite` with ticks for 10371 because bank is equal to `29006 * 0.4 * 1.341 = 15558.8184` and remaining bonus which is equal to `7778  * 2 = 15556` so total amount of bank is 31114.818 and tick is `31114.818 / 3 = 10371.6061333`.

@kadi2 described the same thing above so `positive ignite munching` is the reason of that.
