### ISSUE TITLE
[EN][TALENT] Summon Gargoyle

### ISSUE THREAD

**Issue by aneq** [Atlantiss/BugTracker#825]
Like most guardians, death knight's gargoyle should snapshot his owner's stats during the summon and scale with those. Right now garg scales in real time.

**Comment by Pilarka** [comment]
Please Fix it i checked it today and still not working.

**Comment by Kejmil** [comment]
Gargoyle don't have his gcd while he should in this expansion, due to this regardless of haste rating he should be able only to cast max 16 strikes and start 17 but not finish it. On our server gargoyle don't have this gcd, so for example on sinestra gargoyle is wrecking havoc.

http://us.battle.net/wow/en/forum/topic/3881708498
http://wowwiki.wikia.com/Summon_Gargoyle (5.3 patch removes this gcd, sorry for wowwiki but on wowpedia there isn't this change documented o_0 )
http://wowwiki.wikia.com/Timeline_(World_of_Warcraft) (timeline to check that the forum thread was back in cata days)

**Comment by Kejmil** [comment]
4.3 http://wow.gamepedia.com/Patch_4.3.0#Death_Knights

The gargoyle called by  [Summon Gargoyle] should exclusively use its ranged attack regardless of range to the target.

**Comment by Kejmil** [comment]
still no snapshot, dunno about unlimited range

**Comment by Kejmil** [comment]
another bug - gargoyle should crit for 200%, currently is critting only for 150%
https://youtu.be/y0tfUCk7FbI?t=121

**Comment by kadi2** [comment]
That probably has been changed with cata, like warlock's pets i reported. But only imp and fel hunter has been fixed, since i didn't find the proper proof for other pets.

**Comment by freddie12** [comment]
wow. it's been more than a year and still no fix for it.

**Comment by Kejmil** [comment]
lucky class dk is ( ͡° ͜ʖ ͡°)

**Comment by freddie12** [comment]
i assume people does not know how serious this bug is for unholy death knights.

**Comment by Kejmil** [comment]
they are just too busy whining about gamebreaking bugs aka bugs concerning their classes xD

**Comment by freddie12** [comment]
maybe, we should spam more under this thread so we can draw some attention for this bug.

**Comment by freddie12** [comment]
bump

**Comment by freddie12** [comment]
i'll throw a party to celebrate this report's 2nd anniversary. all of you are my guests.

**Comment by Jenovas** [comment]
AP snapshot added in  rev 5226

**Comment by Kejmil** [comment]
what about crits? it's still not fixed completly
