### ISSUE TITLE
[EN][Spell][Warlock] Drain Soul

### ISSUE THREAD

**Issue by fluessig** [Atlantiss/BugTracker#8297]
drain soul seems to not scale with haste for some reason, even though the tooltip shows a haste calculated number
also u drop out of combat even while channeling drain soul 
i would guess the target should not drop combat nor should the caster
every time drain soul ticks combat is refreshed

http://cata.openwow.com/spell=1120 drain soul

proof:
http://wowwiki.wikia.com/wiki/Drain_Soul
Patch 4.2.0 (2011-06-28): It is no longer possible to leave combat while channeling Drain Soul.

**Comment by Illusie** [comment]
I play as Affliction pvp, and tbh, I barely use Drain soul as "execute" spell.
I found it very bad duo some reasons I don't aware to them.
If i am correct, the first tick happen after 4 second, meanwhile opponent healer can easy to heal through it. make the spell basicly not worth to cast because if you do it at 20% and the first tick appear after 4 second, the opponent healer have like 3-4 second to heal his ally above 20%. then the Drain soul does not double it damage.

On wowiki also it says that: "all periodic damage effects will instantly deal 40% of their normal damage".
I never saw it happen on Atlantiss.

That why I play with 0/2 Pandemic talent.

Thanks for the report, It would be nice if Jenova or someone else who knows Warlocks mechanic will check things out :)

@fluessig btw, how can I contact with you Ingame/Atlantiss forum?

**Comment by Fearyourself** [comment]
The link he gave from wowwiki is mop or wod version of Drain Soul.
That being said, I don't think Drain Soul is supposed to tick after 4 sec. It should tick way earlier because of haste and that's why it's useless for execute in pvp. The only reason that I use Drain Life as execute in pvp is because Drain Soul is broken and it takes too long for the first tick to occur like you said Illusie.

Also on a side note, the reason you get 1/2 Pandemic is to reduce the gcd of curses by another 0.5s (haste gets the other 0.5s). It's not really about the Drain Soul effect. Well that's just my opinion atleast.

**Comment by lamaATS** [comment]
Drain Soul scale with haste properly (I tested it a few minutes ago) and this spell doesn't have first tick at apply, You can see it in this video https://youtu.be/8Ff3FyTZREE?t=250

**Comment by Fearyourself** [comment]
It's not supposed to have the first tick at apply, but it's supposed to tick earlier than 4 seconds. You can see that in the video you linked. If you start counting seconds from when he casts drain soul and look at when it does damage, you'll count to 2-3 seconds. If you do the same thing on atlantiss, then you'll count to 3-4 seconds regardless of haste.

**Comment by Illusie** [comment]
@Fearyourself the issue wont gonna get fix they have so many on issues to handle, and TBC and other PTR tests.

But yeah, as warlock I feel like my "execute" skill is useless ^^. and You like me know how difficult is to Affliction warlock bringing a person to 20% health or below ;/

**Comment by lamaATS** [comment]
I will try to look at this issue once again (but currently I don't know when it will be).

**Comment by lamaATS** [comment]
Please check again on rev. 5242
