### ISSUE TITLE
[EN][Quest][Hillsbrad FootHills] Past their prime

### ISSUE THREAD

**Issue by Griskhet** [Atlantiss/BugTracker#8351]
Only some bears in the zone award you the kill and all of them spawn with half of their health.

http://www.wowhead.com/quest=28115/past-their-prime

![wowscrnshot_100316_152920](https://cloud.githubusercontent.com/assets/11901135/19038957/3852071a-897e-11e6-8d0c-b977073e9977.jpg)

**Comment by tomatosz** [comment]
The bears only grant the kill for the quest if they're above 50% health, but since they have a debuff that sucks their health (intended) you encounter many that are too low. 
They should always grant the kill, no matter the health.

Also, the buff somehow wears off sometimes, leaving the bears with 30-40 health. This shouldn't happen, the buff should actually kill them.

**Comment by tomatosz** [comment]
Posted fix on the forums:

https://community.atlantiss.eu/index.php?/topic/14707-quest-past-their-prime/#comment-70245
