### ISSUE TITLE
[EN] (Silverpine Forest) (Belmont's Report) Quest not working

### ISSUE THREAD

**Issue by MikasaAkcerman** [Atlantiss/BugTracker#8547]
It is  a very easy quest but without it you cant do other missions. quest want you bring report to the slyvanas but there is no question mark on slyvanas.

**Comment by TranceAccount** [comment]
# Please follow our _How to use?_: 
https://github.com/Atlantiss/BugTracker#how-to-use

Thanks in advance.

**Comment by Piklo** [comment]
ohm im slower xd

**Comment by Khangu** [comment]
There's really not much more to say about it.
http://www.wowhead.com/quest=27056/belmonts-report

You pick quest and then go to Sylvanas standing nearby at Forsaken High Command. And that's impossible cause she has no question mark and it's even impossible to speak with her.

There are other locations where she also appears (Sepulcher and The Forsaken Front) but in order to meet her there first u need to do couple of other quests and that's impossible cause this one blocks entire silverpine chain.

As usual... Quest was working fine some time ago.

**Comment by krecik88** [comment]
https://github.com/Atlantiss/BugTracker/issues/8717
