### ISSUE TITLE
[EN][Quest][Eastern Plaguelands] Beat it out of them

### ISSUE THREAD

**Issue by Adriya** [Atlantiss/BugTracker#8557]
Description : I can't return the quest to the NPC named " Fiona" because the caravan has disappeared .

 Current behaviour : It is supposed to be in the tower of the neck of the north , but the map shows to make the quest at the thondroril ( she is not here )

  Expected behaviour: The caravan should not disappear

   Revision : 5246

**Comment by Adriya** [comment]
The caravan of Fiona disappeared when i returned another quest to NPC " Tarenar Sunstrike"

**Comment by Adriya** [comment]
But i can't remember the name of the quest i returned

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
wowhead links

**Comment by Adriya** [comment]
[img]http://imageshack.com/a/img923/9103/Tcmn7D.jpg[/img]

**Comment by Adriya** [comment]
[img]http://imageshack.com/a/img923/9103/Tcmn7D.jpg[/img]

**Comment by Adriya** [comment]
http://imageshack.com/a/img923/9103/Tcmn7D.jpg

**Comment by Adriya** [comment]
[URL=http://www.hostingpics.net/viewer.php?id=299354WoWScrnShot111516001638.jpg]

**Comment by Adriya** [comment]
[url=http://www.hostingpics.net/viewer.php?id=299354WoWScrnShot111516001638.jpg][img]http://img4.hostingpics.net/pics/299354WoWScrnShot111516001638.jpg[/img][/url]

**Comment by Adriya** [comment]
[IMG]http://img4.hostingpics.net/pics/299354WoWScrnShot111516001638.jpg[/IMG][/URL]

**Comment by Adriya** [comment]
Fiona's caravan disappeared at "Northpass Tower " (50.6, 20.2) : http://www.wowhead.com/npc=45400/fionas-caravan
The Quest that  i can't return :  http://www.wowhead.com/quest=27522/beat-it-out-of-them#videos
The Npc who made disappear the caravan of Fiona by returning a quest :  http://www.wowhead.com/npc=45729/tarenar-sunstrike

**Comment by Destroman** [comment]
I had the same issue. It appears when u end the quest "The Baroness' Missive" (http://www.wowhead.com/quest=27551/the-baroness-missive) before ending "Beat it out of them" (http://www.wowhead.com/quest=27522/beat-it-out-of-them#videos). The Questitem "the baroness' missive" drops from a mob in the plaguewoods. I guess it should not drop when "Beat it out of them" is still open, because "Tarenar Sunstrike" (http://www.wowhead.com/npc=45729/tarenar-sunstrike#ends) should be in the plaguewoods at this time and not at the "Northpass Tower". 

My mistake was to turn in "the baroness' missive" at Tarenar at the Northpass Tower and then Fiona dissapears. Then i noticed that i cant start the following quest "Gidwin's Fate Reveales" (http://www.wowhead.com/quest=27526/gidwins-fate-revealed) because i still have "beat it out of them" open and Fiona and her caravan are gone. 

Its a very hard issue because you are not able to end the story line in the eastern plaguelands. It blocks both questlines:

"Blind Fury" (http://www.wowhead.com/quest=27524/blind-fury) to "Guardians of Stratholme" (http://www.wowhead.com/quest=27525/guardians-of-stratholme)
"Gidwin's Fate Revealed" to "Journey's End" (http://www.wowhead.com/quest=27527/journeys-end)

Is there any chance to get these quests now? Pls help me

**Comment by karolnpc** [comment]
Bump

**Comment by TranceAccount** [comment]
Quest chain is probably wrong.
