### ISSUE TITLE
[EN][Core] Raid Loot System

### ISSUE THREAD

**Issue by Jamishman** [Atlantiss/BugTracker#8576]
So you have 4-5(25 man) loot slots and on atlantiss they together have a same chance* to drop items, which means that you will never see 2 or even 3 of the same items droping from a boss kill.
How it should work: Every loot slot should have its own chance (spinning wheel) to choose between all items.
Example: First item - Chance of Item1 Item2 Item3 Item4 Item5
Second item - Chance of Item1 Item2 Item3 Item4 Item5
...
So there should be a possibility for 5 same items to drop
On ats. if First item is Item1, 2nd and ... Item cannot be Item1 since it will be excluded from roll to drop.

Proof: https://youtu.be/hGeY1Hxv-u8?t=10m ( 2 of same item (types since its al'akir rng enchant))
https://youtu.be/5AjM0qGGYFY?t=10m30s (check chat 2 of the same cloth legs dropped)

**Description**: You can't get multiple items of the same from bosses

**Current behaviour**: When you kill a boss it can only drop one of the item except for tokens

**Expected behaviour**: You should be able to get multiple of the same items from bosses

**Steps to reproduce the problem**:

1. Kill a boss in a raid 
2. Look at their loot
3. Notice there's never any duplicate items

**Revision**: 5256

**Comment by Prodiege** [comment]
Is this for 10 man as well? 

Is there any proof besides the 2x 25-man videos that drops are supposed to work like that in 10 man?

**Comment by Jamishman** [comment]
This is almost certainly 25-man exclusive behavior, but it should still be a priority, even though most guilds don't run 25-man

**Comment by Prodiege** [comment]
To be honest, you are saying it should be a priority but it probably shouldn't. 

There is 1 guild right now raiding 25s -yours. And it isn't like loot isn't dropping at all either, you are still getting the correct amount of loot every week

If I recall correctly from what I know about the loot system in the SQL, this change would take a lot of grunt work and time to implement for very little reward

**Comment by Jamishman** [comment]
First of all, there's an unbelievably large flaw in your logic, because we are basically running 3 guilds worth of people in FL HC we should be fucked by non-Blizzlike loot drops? That's incredibly short-sighted.

Also tokens already work properly, all that needs to be done is make loot act like tokens, since that is already implemented correctly, I doubt it would be difficult to figure out a proper fix from that.

**Comment by Prodiege** [comment]
You're still getting the full amount of drops from the boss. You just aren't getting the low % chance that the boss will drop 2 of the same item, which could fuck you over just as much.

You are also the only 25 guild on the server, and even if there was more this should still be considered low priority since you are still getting the same total number of drops from the boss either way. 

You obviously don't know how the loot system works. They have to go in for every boss and modify the grouping of items for every boss one at a time. Its not about figuring out the fix, it is about the time taken to do it and it can be better utilized elsewhere first. There are many problems more impactful and older that are more worth the time of the server development staff

**Comment by Jamishman** [comment]
Except its much better in a 25 man raid, to have the chance for multiple item drops, 99% of the time.

Total drops don't matter when you're almost guaranteed at least 1 garbage loot per boss, what are we supposed to do with rings/weapons off bosses that everyone already has?

With all the bug reports, and testing, and class fixes we've been attempting to help the devs with, clearly we should be fucked over for wanting to do actually difficult content.

**Comment by Prodiege** [comment]
You fail to see how this is low priority and that is hilarious. A+

**Comment by Jamishman** [comment]
Loot is a core mechanic of WoW, how you fail to see that this is higher priority than a lot of issues is hilarious.

**Comment by Prodiege** [comment]
LOL. Unbelievable

**Comment by Kejmil** [comment]
and then by the power of atlantiss RNG you would get 4-5x ring that "everyone have already"
you really want it? ( ͡° ͜ʖ ͡°)

**Comment by Jamishman** [comment]
Yeah I do because at least we will get fucked one week, not every week

**Comment by Prodiege** [comment]
Then you are getting fucked by RNG. Stop crying please

**Comment by Jamishman** [comment]
Getting fucked by RNG is lovely if its true RNG, not made up non-Blizzlike RNG, please don't be upset that whatever guild you're in can't do 25 mans.

**Comment by Prodiege** [comment]
I'm not, I just don't want the development staff wasting time on this over something more valuable to the server as a whole.

**Comment by Jamishman** [comment]
Yes, fixing low level quests is much more important than current raid content, I agree.

**Comment by Prodiege** [comment]
I didn't specifically say low level quests, I have no idea what you are talking about. Just as an example: there are [150 open tickets](https://github.com/Atlantiss/BugTracker/issues?page=1&q=is%3Aissue+is%3Aopen+label%3A%22Spell+-+Generic%22) labeled Spell - Generic, [50 open tickets](https://github.com/Atlantiss/BugTracker/issues?q=is%3Aissue+is%3Aopen+label%3A%22Raid+-+Cata%22) labeled Raid-Cata, and I can guarantee you that 90%+ of those issues are more important to spend time on than this issue. 

You seem to have a fundamental misunderstanding of how random generation works and if this is implemented you would be getting fucked over just as much by having too many of the same pieces dropping eventually. This isn't about loot not dropping at all, that is a totally different matter that WOULD be of higher priority. But JUST because you wrote "but it should still be a priority, even though most guilds don't run 25-man" I felt the need to make sure that you don't attempt to take advantage of the server AND the developers time with such minor, yet time consuming, changes. 

Ultimately it is up to the development staff what they chose to spend their time on, and I hope they read this and realize there are really more important matters worth their time

**Comment by Jamishman** [comment]
There's also a large number of those that have been fixed or corrected without being closed. 

You seem to as well, it is much more beneficial to receive 2x of an item every week, than to receive 1 of the same item over and over in regards to gearing characters, especially when the majority of loot is good. 

Clearly I'm taking advantage of the servers developers by posting a correctly formatted bug report, that clearly explains what is going on. As does the rest of my guild, I'm not bitching about fixing Ragnaros Heroic 25 man, which is currently borderline undo-able, I'm reporting an issue that is much more generic, and will eventually affect more than just one guild.

**Comment by Prodiege** [comment]
Just don't claim it should be a priority, because it is not. That simple

**Comment by Aival94** [comment]
This one has been fixed as far as i know. Please confirm if yes or not.

**Comment by Jamishman** [comment]
It was still not Blizzlike on Wednesday of last week

**Comment by TranceAccount** [comment]
@pelekon didn't you fix this some time ago?
