### ISSUE TITLE
[EN][Spell][Shaman] Grounding Totem

### ISSUE THREAD

**Issue by Zhalox123** [Atlantiss/BugTracker#8589]
http://www.wowhead.com/spell=204336/grounding-totem
**Description**: Describe the problem
Grounding totem doesnt get removed after casting full polymorph on the shaman.

**Current behaviour**: What happens
Casting polymorph on shaman drops grounding I finish casting polymorph the grounding still stays doesnt get removed after eating the cast.

**Expected behaviour**: What should happen instead
After finishing casting polymorph on the shaman with grounding active should remove the totem.

**Steps to reproduce the problem**:
1. Make a shaman drop the grounding totem.
2. Cast polymorph on him.
3. Grounding still stays up as many times u spam poly it will stay active.

Revision: 5256

**Comment by Piklo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
wowhead links

https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md
you can see current server revision by typing ".s in" in chat

**Comment by Zhalox123** [comment]
EDIT:Mind control of priest is also affected doesnt remove the grounding after finished casting.

**Comment by Jenovas** [comment]
Fixed in rev 5275
Shaman:
- Grounding Totem will now be removed after redirecting spells that do not deal DMG (Fear, Cyclone, Poli)
- Grounding Totem will now be destroyed after getting hit by a spell instead of after a spell cast is finished. This means that Grounding Totem can now redirect multiple spells that have travel time. Example - a Mage and Warlock are attacking a Shaman with Grounding Totem up. The Mage casts Fireball, Fireball is currently traveling towards the Grounding Totem, if the Warlock finishes casting Chaos Bolt before Fireball hits the totem Chaos Bolt will also be redirected to the Grounding Totem.

**Comment by Zhalox123** [comment]
https://github.com/Atlantiss/BugTracker/issues/8753
