### ISSUE TITLE
[EN][Instance-TBC][WoWError] Shattered Halls

### ISSUE THREAD

**Issue by PierwszyKrytykRP** [Atlantiss/BugTracker#870]
Something in Shattered Halls is causing wowerror

http://wklej.org/id/1565587/

It happens in this area

http://i.imgur.com/43bZWH9.jpg

**Comment by silverches** [comment]
it's still happening

**Comment by Hordraric** [comment]
I did this achiev on druid dont know how. Now on paladin seems impossible to cross from 1st boss to 2nd one

**Comment by Danelar** [comment]
Bad news :(

**Comment by Aival94** [comment]
I have managed to do this dungeon somehow.It seems the problem is not in the mobs [Shattered Hand Zealot](http://www.wowhead.com/npc=17462/shattered-hand-zealot) but on the location of the map as when you run fast and aggro them(if not crash) and go to the next room where some [Shattered Hand Centurion](http://www.wowhead.com/npc=17465/shattered-hand-centurion) are and fight them there no crash is happening(The room where [Blood Guard Porung](http://www.wowhead.com/npc=20923/blood-guard-porung) give crash about 50% of the times i think). This crash also happen where you first encounter [Shattered Hand Champion](http://www.wowhead.com/npc=17671/shattered-hand-champion)(coordinates on wowhead map from 48.4, 14.0 to 51.6, 13.8).The other location seems fine and without any crashes.

**Comment by Tj20** [comment]
Finally did this dungeons today, and as was said before: in the Gauntlet (Hall after the first boss) everybody in the group had a WoW error. My WoW.exe jumped in some seconds from ~450 MB to 1600 MB memory usage and stopped responding.

**Comment by Clarkiez96** [comment]
Still no possible way to complete this? I need my mog :>

**Comment by Aevrolana** [comment]
This dungeon can be completed if you are either a rogue or possess a couple Lesser Invisibility Potions to bypass the mobs that cause the crashes to occur (see Aival94's comment for coordinates). I completed it on heroic and normal mode using two Lesser Invisibility Potions today.

https://i.imgur.com/3wSq4aY.jpg

**Comment by Tj20** [comment]
I've spent some time testing stuff and I think I have a pretty good idea now about the crashes:

### Affected Mobs:
- [Shattered Hand Assassin](http://www.wowhead.com/npc=17695/shattered-hand-assassin)
- [Shattered Hand Zealot](http://www.wowhead.com/npc=17462/shattered-hand-zealot)
- [Shattered Hand Archer](http://www.wowhead.com/npc=17427/shattered-hand-archer)
- [Shattered Hand Champion](http://www.wowhead.com/npc=17671/shattered-hand-champion)

![map](http://i.imgur.com/62XPDSM.jpg)
(red little cross: game crashed when I aggroed that mob)

### What happens:
- 1 mob: nothing
- 2 mobs: Feign Death will crash the game
- 3 or more mobs: If you only damage part of the mob group (like only 1 mob) there's a high probability that the pull will crash the game. Also Feign Death will crash the game

![what happens](http://i.imgur.com/JCcErBt.jpg)

### Why does it happen?

I have 2 theories.

**a) the aggro/de-aggro mechanism of these mobs is broken**
The mobs are linked in some way. If you pull one mob, it will call the other mobs of the group to help. Something doesn't work here if the mobs are too far away from each other but still in a linked group.

**b) it has something to do with their animations**
All 4 mobs have special animations: Assassins run and die with their daggers sheathed. Zealots do that with their cleavers. Champions run and die with the shield on their back instead of being in their hand. Archers change between multiple weapons and they also die without any weapon in hand.

![weapon change](http://i.imgur.com/abpPGaW.jpg)

As far as I can see, those are the only mobs with special weapon animations. All other mobs in the instance don't have problems, and their weapons are fixed to their hands.

### Workaround:
Aggro every mob at the same time with AoE. Don't use Feign Death.

If the devs don't know what exactly is wrong with these 4 mob types, maybe they could do a quick & dirty fix:  
un-link the mobs of the 4 or 5 mob groups which are problematic so one aggroed mob doesn't try to call the other mobs for help. It's not exactly blizzlike but at least groups won't have wow crashes any more.

**Comment by Tj20** [comment]
By the way, Shojiro was kind enough to also test this, and he reported the same issues (2+ of those mobs: Feign Death will crash the game if you put your pet away beforehand, 3+ mobs: pulling only one of them will crash the game after the first one came and then the others tried to follow).

So I guess it's a common problem and not related to my PC.

Workaround, as already mentioned: pull the whole mob group at the same time with an AoE ability. This may seem counter-intuitive for low level groups where the tank usually only aggroes 1 or 2 mobs, but in this case he should ask one of the DPS to pull with AoE.

**Comment by Dean1989** [comment]
@Tj20 impressive report, pls fix this instance

**Comment by Clarkiez96** [comment]
Kind of necroing, but this still hasn't been fixed and I need to farm this place so I don't care. Can you seriously do what @Tj20 said, it's so damn annoying. An invis potion doesn't last long enough to get past the group around the boss at the end of the hall and waiting 10 minutes for it to cool down is absurd! Also Tj20 with the 3 archers at the second boss, I nitro'd in to the dead centre of the group and instantly hit the mob you marked with a cross, one shotting him. I still crashed, so I'm assuming that the whole group is bugged and not just that one mob. Also I'm a ret so it is very difficult to pull all 3 mobs at the same time without pulling one a fraction earlier, due to melee reasons. Would going Protection and using Avenger's shield be enough to pull them and not crash?

**Comment by Axahus** [comment]
High priority imo. Potrzebuję pofarmić ostatniego bossa, ale każdy crash zawiesza komputer na ok. 2 minuty, po czym często nie działa nawet "zakończ proces" (ctrl+alt+delete), więc trzeba restartować komputer...

**Comment by Quban** [comment]
> The reason I even thought of this is that the wowerror mentions an "AnimKit" object:

this kind of errors are caused by mob emotes, dont know why it happens, if you find this AnimKit msg on another mobs, than report it

**Comment by Tj20** [comment]
I just tested your fix in the Shattered Halls and in Kaskala (#1791) on the PBE and it works like a charm - no more WoW crashes, great job!

Did you just remove their emotes? I never noticed that the mobs had special emotes which might cause this problem when they enter/leave combat, but your fix seems to work great. Very happy!

**Comment by Bildo** [comment]
Yay but you know that fix is not live yet :D

**Comment by Tj20** [comment]
Yes, I've checked it on the PBE. Rev 4574 is already live over there according to .s in.

**Comment by Bildo** [comment]
ohh didn't know what PBE means ;p

**Comment by Aival94** [comment]
Good job fixing this one.It was really annoying for tbc level ppls.ok now go to sunwell(hopes always :D)

**Comment by TranceAccount** [comment]
Bump. I just crashed here.
