### ISSUE TITLE
[PL]Utrata po crashu

### ISSUE THREAD

**Issue by yeneferka** [Atlantiss/BugTracker#8735]
Witam serdecznie. Kolo 5:30 cos sie stalo z serwerem i nastapilo cofniecie o ok 3 tygodnie. Da sie cosik z tym zrobic??

[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[
**Revision**: Current server version

**Comment by Piklo** [comment]
Po pierwsze, nie napisałeś /aś co się dokładnie stało, ale sądząc po tytule chodzi o to że coś straciłeś /aś. Najpierw upewnij się że wybrany jest dobry realm, może jesteś na PTR który ma aktualizowane postacie co jakiś czas. Jeżeli naprawdę cofnęło Ci postacie o 3 tygodnie to może być problem, ponieważ w [rules](http://atlantiss.eu/pages/3) jest napisane tak:
"GMs/Admins do not change the race/class/sex of a character, they do not change a nickname nor make character transfers, do not move/exchange/give items/gold, do not complete quests for any players (it can be done only in cases with no other way) and do not give back items/honor/ap/rating/gold etc lost because of dc/player's fault/technical problems/actions by a third party."

Po drugie, bug tracker raczej nie jest miejscem do zgłaszania takich rzeczy, tutaj opisuje się błędy które później deweloperzy będą (próbować*) naprawiać. Przypuszczam że lepszym miejscem na ten post byłoby forum, na przykład [tutaj](http://community.atlantiss.eu/index.php?/forum/9-support-qa/), GMi nie muszą wchodzić na bugtrackera, bo po prostu to nie jest ich zadaniem. 

próbować*, tutaj chodziło mi o to że nie wszystko można naprawić za pierwszym razem, a czasami nawet po naprawieniu po prostu nie działa tak jak powinno.

Twój post zostanie prawdopodobnie niedługo zamknięty, lub możesz sam(a) go zamknąć.
![awsfdgh](https://cloud.githubusercontent.com/assets/16057987/21539758/fe2c0656-cda9-11e6-9673-5a998072668b.PNG)
