### ISSUE TITLE
Apparatus of Khaz'goroth sharing cooldown with pvp trinkets

### ISSUE THREAD

**Issue by brokenshard** [Atlantiss/BugTracker#8787]
Description: Apparatus of Khaz'goroth
Current behaviour: Apparatus of Khaz'goroth shares cooldown with pvp burst trinket (Ruthless Gladiator's Badge of Victory)
Expected behaviour: Apparutus of khaz'goroth and the pvp trinket could be used at the same time
here's the evidence https://www.youtube.com/watch?v=-aB-wcwFh9Y at 5.40mns as u can see he has both of the pvp trinket and the Apparatus of khaz'goroth buffs and i checked the patch notes and they didnt mention anything about putting them on the same cd
Steps to reproduce the problem:
1. put on both of the trinket
2. use one of the trinket

**Comment by Piklo** [comment]
use [issue template](https://github.com/Atlantiss/BugTracker/blob/master/ISSUE_TEMPLATE.md)

**Comment by brokenshard** [comment]
i did?

**Comment by krecik88** [comment]
fix title, add wowhead links

**Comment by Sayris9876** [comment]
Just decided to put some more information and I looked around forums and this is what i found: 
"Aug 10, 2011: All trinkets/non-class abilities that give you a stat boost for X seconds on demand (or just do a large amount of instant damage) all share a "Burst" cooldown (as of a patch mid-way through Wrath)."
https://us.battle.net/forums/en/wow/topic/2973250693

But I also saw a comments like:
"sep 07, 2011: Trinkets like:  Apparatus of Khaz'goroth and Ruthless Gladiator's Badge of Victory can be used at the same time. It's mostly the trinkets that increase your raw dmg (Agility, Intellect, Strength, Attack Power and Spellpower) that share can't be used at the same time."
"sep 06. 2011: ...A few trinkets, however, stray from this (namely if you combine, say, Ruthless/Vicious Gladiator's Badge of Victory and an Apparatus of Khaz'goroth) - and are synergetic in the sense that they are usable at the same time."
https://eu.battle.net/forums/en/wow/topic/2624783169

4.2.2 patch is from 10th of August 2011; 4.3.0 (first patch of hour of twilight) is from 30th of November 2011. So the comments are from end of 4.2 patch and until 4.3.4 nothing is changed trinkets wise.
http://us.battle.net/wow/en/game/patch-notes/4-3-4

The general rule is you cannot use burst trinkets at the same time (only after burst duration is done from first you can use second) however there is exception at least for Apparathus (as second commend stated) because its boost is to secondary stat not primary. So patch wise (according to forum player information)  4.2 Apparathus and pvp trinket can be used at the same time.. Still havent found an official statement only players comments so not sure if thats how its suppose to be.

Right now in wowhead every on use trinket shares cd with other on-use trinkets but as we all know wowhead is with legion updates so still not 100% sure.
http://ptr.wowhead.com/item=69113/apparatus-of-khazgoroth#shared-cooldown:250-2  
(check "shared cooldown" section)

So conclusion: Yes you can use apparathus and pvp trinket in 4.2 (no info about this being changed in 4.3) but the information I gathered is only from players from blizzard forums not a single official statement. From the video above and from the comments I saw i think it is indeed a bug and we should be able to use Apparathus and pvp trinket at the same time but now another question pops up... Can we use Apparathus and another PvE on-use trinket together in PvE enviorment? Everyone is talking about Apparathus + PvP trinket but I couldnt find info about Apparathus + another PvE trinket...

**Comment by sigmundfreud2016** [comment]
Please, don't try to break something which actually works just because you want to pwn. I have human DK, warrior and paladin myself, still I don't want any bugged mechanics to be implemented here.
http://www.mmo-champion.com/threads/1032941-Apparatus-of-Khaz-Goroth-nerfed
https://us.battle.net/forums/en/wow/topic/4079845343
First link is dated as 30/11/2011, which was just next day after the patch 4.3.0. Not all changes are officially documented, you know. Especially if it is a bug-fix.

**Comment by Myivo** [comment]
https://github.com/Atlantiss/BugTracker#how-to-use
wowhead or cata.openwow.com links
