### ISSUE TITLE
[EN][CLASS][WARRIOR]Fury Warrior Titans Grip Hit Cap

### ISSUE THREAD

**Issue by Minazukii** [Atlantiss/BugTracker#8807]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**:
Fury Warrior can miss with main 2h even with 8% hit

**Current behaviour**:
Main 2h Weapon can miss even if you have 8% hit.
**Expected behaviour**:
Main 2h weapon shouldn't miss with 8%, only off hand should have 27% hit cap.
**Steps to reproduce the problem**:

1. Play fury specialization with Titans Grip
2. Attack Dummy
3. Look at misses with main hand

**Revision**: Rev .5291

**Comment by Binchal** [comment]
Truth

**Comment by stanq87** [comment]
well if i have only the main weapon it works as it should, dont know when i have two weapons,

**Comment by Jenovas** [comment]
From the first article I found on wowwiki - "Dual wielding adds a 19% miss penalty to both main and offhand weapons.".

It would be really weird to have a different hit chance for main hand and off hand.
Closing.

**Comment by Jenovas** [comment]
From Blizzard Forum:
"
Apr 14
 (Edited)

Tavenger's information not entirely correct. The base chance to miss was 7%, but when they removed hit rating as a stat on gear they also changed the base hit (as well as dodge and parry) chances.

For all of WoD, the base chance to miss for melee, ranged and spells, against a target up to 3 levels higher than you is 0%. 

He is correct, for Dual Wielding classes/specs there is a 19% miss penalty, just as there's always been. However, this ONLY applies to auto-attacks, it does not apply to any abilities (also, just because a LOT of people seem to not realize this, but this penalty applies to ALL auto-attacks, not just auto-attacks made with your offhand). "

From worldofwarcraft.wikia:
"Dual wielding adds a 19% miss penalty to both main and offhand weapons. "

From http://www.wowhead.com/spell=30798/dual-wield :
"Chance to miss with auto-attacks in both hands is increased by 19%."

From wow.gamepedia:
"Dual wielding adds a 19% miss penalty to both main and offhand weapons."
