### ISSUE TITLE
[EN][Quest][Stormwind]Hero's Call; Deepholm

### ISSUE THREAD

**Issue by Veriee** [Atlantiss/BugTracker#8869]
**Description**: I just made faction change, and all my quest progress is gone. I wanted to start deepholm chain quest, but after first part, second is missing. I really want to get this quest working, because I need shoulders enchant from therazane.

**Current behaviour**: Can't start any quest in deepholm and stormwind, related to deepholm.

**Expected behaviour**: I should get a quest starting other quests in deepholm

**Steps to reproduce the problem**:

1. start quests i deepholm
2. Make faction change
3. get Hero's Call; Deepholm.

**Comment by Aival94** [comment]
This happened because of faction change. If you cannot start the [Hero's call: Deepholm](http://www.wowhead.com/quest=27727/heros-call-deepholm) go to [Naraat the Earthspeaker](http://www.wowhead.com/npc=45226/naraat-the-earthspeaker) and speak see if you can take quest [The Maelstrom](http://www.wowhead.com/quest=27203/the-maelstrom). If this does not work then make a ticket and stay online with the char with the ticket.

**Comment by TranceAccount** [comment]
Make a ticket.
