### ISSUE TITLE
[EN][Quest][Deepholm][Silvermarsh Rendezvous]

### ISSUE THREAD

**Issue by Jumbubbly** [Atlantiss/BugTracker#9018]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Deepholm automatic quest failed to update

I was completing my Deepholm quest chain to obtain the Therazane faction and once i completed "The Forgemaster's Log" and then scouted Upper Silvermarsh to complete the  "Silvermarsh Rendezvous" quest, the next quest is supposed to automatically update.  That did not happen and i am NOT ABLE TO START the quest "Quicksilver Submersion" as there is no quest giver. 

Please allow me to complete this quest so I may continue with the quest chain. thank you

**Current behaviour**: I can not start the nest quest in the chain

**Expected behaviour**: To be able to start the next quest in the chain to eventually obtain Therazane rep

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Jumbubbly** [comment]
Character name = Mattdaemon

**Comment by qwertyasad** [comment]
There are some quests in Deepholm that don't automatically complete as they are supposed to. Instead, you have to go to the NPC that gave you the quest. 

Have you tried that?

**Comment by Jumbubbly** [comment]
The "Forgemaster's Log" gave me the quest before the quest i am having issues with.  When i speak to it nothing happens.  Many quest before are either Automatic or are given via an item. Maruut Stonebinder is the most recent NPC to give me a quest.  He offers no help.

**Comment by Aival94** [comment]
Reported: https://github.com/Atlantiss/BugTracker/issues/3325
Related: https://github.com/Atlantiss/BugTracker/issues/2960

**Comment by Ripnugget** [comment]
This issue is not a duplicate and should not have been closed.  The issue here is that there is no way to pick up the following quest:
http://www.wowhead.com/quest=27010/quicksilver-submersion
after the initial quest
http://www.wowhead.com/quest=27007/silvermarsh-rendezvous
is completed.  Thus making it impossible to progress further in the chain.

**Comment by Aival94** [comment]
I finished deepholm on an alt before 1 week if i remember correct and i did hall zone quests without any problem. Maybe you skip some quests and this cause your bug. 
I would recommend you to download [Grail](https://www.curseforge.com/wow/addons/grail/files?filter-game-version=2020709689%3A205) and [Wholly](https://www.curseforge.com/wow/addons/wholly/files?filter-game-version=2020709689%3A205) in order to help you with questing and see what quests you have not done in a zone.

**Comment by Ripnugget** [comment]
I downloaded Grail and Wholly and searched every square inch of deepholm, and cant find a single quest. I don't know what to do to fix this now.
