### ISSUE TITLE
[PL][Dungeon-Cata] Deadmines Vanessa Vancleef

### ISSUE THREAD

**Issue by Mati569** [Atlantiss/BugTracker#9072]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

Opis: http://www.wowhead.com/npc=49541/vanessa-vancleef#encounter
http://www.wowhead.com/spell=93484/fiery-blaze
Fiery Blaze – After Vanessa has been wounded below 50% of her total health, she will leap to the top of the ship and detonate preplaced explosives around the ship. These explosives will create Fiery Blazes across the deck. Players within 5 yards of a fire will be dealt 13875 to 16125 Fire damage every second. 

Aktualne zachowanie: Vanessa po uzyciu Fiery Blaze teleportuje się na góre statku i nie schodzi stamtąd co uniemożliwia podniesienie lootu. Vanessa stoi u góry, a auto ataki i skille aoe (swipe i trash miśka) trafiają jakby stała na środku podkładu.

Poprawne zachowanie: Powinna zejśc na dól do graczy po wybuchach.

Kroki aby powtórzyć problem:
Po prostu bić, dzieje się tak za każdym razem.

Rev. 5357

**Comment by Anhaeyn** [comment]
Popraw tytuł i zgłoszenie, używając szablonu:
[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Describe the problem

**Current behaviour**: What happens

**Expected behaviour**: What should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)


Bo inaczej zostanie to zamknięte bez odpowiedzi.
