### ISSUE TITLE
[Eastern Plaguelands] Onward, to Light's Hope Chapel

### ISSUE THREAD

**Issue by Vyrus21** [Atlantiss/BugTracker#9153]
**Description**: when you go to caravan and put the option "Ride Fiona's Caravan to its next destination" you be stuck on caravan and you have to close the game or nothing happened.

**Current behaviour**: Bugged

**Expected behaviour**: Suppost to go in caravan with Fiona to th destination.

**Steps to reproduce the problem**:

1. Remove all Caravans in entrance of Eastern Plaguelands, its very confused
2. Allow to go with Fiona in Caravan to the destination.
3. http://www.wowhead.com/quest=27373/onward-to-lights-hope-chapel
4. https://www.youtube.com/watch?v=i7S6A0XaOU8

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by xmesaj2** [comment]
#1035 related

**Comment by IamtheLexx** [comment]
Yeah confirming bug. There's a bunch of caravans stacked on top of the others and it's annoying.

**Comment by XreaperDK** [comment]
Still a major bug. It blocks the rest of the Caravan questline, including an achievement and story progression throughout the rest of Eastern Plaguelands.

When attempting to mount on the caravan to continue the quest after getting past the 200 stacked on top of it, it will just freeze. The only way to get off is to log off then back on which will then throw you out of the world to your death in the void (see image below) where you will have to log off again then back on in order to be spawned at the nearest spirit healer. Thankfully it doesn't give you ressurection sickness.

Images of the caravan pile and being thrown out of the world:
https://imgur.com/a/AU9Go

**Comment by wandres0697** [comment]
@XreaperDK When you get throw out of the world and die in the void you can use this macro "/script RepopMe() " that confirms the dialog that pops up to release your corpse and sends you to the graveyard so you don't have to log off.

**Comment by KieraHorde** [comment]
Was there any action done towards fixing this bug? 
Please solve this issue!

**Comment by Avalain** [comment]
Waited for server restart to see if it would work for at least one player. Nope. It's the same thing, you're stuck on not moving wagon and even waiting doesn't complete quest.

While this is not gamebreaking it is probably one of most annoying bugs for leveling characters 40+ questing on Eastern Kingdoms. Saw too many people stuck there asking for help.

Even temporal fix would be most appreciated, especially that quest was working one year ago.

**Comment by RagingShostakovich** [comment]
Confirming that this remains a major blocking normal progression bug.

**Comment by MediDaner** [comment]
Still a major issue, blocks the majority of the Eastern Plaguelands

**Comment by xmesaj2** [comment]
rev 5547
