### ISSUE TITLE
[EN] [Spell] [Dk] Dark Simulacrum copy interupt cooldown on mind freeze

### ISSUE THREAD

**Issue by Heroclassx** [Atlantiss/BugTracker#9311]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Hey, tbh i dont know if this is a bug or intendet, but i know no reason why it should be no bug, so here is the case:

I just played an arena game and gripped the enemy mage and put dark simulacrum up becasue 90% of the time vs not so experienced mages i will copy blink, and will save it for smokebomb or to blink kidneys. This time he counterspelled me in the excact same moment so i copied counterspell. he then ran away from me and tried to poly my shaman and i CS'ed that poly. I got a 22 sec lock on mind freeze (cooldown of counterspell) (normal cooldown 10 sec)

Here is a small video: https://www.twitch.tv/videos/155787555 at about 40 sec i copied CS and used it shortly after. :)

**Current behaviour**: See description

**Expected behaviour**: I guess no cooldown on mind freeze when using counterspell.

**Steps to reproduce the problem**:

1. Find a Mage/warlock w/ fellhunter
2. put dark simulacrum on mage / fellhunter
3. use that copied CS / spell lock
4. see mind freeze on a cooldown equal the cooldown of the spell used.

**Revision**: Current server version (you can see current server revision by typing ".server info" command in the game chat)

**Comment by Sayris9876** [comment]
I really dont know how to search for info about that kind of scenario but a MoP example Disrupting shout (40 sec cd aoe interupt) and the normal pummel it works like this: If you use Pummel Disrupting shout goes into same cd as pummel however if you use Disrupting shout it goes on 40 sec cd but pummel goes into its usual 15 sec cd (mop cooldown of interupts). So following that logic if you using copied CS the mind freeze should go in its own 10sec cd (because if "I guess no cooldown on mind freeze when using counterspell." that is the way it works it is a bit too overpowered). Again dont have any info at all but mind freeze going into 10sec cd seems the proper way to work like that.

**Comment by lamaATS** [comment]
What about this https://us.battle.net/forums/en/wow/topic/1756036762 ?
