### ISSUE TITLE
[EN][Spell][Warrior] Raging blow

### ISSUE THREAD

**Issue by brokenshard** [Atlantiss/BugTracker#9619]
Description: raging blow should do a lot more damage than bloodthirst but it a bit less damage than bloodthirst https://www.youtube.com/watch?v=eA_Wbb8Z3w4 you can see at 10:46 the warrior's raging blow main hand does 18k non crit+off hand crit 25k in total 43k and then he bloodthirsts for 35k crit

Current behaviour: Raging blow damage is weaker than it should be

Expected behaviour: Raging blow should do a lot more damage than bloodthirst

Revision: Current server version 5534

**Comment by Psychobird7** [comment]
The video you linked shows literally nothing.  
You can not know what gear that warrior is wearing, or what weapons they are using, therefore you can also not estimate their AP and weapon damage.  

You also did not bring any logs or testing from Atlantiss. 
Without providing any of those, I don't really see how you expect this "bug" (if it even is one, since your last report was also erroneous) to be acknowledged, let alone actually fixed.

**Comment by brokenshard** [comment]
they can easily test it out them selves + do u think an ability that requires a condition to be used would hit less that a 3sec cd ability think about it

**Comment by Malylolek** [comment]
xD

**Comment by Vayns** [comment]
Nice proof yo.
