### ISSUE TITLE
[EN][Paladin] Hammer of Wrath 

### ISSUE THREAD

**Issue by Psychobird7** [Atlantiss/BugTracker#9623]
**Description**: 
Hammer of Wrath (referenced to as "HoW" in the following) currently uses incorrect base damages and/or scalings.  

**Current behaviour**: 
In my character's unbuffed state, having 13779 AP and 4244 SP, HoW deals an average of 10400 Holy damage. 
Testing done with an active Aura showed a range of approx 10400+-200. 

**Expected behaviour**: 
The proper base damages and coeffs for HoW are the following: 
Base: 3814.27 to 4215.78 
Coeffs: 50% of AP and 15% of SP. 
These values are taken from Simcraft and align with information found on EJ. 

With the same parameters as in the testing mentioned above, this amounts to an expected average of 11992, which is a very significant difference. 

Base damage: Open Simcraft results or "sc_paladin.cpp". You will find them easily. 

Ratios: https://web.archive.org/web/20120704234204/http://elitistjerks.com/f76/t110342-retribution_concordance_4_3_voice_dps/ 
"Base Damage: average 4015 (exact range yet to be tested extensively and calculated)
Coefficient: 50% AP + 15% SP"

**Steps to reproduce the problem**:

1. Go to a dummy that you can easily DPS down to <20% 
2. Take off any procs that could modify HoW damage, and do not use Inquisition or any Cooldowns
3. Once your dummy is at <20% HP, spam HoW on it 
4. Check the results on your combat text or damage meter against the proper damage/ratios from Simcraft or EJ

**Revision**: 5534

**Comment by Piklo** [comment]
posted fix on forum:
https://community.atlantiss.eu/index.php?/topic/15287-9623-hammer-of-wrath-spell_bonus_data/

**Comment by Psychobird7** [comment]
ty <3

**Comment by Jenovas** [comment]
Fix in 5537

**Comment by lamaATS** [comment]
```
"Base Damage: average 4015 (exact range yet to be tested extensively and calculated)
Coefficient: 50% AP + 15% SP"
```
In EJ post base damage is not 100% sure like poster said in comment `exact range yet to be tested extensively and calculated`, so all calculation can be wrong.

```
These values are taken from Simcraft and align with information found on EJ.
```
It's not true, simcraft use same different data.

```
Base damage: Open Simcraft results or "sc_paladin.cpp". You will find them easily.
```
It's not that easy like you said. In code we have something like this (newest version for 433 that I have, simcraft for 434 was never released AFAIK).

```cpp
struct hammer_of_wrath_t : public paladin_attack_t
{
  hammer_of_wrath_t( paladin_t* p, const std::string& options_str )
    : paladin_attack_t( "hammer_of_wrath", "Hammer of Wrath", p, false )
  {
    parse_options( NULL, options_str );

    may_parry    = false;
    may_dodge    = false;
    may_block    = false;
    trigger_dp   = true;
    trigger_seal = 1; // TODO: only SoT or all seals?

    weapon = &( p -> main_hand_weapon );
    weapon_multiplier = 0.0;

    base_crit += p -> talents.sanctified_wrath -> mod_additive( P_CRIT )
                 + p -> talents.wrath_of_the_lightbringer -> mod_additive( P_CRIT );
    base_cost *= p -> glyphs.hammer_of_wrath -> mod_additive( P_RESOURCE_COST );

    base_spell_power_multiplier  = direct_power_mod;
    base_attack_power_multiplier = extra_coeff();
    direct_power_mod             = 1.0;
  }

  virtual bool ready()
  {
    paladin_t* p = player -> cast_paladin();
    if ( target -> health_percentage() > 20 && ! ( p -> talents.sanctified_wrath -> rank() && p -> buffs_avenging_wrath -> check() ) )
      return false;

    return paladin_attack_t::ready();
  }
};
```

We care about only about 2 lines (I put here 3 because need to explain):
```cpp
    base_spell_power_multiplier  = direct_power_mod;
    base_attack_power_multiplier = extra_coeff();
    direct_power_mod             = 1.0;
```
First line set bonus for *SpellPower* it's some variables which is equal to 10th columns:
```csv
  { 14488, 0x00, 24275, 0, E_SCHOOL_DAMAGE             , A_NONE                                     ,  3.9000000954,  0.1000000015,  0.0000000000,  0.1169999987,     0,     0.0,     0.0,     350,       0,       0,     0, 1.000000,   0.0, 2.400, 37, 0, 0 },
```
So it's `0.1169999987`. (you can find this in in `sc_scale_data.inc`)

Seconds line `base_attack_power_multiplier = extra_coeff();` tell as how to calculate *AttackPower` bonus.
This values is taken some another line in the same file line *SpellPower*.
```csv
{ "Hammer of Wrath"                   , 24275, 0x00, 50.0, 0x02,  0, 0x002, 0x000,  2, 0.3900000,  46,  0,     0.0,    30.0,    6000, 1500, 1131,         0,  12, 0x000,   0,   0,   0,  0,    0, 0x00000000, 0x00000000,     0,     0, 20,  1.0000000000,  0, { 14488,     0,     0 }
```

And one again 10th columns it's values which is returned by `extra_coeff` so it's `0.3900000`.

Additional info last what in this line is `{ 14488,     0,     0 }` this number reference to line above from which we taken values for *SpellPower* Bonus.

Server currently have `0.12` bonus from *SpellPower* what will be nerfed to proper values.

If something was not explained enough just ask.

**Comment by Psychobird7** [comment]
After looking into the issue a second time, it seems I made a mistake while gathering data through simcraft results. 
Lama is telling the truth.
