### ISSUE TITLE
[EN][Pet][Class] New hunter pets

### ISSUE THREAD

**Issue by c0ldw1nter** [Atlantiss/BugTracker#9696]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

[//]: # (On the Bugtracker all titles of reports must be written in English so that everyone, no matter which language they use everyday, could search and check if the problem already has been reported by another player. When describing the problem you can use English as well as Polish and in nearest future - others. It is important to determine at the beginning of a title in which language it is written by using symbols [EN] or [PL].)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or http://cata.openwow.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([EN][Quest][Zone] A Vision of the Past)
[//]: # ([EN][NPC] Thoralius the Wise)
[//]: # ([EN][Spell][Class] Frostfire Bolt)
[//]: # ([PL][Talent][Class] Brain Freeze)
[//]: # ([EN][Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([EN][Npc][Drop] Thoralius the Wise)
[//]: # ([EN][Web] Armory doesnt work)

**Description**: Hunter pets tamed since Dec. 03 do not work correctly

**Current behaviour**: The tamed pet does not have an action bar or perform any actions besides following the player. Casting Mend Pet or Dismiss will despawn the pet and produce an error message "You do not have a pet". It also has the name "Unknown" instead of a valid name.

**Expected behaviour**: Pet should behave like it used to before December 3rd.

**Steps to reproduce the problem**:

1.  Tame a new pet

**Revision**: ACore rev. 5536 hash. 808aad465152 2017-10-30 17:50:29 +0100 (4.3.4 branch) (Unix, RelWithDebInfo)

**Comment by RagingShostakovich** [comment]
I have this issue as well. Encountered it in creating a new hunter character. Pet also cannot be named (no option); as above it is 'unknown'. Upon reaching lvl 10 I got the "control pet' passive but could not control pet with petattack or petfollow. The pet will only attack if it pulls aggro, otherwise it will simply follow me and not attack at all.

**Comment by fabricioer** [comment]
I had the same problem, I solved this by storing the pet in the stable master, but I had the same problem when taming another pet

**Comment by c0ldw1nter** [comment]
@fabricioer Can you elaborate on how you solved it by storing the pet in the stable? Because that doesn't help when I try.

**Comment by MatfisMatfis** [comment]
Having the same issue. Went to Terrokar Forest yesterday (Dec 3rd) looking for Warp Stalkers to increase my pet collection, but after succesful, uninterrupted taming it just goes into "Unknown" state. And it's not your usual bug fixed by placing the pet in stable master/relogging. You will be permamently unable to use that pet, as long as this bug exists. Today i tried to tame Ironjaw (Wolf) for its looks, and it went into "Unknown" state. Hope affected pets will be useable after the fix.

PS: Not even the script will help you remove this pet. It permamently decreases your pet capacity overall.

**Comment by MatfisMatfis** [comment]
A few more bugs regarding this:
-Any pet-related ability (ex. Kill Command) will dismiss the bugged pet
-Having the "Unknown" die while its out, will make you unable to switch pets until you relog. (Haven't tried riding away from the corpse, but i guess it would just respawn it nearby you after getting off the mount, or re-calling the "pet")

**Comment by xmesaj2** [comment]
rev. 5543 fixed
