### ISSUE TITLE
[EN][Talent][Death Knight] Mastery: Blood Shield + Death Strike

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#9875]
**Description**: bloodshield should be aplied when a heal occurs from Death Strik's, if u strike someone  when u have 100% hp no healing occurs = no shield

**Current behaviour**: even when u have100% hp when u use Death Strik u get a bloodshield derived from ovearhealing

**Expected behaviour**: if hp > 100% DS heals u and gives a blood shield based on DS hit and mastery and talents

http://www.wowhead.com/spell=77513/mastery-blood-shield#comments
http://www.wowhead.com/spell=49998/death-strike#comments
http://web.archive.org/web/20121108072752/http://elitistjerks.com/f72/t125290-blood_dk_endgame_tanking_4_x/
http://web.archive.org/web/20111113115208/http://pwnwear.com:80/forum/death-knight-detailed-mechanics-t740-15.html
https://us.battle.net/forums/en/wow/topic/20749856931
https://us.battle.net/forums/en/wow/topic/4768448490

**Steps to reproduce the problem**:

1.  be dk
2.  have 100% hp
3.  use ds

**Revision**: rev. 5636

**Comment by Psychobird7** [comment]
Ahh fresh memes.  

- http://www.wowhead.com/spell=77513/mastery-blood-shield#comments 
These comments do not contain a single entry confirming your claims, quite the opposite in fact. 

http://www.wowhead.com/spell=77513/mastery-blood-shield#comments:id=1140124 
"Does this count the overheal? or just effective heal?" 
Answer: 
http://www.wowhead.com/spell=77513/mastery-blood-shield#comments:id=1140124:reply=460344 
Do note the "this is pure speculation". 
"I cannot confirm this, but from the way I read the talent, it is half of the healing done, regardless of the hp you have when you use it... so the shield would have the same strength if you used it to heal yourself at 50% hp as it would if you used deathstrike at 100% health, (and it didnt heal you at all). This only makes sense, because in a raiding situation, your health drops and gets topped off by healers so quickly that it would make the talent useless, because the vast amount of time you used DS it would count as an overheal. This is pure speculation however, and I could be wrong." 


- http://www.wowhead.com/spell=49998/death-strike#comments 
Same here, not a single comment referring to overheal or usage at full HP. 


- https://web.archive.org/web/20121108072752/http://elitistjerks.com/f72/t125290-blood_dk_endgame_tanking_4_x/ 
No mention of overheal here either. 


- https://web.archive.org/web/20111113115208/http://pwnwear.com:80/forum/death-knight-detailed-mechanics-t740-15.html 
This has to be a joke. 


- https://us.battle.net/forums/en/wow/topic/20749856931 
First off, this thread is from 2016. That's early Warlords? Maybe late Mists. 
Read how it is worded. **Overheal into *extra* Blood Shield***. What he means is a DS overheal should give *more* Blood Shield than a normal DS heal. 


- https://us.battle.net/forums/en/wow/topic/4768448490 
No mention of overheal here either.  


Can we get this closed? And, please, for the love of whatever you believe in, stop making these bullshit bug reports.

**Comment by stanq87** [comment]
> 
> if TriggerSpell = DeathStrikeHeal
>    = DequeueSavedValue(BloodShieldTotal) + TriggerHeal * MasteryValue(DeathKnightBloodShield,false)
> if TriggerSpell != DeathStrikeHeal
>    = PeekSavedValue(BloodShieldTotal) - Min(PeekSavedValue(BloodShieldTotal), TriggerDamage)
