### ISSUE TITLE
 [EN][Class][Talent][Spell][Warrior] spell dmg reduction/diminishing

### ISSUE THREAD

**Issue by stanq87** [Atlantiss/BugTracker#9905]
**Description**:
a warrior tank has 3 magic dmg reduction skills, those are:  Defensive Stance(10%) ,  Shield Mastery(7% , 14% and 20%) and Shield Wall (40% or 60%) so at one time a properly glyphed/talented tank in the  right stance should with good timing be able to reduce dmg by 90%, however this dosent seem to be the case

**Current behaviour**:
on ultraxion from  [Hour of Twilight] (300k) we are geting 39-43% dmg around 130k https://youtu.be/MU6i6K9VkXE?t=667 thats 9-13% to much

**Expected behaviour**: 
expected dmg in https://youtu.be/MU6i6K9VkXE?t=667 was 90k so 30%  out of 300k 

Hour of Twilight http://cata-shoot.tauri.hu/?spell=103327
10% Defensive Stance http://cata-shoot.tauri.hu/?spell=71
20% for 6 sec Spell Block http://cata-shoot.tauri.hu/?spell=84608 from [Shield Mastery] (talent) after using [Shield Block]
40%for 12sec Shield Wall http://cata-shoot.tauri.hu/?spell=871

**Steps to reproduce the problem**:

1. be war tank
2. have proper talents + stance + time shieldblock  properly
3. look how much dmg was resived

**Revision**: Current server version

**Comment by Katonetwo** [comment]
those do not stack additively
otherwise prot paladins would be completely immune to all damage if they used divine protection, guardian and ardent defender at the same time

it doesn't work like that

you reduce damage by 10%, 90% remaining (1x0.9)
you reduce by another 20%, 72% remaining  (0.9x0.8)
you reduce by another 40%, 43.2% remaining (0.72x0.6)

43.2% of an hour of twilight would then be 129600
...which is practically exactly the number you listed

damage reduction is working fine

**Comment by stanq87** [comment]
cant really find any source material speaking about it but this http://worldoflogs.com/reports/rt-jct3dli2u61v161w/details/5/?s=9343&e=9705 seems confirming your version
